CREATE TABLE CONVENIENT_global_confirmed_cases(
	"Country/Region_Province/State" varchar2(10) primary key,
	"Afghanistan" int,
	"Albania" int,
	"Algeria" int,
	"Andorra" int,
	"Angola" int,
	"Antigua and Barbuda" int,
	"Argentina" int,
	"Armenia" int,
	"Australia_Australian Capital Territory" int,
	"Australia_New South Wales" int,
	"Australia_Northern Territory" int,
	"Australia_Queensland" int,
	"Australia_South Australia" int,
	"Australia_Tasmania" int,
	"Australia_Victoria" int,
	"Australia_Western Australia" int,
	"Austria" int,
	"Azerbaijan" int,
	"Bahamas" int,
	"Bahrain" int,
	"Bangladesh" int,
	"Barbados" int,
	"Belarus" int,
	"Belgium" int,
	"Belize" int,
	"Benin" int,
	"Bhutan" int,
	"Bolivia" int,
	"Bosnia and Herzegovina" int,
	"Botswana" int,
	"Brazil" int,
	"Brunei" int,
	"Bulgaria" int,
	"Burkina Faso" int,
	"Burma" int,
	"Burundi" int,
	"Cabo Verde" int,
	"Cambodia" int,
	"Cameroon" int,
	"Canada_Alberta" int,
	"Canada_British Columbia" int,
	"Canada_Diamond Princess" int,
	"Canada_Grand Princess" int,
	"Canada_Manitoba" int,
	"Canada_New Brunswick" int,
	"Canada_Newfoundland and Labrador" int,
	"Canada_Northwest Territories" int,
	"Canada_Nova Scotia" int,
	"Canada_Nunavut" int,
	"Canada_Ontario" int,
	"Canada_Prince Edward Island" int,
	"Canada_Quebec" int,
	"Canada_Repatriated Travellers" int,
	"Canada_Saskatchewan" int,
	"Canada_Yukon" int,
	"Central African Republic" int,
	"Chad" int,
	"Chile" int,
	"China_Anhui" int,
	"China_Beijing" int,
	"China_Chongqing" int,
	"China_Fujian" int,
	"China_Gansu" int,
	"China_Guangdong" int,
	"China_Guangxi" int,
	"China_Guizhou" int,
	"China_Hainan" int,
	"China_Hebei" int,
	"China_Heilongjiang" int,
	"China_Henan" int,
	"China_Hong Kong" int,
	"China_Hubei" int,
	"China_Hunan" int,
	"China_Inner Mongolia" int,
	"China_Jiangsu" int,
	"China_Jiangxi" int,
	"China_Jilin" int,
	"China_Liaoning" int,
	"China_Macau" int,
	"China_Ningxia" int,
	"China_Qinghai" int,
	"China_Shaanxi" int,
	"China_Shandong" int,
	"China_Shanghai" int,
	"China_Shanxi" int,
	"China_Sichuan" int,
	"China_Tianjin" int,
	"China_Tibet" int,
	"China_Xinjiang" int,
	"China_Yunnan" int,
	"China_Zhejiang" int,
	"Colombia" int,
	"Comoros" int,
	"Congo (Brazzaville)" int,
	"Congo (Kinshasa)" int,
	"Costa Rica" int,
	"Cote d'Ivoire" int,
	"Croatia" int,
	"Cuba" int,
	"Cyprus" int,
	"Czechia" int,
	"Denmark_Faroe Islands" int,
	"Denmark_Greenland" int,
	"Denmark" int,
	"Diamond Princess" int,
	"Djibouti" int,
	"Dominica" int,
	"Dominican Republic" int,
	"Ecuador" int,
	"Egypt" int,
	"El Salvador" int,
	"Equatorial Guinea" int,
	"Eritrea" int,
	"Estonia" int,
	"Eswatini" int,
	"Ethiopia" int,
	"Fiji" int,
	"Finland" int,
	"France_French Guiana" int,
	"France_French Polynesia" int,
	"France_Guadeloupe" int,
	"France_Martinique" int,
	"France_Mayotte" int,
	"France_New Caledonia" int,
	"France_Reunion" int,
	"France_Saint Barthelemy" int,
	"France_Saint Pierre and Miquelon" int,
	"France_St Martin" int,
	"France" int,
	"Gabon" int,
	"Gambia" int,
	"Georgia" int,
	"Germany" int,
	"Ghana" int,
	"Greece" int,
	"Grenada" int,
	"Guatemala" int,
	"Guinea" int,
	"Guinea-Bissau" int,
	"Guyana" int,
	"Haiti" int,
	"Holy See" int,
	"Honduras" int,
	"Hungary" int,
	"Iceland" int,
	"India" int,
	"Indonesia" int,
	"Iran" int,
	"Iraq" int,
	"Ireland" int,
	"Israel" int,
	"Italy" int,
	"Jamaica" int,
	"Japan" int,
	"Jordan" int,
	"Kazakhstan" int,
	"Kenya" int,
	"Korea, South" int,
	"Kosovo" int,
	"Kuwait" int,
	"Kyrgyzstan" int,
	"Laos" int,
	"Latvia" int,
	"Lebanon" int,
	"Lesotho" int,
	"Liberia" int,
	"Libya" int,
	"Liechtenstein" int,
	"Lithuania" int,
	"Luxembourg" int,
	"MS Zaandam" int,
	"Madagascar" int,
	"Malawi" int,
	"Malaysia" int,
	"Maldives" int,
	"Mali" int,
	"Malta" int,
	"Marshall Islands" int,
	"Mauritania" int,
	"Mauritius" int,
	"Mexico" int,
	"Moldova" int,
	"Monaco" int,
	"Mongolia" int,
	"Montenegro" int,
	"Morocco" int,
	"Mozambique" int,
	"Namibia" int,
	"Nepal_Aruba" int,
	"Netherlands_Bonaire" int,
	"Netherlands_ Sint Eustatius and Saba" int,
	"Netherlands_Curacao" int,
	"Netherlands_Sint Maarten" int,
	"Netherlands" int,
	"New Zealand" int,
	"Nicaragua" int,
	"Niger" int,
	"Nigeria" int,
	"North Macedonia" int,
	"Norway" int,
	"Oman" int,
	"Pakistan" int,
	"Panama" int,
	"Papua New Guinea" int,
	"Paraguay" int,
	"Peru" int,
	"Philippines" int,
	"Poland" int,
	"Portugal" int,
	"Qatar" int,
	"Romania" int,
	"Russia" int,
	"Rwanda" int,
	"Saint Kitts and Nevis" int,
	"Saint Lucia" int,
	"Saint Vincent and the Grenadines" int,
	"Samoa" int,
	"San Marino" int,
	"Sao Tome and Principe" int,
	"Saudi Arabia" int,
	"Senegal" int,
	"Serbia" int,
	"Seychelles" int,
	"Sierra Leone" int,
	"Singapore" int,
	"Slovakia" int,
	"Slovenia" int,
	"Solomon Islands" int,
	"Somalia" int,
	"South Africa" int,
	"South Sudan" int,
	"Spain" int,
	"Sri Lanka" int,
	"Sudan" int,
	"Suriname" int,
	"Sweden" int,
	"Switzerland" int,
	"Syria" int,
	"Taiwan*" int,
	"Tajikistan" int,
	"Tanzania" int,
	"Thailand" int,
	"Timor-Leste" int,
	"Togo" int,
	"Trinidad and Tobago" int,
	"Tunisia" int,
	"Turkey" int,
	"US" int,
	"Uganda" int,
	"Ukraine" int,
	"United Arab Emirates" int,
	"United Kingdom_Anguilla" int,
	"United Kingdom_Bermuda" int,
	"United Kingdom_British Virgin Islands" int,
	"United Kingdom_Cayman Islands" int,
	"United Kingdom_Channel Islands" int,
	"United Kingdom_Falkland Islands (Malvinas)" int,
	"United Kingdom_Gibraltar" int,
	"United Kingdom_Isle of Man" int,
	"United Kingdom_Montserrat" int,
	"United Kingdom_Turks and Caicos Islands" int,
	"United Kingdom" int,
	"Uruguay" int,
	"Uzbekistan" int,
	"Vanuatu" int,
	"Venezuela" int,
	"Vietnam" int,
	"West Bank and Gaza" int,
	"Western Sahara" int,
	"Yemen" int,
	"Zambia" int,
	"Zimbabwe" int
);