CREATE TABLE CONVENIENT_us_deaths_4(
	"Province_State_Admin2" varchar2(10) primary key,
	"South Carolina_Dillon" int,
	"South Carolina_Dorchester" int,
	"South Carolina_Edgefield" int,
	"South Carolina_Fairfield" int,
	"South Carolina_Florence" int,
	"South Carolina_Georgetown" int,
	"South Carolina_Greenville" int,
	"South Carolina_Greenwood" int,
	"South Carolina_Hampton" int,
	"South Carolina_Horry" int,
	"South Carolina_Jasper" int,
	"South Carolina_Kershaw" int,
	"South Carolina_Lancaster" int,
	"South Carolina_Laurens" int,
	"South Carolina_Lee" int,
	"South Carolina_Lexington" int,
	"South Carolina_Marion" int,
	"South Carolina_Marlboro" int,
	"South Carolina_McCormick" int,
	"South Carolina_Newberry" int,
	"South Carolina_Oconee" int,
	"South Carolina_Orangeburg" int,
	"South Carolina_Out of SC" int,
	"South Carolina_Pickens" int,
	"South Carolina_Richland" int,
	"South Carolina_Saluda" int,
	"South Carolina_Spartanburg" int,
	"South Carolina_Sumter" int,
	"South Carolina_Unassigned" int,
	"South Carolina_Union" int,
	"South Carolina_Williamsburg" int,
	"South Carolina_York" int,
	"South Dakota_Aurora" int,
	"South Dakota_Beadle" int,
	"South Dakota_Bennett" int,
	"South Dakota_Bon Homme" int,
	"South Dakota_Brookings" int,
	"South Dakota_Brown" int,
	"South Dakota_Brule" int,
	"South Dakota_Buffalo" int,
	"South Dakota_Butte" int,
	"South Dakota_Campbell" int,
	"South Dakota_Charles Mix" int,
	"South Dakota_Clark" int,
	"South Dakota_Clay" int,
	"South Dakota_Codington" int,
	"South Dakota_Corson" int,
	"South Dakota_Custer" int,
	"South Dakota_Davison" int,
	"South Dakota_Day" int,
	"South Dakota_Deuel" int,
	"South Dakota_Dewey" int,
	"South Dakota_Douglas" int,
	"South Dakota_Edmunds" int,
	"South Dakota_Fall River" int,
	"South Dakota_Faulk" int,
	"South Dakota_Grant" int,
	"South Dakota_Gregory" int,
	"South Dakota_Haakon" int,
	"South Dakota_Hamlin" int,
	"South Dakota_Hand" int,
	"South Dakota_Hanson" int,
	"South Dakota_Harding" int,
	"South Dakota_Hughes" int,
	"South Dakota_Hutchinson" int,
	"South Dakota_Hyde" int,
	"South Dakota_Jackson" int,
	"South Dakota_Jerauld" int,
	"South Dakota_Jones" int,
	"South Dakota_Kingsbury" int,
	"South Dakota_Lake" int,
	"South Dakota_Lawrence" int,
	"South Dakota_Lincoln" int,
	"South Dakota_Lyman" int,
	"South Dakota_Marshall" int,
	"South Dakota_McCook" int,
	"South Dakota_McPherson" int,
	"South Dakota_Meade" int,
	"South Dakota_Mellette" int,
	"South Dakota_Miner" int,
	"South Dakota_Minnehaha" int,
	"South Dakota_Moody" int,
	"South Dakota_Oglala Lakota" int,
	"South Dakota_Out of SD" int,
	"South Dakota_Pennington" int,
	"South Dakota_Perkins" int,
	"South Dakota_Potter" int,
	"South Dakota_Roberts" int,
	"South Dakota_Sanborn" int,
	"South Dakota_Spink" int,
	"South Dakota_Stanley" int,
	"South Dakota_Sully" int,
	"South Dakota_Todd" int,
	"South Dakota_Tripp" int,
	"South Dakota_Turner" int,
	"South Dakota_Unassigned" int,
	"South Dakota_Union" int,
	"South Dakota_Walworth" int,
	"South Dakota_Yankton" int,
	"South Dakota_Ziebach" int,
	"Tennessee_Anderson" int,
	"Tennessee_Bedford" int,
	"Tennessee_Benton" int,
	"Tennessee_Bledsoe" int,
	"Tennessee_Blount" int,
	"Tennessee_Bradley" int,
	"Tennessee_Campbell" int,
	"Tennessee_Cannon" int,
	"Tennessee_Carroll" int,
	"Tennessee_Carter" int,
	"Tennessee_Cheatham" int,
	"Tennessee_Chester" int,
	"Tennessee_Claiborne" int,
	"Tennessee_Clay" int,
	"Tennessee_Cocke" int,
	"Tennessee_Coffee" int,
	"Tennessee_Crockett" int,
	"Tennessee_Cumberland" int,
	"Tennessee_Davidson" int,
	"Tennessee_DeKalb" int,
	"Tennessee_Decatur" int,
	"Tennessee_Dickson" int,
	"Tennessee_Dyer" int,
	"Tennessee_Fayette" int,
	"Tennessee_Fentress" int,
	"Tennessee_Franklin" int,
	"Tennessee_Gibson" int,
	"Tennessee_Giles" int,
	"Tennessee_Grainger" int,
	"Tennessee_Greene" int,
	"Tennessee_Grundy" int,
	"Tennessee_Hamblen" int,
	"Tennessee_Hamilton" int,
	"Tennessee_Hancock" int,
	"Tennessee_Hardeman" int,
	"Tennessee_Hardin" int,
	"Tennessee_Hawkins" int,
	"Tennessee_Haywood" int,
	"Tennessee_Henderson" int,
	"Tennessee_Henry" int,
	"Tennessee_Hickman" int,
	"Tennessee_Houston" int,
	"Tennessee_Humphreys" int,
	"Tennessee_Jackson" int,
	"Tennessee_Jefferson" int,
	"Tennessee_Johnson" int,
	"Tennessee_Knox" int,
	"Tennessee_Lake" int,
	"Tennessee_Lauderdale" int,
	"Tennessee_Lawrence" int,
	"Tennessee_Lewis" int,
	"Tennessee_Lincoln" int,
	"Tennessee_Loudon" int,
	"Tennessee_Macon" int,
	"Tennessee_Madison" int,
	"Tennessee_Marion" int,
	"Tennessee_Marshall" int,
	"Tennessee_Maury" int,
	"Tennessee_McMinn" int,
	"Tennessee_McNairy" int,
	"Tennessee_Meigs" int,
	"Tennessee_Monroe" int,
	"Tennessee_Montgomery" int,
	"Tennessee_Moore" int,
	"Tennessee_Morgan" int,
	"Tennessee_Obion" int,
	"Tennessee_Out of TN" int,
	"Tennessee_Overton" int,
	"Tennessee_Perry" int,
	"Tennessee_Pickett" int,
	"Tennessee_Polk" int,
	"Tennessee_Putnam" int,
	"Tennessee_Rhea" int,
	"Tennessee_Roane" int,
	"Tennessee_Robertson" int,
	"Tennessee_Rutherford" int,
	"Tennessee_Scott" int,
	"Tennessee_Sequatchie" int,
	"Tennessee_Sevier" int,
	"Tennessee_Shelby" int,
	"Tennessee_Smith" int,
	"Tennessee_Stewart" int,
	"Tennessee_Sullivan" int,
	"Tennessee_Sumner" int,
	"Tennessee_Tipton" int,
	"Tennessee_Trousdale" int,
	"Tennessee_Unassigned" int,
	"Tennessee_Unicoi" int,
	"Tennessee_Union" int,
	"Tennessee_Van Buren" int,
	"Tennessee_Warren" int,
	"Tennessee_Washington" int,
	"Tennessee_Wayne" int,
	"Tennessee_Weakley" int,
	"Tennessee_White" int,
	"Tennessee_Williamson" int,
	"Tennessee_Wilson" int,
	"Texas_Anderson" int,
	"Texas_Andrews" int,
	"Texas_Angelina" int,
	"Texas_Aransas" int,
	"Texas_Archer" int,
	"Texas_Armstrong" int,
	"Texas_Atascosa" int,
	"Texas_Austin" int,
	"Texas_Bailey" int,
	"Texas_Bandera" int,
	"Texas_Bastrop" int,
	"Texas_Baylor" int,
	"Texas_Bee" int,
	"Texas_Bell" int,
	"Texas_Bexar" int,
	"Texas_Blanco" int,
	"Texas_Borden" int,
	"Texas_Bosque" int,
	"Texas_Bowie" int,
	"Texas_Brazoria" int,
	"Texas_Brazos" int,
	"Texas_Brewster" int,
	"Texas_Briscoe" int,
	"Texas_Brooks" int,
	"Texas_Brown" int,
	"Texas_Burleson" int,
	"Texas_Burnet" int,
	"Texas_Caldwell" int,
	"Texas_Calhoun" int,
	"Texas_Callahan" int,
	"Texas_Cameron" int,
	"Texas_Camp" int,
	"Texas_Carson" int,
	"Texas_Cass" int,
	"Texas_Castro" int,
	"Texas_Chambers" int,
	"Texas_Cherokee" int,
	"Texas_Childress" int,
	"Texas_Clay" int,
	"Texas_Cochran" int,
	"Texas_Coke" int,
	"Texas_Coleman" int,
	"Texas_Collin" int,
	"Texas_Collingsworth" int,
	"Texas_Colorado" int,
	"Texas_Comal" int,
	"Texas_Comanche" int,
	"Texas_Concho" int,
	"Texas_Cooke" int,
	"Texas_Coryell" int,
	"Texas_Cottle" int,
	"Texas_Crane" int,
	"Texas_Crockett" int,
	"Texas_Crosby" int,
	"Texas_Culberson" int,
	"Texas_Dallam" int,
	"Texas_Dallas" int,
	"Texas_Dawson" int,
	"Texas_DeWitt" int,
	"Texas_Deaf Smith" int,
	"Texas_Delta" int,
	"Texas_Denton" int,
	"Texas_Dickens" int,
	"Texas_Dimmit" int,
	"Texas_Donley" int,
	"Texas_Duval" int,
	"Texas_Eastland" int,
	"Texas_Ector" int,
	"Texas_Edwards" int,
	"Texas_El Paso" int,
	"Texas_Ellis" int,
	"Texas_Erath" int,
	"Texas_Falls" int,
	"Texas_Fannin" int,
	"Texas_Fayette" int,
	"Texas_Fisher" int,
	"Texas_Floyd" int,
	"Texas_Foard" int,
	"Texas_Fort Bend" int,
	"Texas_Franklin" int,
	"Texas_Freestone" int,
	"Texas_Frio" int,
	"Texas_Gaines" int,
	"Texas_Galveston" int,
	"Texas_Garza" int,
	"Texas_Gillespie" int,
	"Texas_Glasscock" int,
	"Texas_Goliad" int,
	"Texas_Gonzales" int,
	"Texas_Gray" int,
	"Texas_Grayson" int,
	"Texas_Gregg" int,
	"Texas_Grimes" int,
	"Texas_Guadalupe" int,
	"Texas_Hale" int,
	"Texas_Hall" int,
	"Texas_Hamilton" int,
	"Texas_Hansford" int,
	"Texas_Hardeman" int,
	"Texas_Hardin" int,
	"Texas_Harris" int,
	"Texas_Harrison" int,
	"Texas_Hartley" int,
	"Texas_Haskell" int,
	"Texas_Hays" int,
	"Texas_Hemphill" int,
	"Texas_Henderson" int,
	"Texas_Hidalgo" int,
	"Texas_Hill" int,
	"Texas_Hockley" int,
	"Texas_Hood" int,
	"Texas_Hopkins" int,
	"Texas_Houston" int,
	"Texas_Howard" int,
	"Texas_Hudspeth" int,
	"Texas_Hunt" int,
	"Texas_Hutchinson" int,
	"Texas_Irion" int,
	"Texas_Jack" int,
	"Texas_Jackson" int,
	"Texas_Jasper" int,
	"Texas_Jeff Davis" int,
	"Texas_Jefferson" int,
	"Texas_Jim Hogg" int,
	"Texas_Jim Wells" int,
	"Texas_Johnson" int,
	"Texas_Jones" int,
	"Texas_Karnes" int,
	"Texas_Kaufman" int,
	"Texas_Kendall" int,
	"Texas_Kenedy" int,
	"Texas_Kent" int,
	"Texas_Kerr" int,
	"Texas_Kimble" int,
	"Texas_King" int,
	"Texas_Kinney" int,
	"Texas_Kleberg" int,
	"Texas_Knox" int,
	"Texas_La Salle" int,
	"Texas_Lamar" int,
	"Texas_Lamb" int,
	"Texas_Lampasas" int,
	"Texas_Lavaca" int,
	"Texas_Lee" int,
	"Texas_Leon" int,
	"Texas_Liberty" int,
	"Texas_Limestone" int,
	"Texas_Lipscomb" int,
	"Texas_Live Oak" int,
	"Texas_Llano" int,
	"Texas_Loving" int,
	"Texas_Lubbock" int,
	"Texas_Lynn" int,
	"Texas_Madison" int,
	"Texas_Marion" int,
	"Texas_Martin" int,
	"Texas_Mason" int,
	"Texas_Matagorda" int,
	"Texas_Maverick" int,
	"Texas_McCulloch" int,
	"Texas_McLennan" int,
	"Texas_McMullen" int,
	"Texas_Medina" int,
	"Texas_Menard" int,
	"Texas_Midland" int,
	"Texas_Milam" int,
	"Texas_Mills" int,
	"Texas_Mitchell" int,
	"Texas_Montague" int,
	"Texas_Montgomery" int,
	"Texas_Moore" int,
	"Texas_Morris" int,
	"Texas_Motley" int,
	"Texas_Nacogdoches" int,
	"Texas_Navarro" int,
	"Texas_Newton" int,
	"Texas_Nolan" int,
	"Texas_Nueces" int,
	"Texas_Ochiltree" int,
	"Texas_Oldham" int,
	"Texas_Orange" int,
	"Texas_Out of TX" int,
	"Texas_Palo Pinto" int,
	"Texas_Panola" int,
	"Texas_Parker" int,
	"Texas_Parmer" int,
	"Texas_Pecos" int,
	"Texas_Polk" int,
	"Texas_Potter" int,
	"Texas_Presidio" int,
	"Texas_Rains" int,
	"Texas_Randall" int,
	"Texas_Reagan" int,
	"Texas_Real" int,
	"Texas_Red River" int,
	"Texas_Reeves" int,
	"Texas_Refugio" int,
	"Texas_Roberts" int,
	"Texas_Robertson" int,
	"Texas_Rockwall" int,
	"Texas_Runnels" int,
	"Texas_Rusk" int,
	"Texas_Sabine" int,
	"Texas_San Augustine" int,
	"Texas_San Jacinto" int,
	"Texas_San Patricio" int,
	"Texas_San Saba" int,
	"Texas_Schleicher" int,
	"Texas_Scurry" int,
	"Texas_Shackelford" int,
	"Texas_Shelby" int,
	"Texas_Sherman" int,
	"Texas_Smith" int,
	"Texas_Somervell" int,
	"Texas_Starr" int,
	"Texas_Stephens" int,
	"Texas_Sterling" int,
	"Texas_Stonewall" int,
	"Texas_Sutton" int,
	"Texas_Swisher" int,
	"Texas_Tarrant" int,
	"Texas_Taylor" int,
	"Texas_Terrell" int,
	"Texas_Terry" int,
	"Texas_Throckmorton" int,
	"Texas_Titus" int,
	"Texas_Tom Green" int,
	"Texas_Travis" int,
	"Texas_Trinity" int,
	"Texas_Tyler" int,
	"Texas_Unassigned" int,
	"Texas_Upshur" int,
	"Texas_Upton" int,
	"Texas_Uvalde" int,
	"Texas_Val Verde" int,
	"Texas_Van Zandt" int,
	"Texas_Victoria" int,
	"Texas_Walker" int,
	"Texas_Waller" int,
	"Texas_Ward" int,
	"Texas_Washington" int,
	"Texas_Webb" int,
	"Texas_Wharton" int,
	"Texas_Wheeler" int,
	"Texas_Wichita" int,
	"Texas_Wilbarger" int,
	"Texas_Willacy" int,
	"Texas_Williamson" int,
	"Texas_Wilson" int,
	"Texas_Winkler" int,
	"Texas_Wise" int,
	"Texas_Wood" int,
	"Texas_Yoakum" int,
	"Texas_Young" int,
	"Texas_Zapata" int,
	"Texas_Zavala" int,
	"Utah_Bear River" int,
	"Utah_Beaver" int,
	"Utah_Box Elder" int,
	"Utah_Cache" int,
	"Utah_Carbon" int,
	"Utah_Central Utah" int,
	"Utah_Daggett" int,
	"Utah_Davis" int,
	"Utah_Duchesne" int,
	"Utah_Emery" int,
	"Utah_Garfield" int,
	"Utah_Grand" int,
	"Utah_Iron" int,
	"Utah_Juab" int,
	"Utah_Kane" int,
	"Utah_Millard" int,
	"Utah_Morgan" int,
	"Utah_Out of UT" int,
	"Utah_Piute" int,
	"Utah_Rich" int,
	"Utah_Salt Lake" int,
	"Utah_San Juan" int,
	"Utah_Sanpete" int,
	"Utah_Sevier" int,
	"Utah_Southeast Utah" int,
	"Utah_Southwest Utah" int,
	"Utah_Summit" int,
	"Utah_Tooele" int,
	"Utah_TriCounty" int,
	"Utah_Uintah" int,
	"Utah_Unassigned" int,
	"Utah_Utah" int,
	"Utah_Wasatch" int,
	"Utah_Washington" int,
	"Utah_Wayne" int,
	"Utah_Weber" int,
	"Utah_Weber-Morgan" int,
	"Vermont_Addison" int,
	"Vermont_Bennington" int,
	"Vermont_Caledonia" int,
	"Vermont_Chittenden" int,
	"Vermont_Essex" int,
	"Vermont_Franklin" int,
	"Vermont_Grand Isle" int,
	"Vermont_Lamoille" int,
	"Vermont_Orange" int,
	"Vermont_Orleans" int,
	"Vermont_Out of VT" int,
	"Vermont_Rutland" int,
	"Vermont_Unassigned" int,
	"Vermont_Washington" int,
	"Vermont_Windham" int,
	"Vermont_Windsor" int,
	"Virgin Islands" int,
	"Virginia_Accomack" int,
	"Virginia_Albemarle" int,
	"Virginia_Alexandria" int,
	"Virginia_Alleghany" int,
	"Virginia_Amelia" int,
	"Virginia_Amherst" int,
	"Virginia_Appomattox" int,
	"Virginia_Arlington" int,
	"Virginia_Augusta" int,
	"Virginia_Bath" int,
	"Virginia_Bedford" int,
	"Virginia_Bland" int,
	"Virginia_Botetourt" int,
	"Virginia_Bristol" int,
	"Virginia_Brunswick" int,
	"Virginia_Buchanan" int,
	"Virginia_Buckingham" int,
	"Virginia_Buena Vista" int,
	"Virginia_Campbell" int,
	"Virginia_Caroline" int,
	"Virginia_Carroll" int,
	"Virginia_Charles City" int,
	"Virginia_Charlotte" int,
	"Virginia_Charlottesville" int,
	"Virginia_Chesapeake" int,
	"Virginia_Chesterfield" int,
	"Virginia_Clarke" int,
	"Virginia_Colonial Heights" int,
	"Virginia_Covington" int,
	"Virginia_Craig" int,
	"Virginia_Culpeper" int,
	"Virginia_Cumberland" int,
	"Virginia_Danville" int,
	"Virginia_Dickenson" int,
	"Virginia_Dinwiddie" int,
	"Virginia_Emporia" int,
	"Virginia_Essex" int,
	"Virginia_Fairfax" int,
	"Virginia_Fairfax City" int,
	"Virginia_Falls Church" int,
	"Virginia_Fauquier" int,
	"Virginia_Floyd" int,
	"Virginia_Fluvanna" int,
	"Virginia_Franklin" int,
	"Virginia_Franklin City" int,
	"Virginia_Frederick" int,
	"Virginia_Fredericksburg" int,
	"Virginia_Galax" int,
	"Virginia_Giles" int,
	"Virginia_Gloucester" int,
	"Virginia_Goochland" int,
	"Virginia_Grayson" int,
	"Virginia_Greene" int,
	"Virginia_Greensville" int,
	"Virginia_Halifax" int,
	"Virginia_Hampton" int,
	"Virginia_Hanover" int,
	"Virginia_Harrisonburg" int,
	"Virginia_Henrico" int,
	"Virginia_Henry" int,
	"Virginia_Highland" int,
	"Virginia_Hopewell" int,
	"Virginia_Isle of Wight" int,
	"Virginia_James City" int,
	"Virginia_King George" int,
	"Virginia_King William" int,
	"Virginia_King and Queen" int,
	"Virginia_Lancaster" int,
	"Virginia_Lee" int,
	"Virginia_Lexington" int,
	"Virginia_Loudoun" int,
	"Virginia_Louisa" int,
	"Virginia_Lunenburg" int,
	"Virginia_Lynchburg" int,
	"Virginia_Madison" int,
	"Virginia_Manassas" int,
	"Virginia_Manassas Park" int,
	"Virginia_Martinsville" int,
	"Virginia_Mathews" int,
	"Virginia_Mecklenburg" int,
	"Virginia_Middlesex" int,
	"Virginia_Montgomery" int,
	"Virginia_Nelson" int,
	"Virginia_New Kent" int,
	"Virginia_Newport News" int,
	"Virginia_Norfolk" int,
	"Virginia_Northampton" int,
	"Virginia_Northumberland" int,
	"Virginia_Norton" int,
	"Virginia_Nottoway" int,
	"Virginia_Orange" int,
	"Virginia_Out of VA" int,
	"Virginia_Page" int,
	"Virginia_Patrick" int,
	"Virginia_Petersburg" int,
	"Virginia_Pittsylvania" int,
	"Virginia_Poquoson" int,
	"Virginia_Portsmouth" int,
	"Virginia_Powhatan" int,
	"Virginia_Prince Edward" int,
	"Virginia_Prince George" int,
	"Virginia_Prince William" int,
	"Virginia_Pulaski" int,
	"Virginia_Radford" int,
	"Virginia_Rappahannock" int,
	"Virginia_Richmond" int,
	"Virginia_Richmond City" int,
	"Virginia_Roanoke" int,
	"Virginia_Roanoke City" int,
	"Virginia_Rockbridge" int,
	"Virginia_Rockingham" int,
	"Virginia_Russell" int,
	"Virginia_Salem" int,
	"Virginia_Scott" int,
	"Virginia_Shenandoah" int,
	"Virginia_Smyth" int,
	"Virginia_Southampton" int,
	"Virginia_Spotsylvania" int,
	"Virginia_Stafford" int,
	"Virginia_Staunton" int,
	"Virginia_Suffolk" int,
	"Virginia_Surry" int,
	"Virginia_Sussex" int,
	"Virginia_Tazewell" int,
	"Virginia_Unassigned" int,
	"Virginia_Virginia Beach" int,
	"Virginia_Warren" int,
	"Virginia_Washington" int,
	"Virginia_Waynesboro" int,
	"Virginia_Westmoreland" int,
	"Virginia_Williamsburg" int,
	"Virginia_Winchester" int,
	"Virginia_Wise" int,
	"Virginia_Wythe" int,
	"Virginia_York" int,
	"Washington_Adams" int,
	"Washington_Asotin" int,
	"Washington_Benton" int,
	"Washington_Chelan" int,
	"Washington_Clallam" int,
	"Washington_Clark" int,
	"Washington_Columbia" int,
	"Washington_Cowlitz" int,
	"Washington_Douglas" int,
	"Washington_Ferry" int,
	"Washington_Franklin" int,
	"Washington_Garfield" int,
	"Washington_Grant" int,
	"Washington_Grays Harbor" int,
	"Washington_Island" int,
	"Washington_Jefferson" int,
	"Washington_King" int,
	"Washington_Kitsap" int,
	"Washington_Kittitas" int,
	"Washington_Klickitat" int,
	"Washington_Lewis" int,
	"Washington_Lincoln" int,
	"Washington_Mason" int,
	"Washington_Okanogan" int,
	"Washington_Out of WA" int,
	"Washington_Pacific" int,
	"Washington_Pend Oreille" int,
	"Washington_Pierce" int,
	"Washington_San Juan" int,
	"Washington_Skagit" int,
	"Washington_Skamania" int,
	"Washington_Snohomish" int,
	"Washington_Spokane" int,
	"Washington_Stevens" int,
	"Washington_Thurston" int,
	"Washington_Unassigned" int,
	"Washington_Wahkiakum" int,
	"Washington_Walla Walla" int,
	"Washington_Whatcom" int,
	"Washington_Whitman" int,
	"Washington_Yakima" int,
	"West Virginia_Barbour" int,
	"West Virginia_Berkeley" int,
	"West Virginia_Boone" int,
	"West Virginia_Braxton" int,
	"West Virginia_Brooke" int,
	"West Virginia_Cabell" int,
	"West Virginia_Calhoun" int,
	"West Virginia_Clay" int,
	"West Virginia_Doddridge" int,
	"West Virginia_Fayette" int,
	"West Virginia_Gilmer" int,
	"West Virginia_Grant" int,
	"West Virginia_Greenbrier" int,
	"West Virginia_Hampshire" int,
	"West Virginia_Hancock" int,
	"West Virginia_Hardy" int,
	"West Virginia_Harrison" int,
	"West Virginia_Jackson" int,
	"West Virginia_Jefferson" int,
	"West Virginia_Kanawha" int,
	"West Virginia_Lewis" int,
	"West Virginia_Lincoln" int,
	"West Virginia_Logan" int,
	"West Virginia_Marion" int,
	"West Virginia_Marshall" int,
	"West Virginia_Mason" int,
	"West Virginia_McDowell" int,
	"West Virginia_Mercer" int,
	"West Virginia_Mineral" int,
	"West Virginia_Mingo" int,
	"West Virginia_Monongalia" int,
	"West Virginia_Monroe" int,
	"West Virginia_Morgan" int,
	"West Virginia_Nicholas" int,
	"West Virginia_Ohio" int,
	"West Virginia_Out of WV" int,
	"West Virginia_Pendleton" int,
	"West Virginia_Pleasants" int,
	"West Virginia_Pocahontas" int,
	"West Virginia_Preston" int,
	"West Virginia_Putnam" int,
	"West Virginia_Raleigh" int,
	"West Virginia_Randolph" int,
	"West Virginia_Ritchie" int,
	"West Virginia_Roane" int,
	"West Virginia_Summers" int,
	"West Virginia_Taylor" int,
	"West Virginia_Tucker" int,
	"West Virginia_Tyler" int,
	"West Virginia_Unassigned" int,
	"West Virginia_Upshur" int,
	"West Virginia_Wayne" int,
	"West Virginia_Webster" int,
	"West Virginia_Wetzel" int,
	"West Virginia_Wirt" int,
	"West Virginia_Wood" int,
	"West Virginia_Wyoming" int,
	"Wisconsin_Adams" int,
	"Wisconsin_Ashland" int,
	"Wisconsin_Barron" int,
	"Wisconsin_Bayfield" int,
	"Wisconsin_Brown" int,
	"Wisconsin_Buffalo" int,
	"Wisconsin_Burnett" int,
	"Wisconsin_Calumet" int,
	"Wisconsin_Chippewa" int,
	"Wisconsin_Clark" int,
	"Wisconsin_Columbia" int,
	"Wisconsin_Crawford" int,
	"Wisconsin_Dane" int,
	"Wisconsin_Dodge" int,
	"Wisconsin_Door" int,
	"Wisconsin_Douglas" int,
	"Wisconsin_Dunn" int,
	"Wisconsin_Eau Claire" int,
	"Wisconsin_Florence" int,
	"Wisconsin_Fond du Lac" int,
	"Wisconsin_Forest" int,
	"Wisconsin_Grant" int,
	"Wisconsin_Green" int,
	"Wisconsin_Green Lake" int,
	"Wisconsin_Iowa" int,
	"Wisconsin_Iron" int,
	"Wisconsin_Jackson" int,
	"Wisconsin_Jefferson" int,
	"Wisconsin_Juneau" int,
	"Wisconsin_Kenosha" int,
	"Wisconsin_Kewaunee" int,
	"Wisconsin_La Crosse" int,
	"Wisconsin_Lafayette" int,
	"Wisconsin_Langlade" int,
	"Wisconsin_Lincoln" int,
	"Wisconsin_Manitowoc" int,
	"Wisconsin_Marathon" int,
	"Wisconsin_Marinette" int,
	"Wisconsin_Marquette" int,
	"Wisconsin_Menominee" int,
	"Wisconsin_Milwaukee" int,
	"Wisconsin_Monroe" int,
	"Wisconsin_Oconto" int,
	"Wisconsin_Oneida" int,
	"Wisconsin_Out of WI" int,
	"Wisconsin_Outagamie" int,
	"Wisconsin_Ozaukee" int,
	"Wisconsin_Pepin" int,
	"Wisconsin_Pierce" int,
	"Wisconsin_Polk" int,
	"Wisconsin_Portage" int,
	"Wisconsin_Price" int,
	"Wisconsin_Racine" int,
	"Wisconsin_Richland" int,
	"Wisconsin_Rock" int,
	"Wisconsin_Rusk" int,
	"Wisconsin_Sauk" int,
	"Wisconsin_Sawyer" int,
	"Wisconsin_Shawano" int,
	"Wisconsin_Sheboygan" int,
	"Wisconsin_St. Croix" int,
	"Wisconsin_Taylor" int,
	"Wisconsin_Trempealeau" int,
	"Wisconsin_Unassigned" int,
	"Wisconsin_Vernon" int,
	"Wisconsin_Vilas" int,
	"Wisconsin_Walworth" int,
	"Wisconsin_Washburn" int,
	"Wisconsin_Washington" int,
	"Wisconsin_Waukesha" int,
	"Wisconsin_Waupaca" int,
	"Wisconsin_Waushara" int,
	"Wisconsin_Winnebago" int,
	"Wisconsin_Wood" int,
	"Wyoming_Albany" int,
	"Wyoming_Big Horn" int,
	"Wyoming_Campbell" int,
	"Wyoming_Carbon" int,
	"Wyoming_Converse" int,
	"Wyoming_Crook" int,
	"Wyoming_Fremont" int,
	"Wyoming_Goshen" int,
	"Wyoming_Hot Springs" int,
	"Wyoming_Johnson" int,
	"Wyoming_Laramie" int,
	"Wyoming_Lincoln" int,
	"Wyoming_Natrona" int,
	"Wyoming_Niobrara" int,
	"Wyoming_Out of WY" int,
	"Wyoming_Park" int,
	"Wyoming_Platte" int,
	"Wyoming_Sheridan" int,
	"Wyoming_Sublette" int,
	"Wyoming_Sweetwater" int,
	"Wyoming_Teton" int,
	"Wyoming_Uinta" int,
	"Wyoming_Unassigned" int,
	"Wyoming_Washakie" int,
	"Wyoming_Weston" int
);