CREATE TABLE CONVENIENT_us_deaths_3(
	"Province_State_Admin2" varchar2(10) primary key,
	"Montana_Dawson" int,
	"Montana_Deer Lodge" int,
	"Montana_Fallon" int,
	"Montana_Fergus" int,
	"Montana_Flathead" int,
	"Montana_Gallatin" int,
	"Montana_Garfield" int,
	"Montana_Glacier" int,
	"Montana_Golden Valley" int,
	"Montana_Granite" int,
	"Montana_Hill" int,
	"Montana_Jefferson" int,
	"Montana_Judith Basin" int,
	"Montana_Lake" int,
	"Montana_Lewis and Clark" int,
	"Montana_Liberty" int,
	"Montana_Lincoln" int,
	"Montana_Madison" int,
	"Montana_McCone" int,
	"Montana_Meagher" int,
	"Montana_Mineral" int,
	"Montana_Missoula" int,
	"Montana_Musselshell" int,
	"Montana_Out of MT" int,
	"Montana_Park" int,
	"Montana_Petroleum" int,
	"Montana_Phillips" int,
	"Montana_Pondera" int,
	"Montana_Powder River" int,
	"Montana_Powell" int,
	"Montana_Prairie" int,
	"Montana_Ravalli" int,
	"Montana_Richland" int,
	"Montana_Roosevelt" int,
	"Montana_Rosebud" int,
	"Montana_Sanders" int,
	"Montana_Sheridan" int,
	"Montana_Silver Bow" int,
	"Montana_Stillwater" int,
	"Montana_Sweet Grass" int,
	"Montana_Teton" int,
	"Montana_Toole" int,
	"Montana_Treasure" int,
	"Montana_Unassigned" int,
	"Montana_Valley" int,
	"Montana_Wheatland" int,
	"Montana_Wibaux" int,
	"Montana_Yellowstone" int,
	"Nebraska_Adams" int,
	"Nebraska_Antelope" int,
	"Nebraska_Arthur" int,
	"Nebraska_Banner" int,
	"Nebraska_Blaine" int,
	"Nebraska_Boone" int,
	"Nebraska_Box Butte" int,
	"Nebraska_Boyd" int,
	"Nebraska_Brown" int,
	"Nebraska_Buffalo" int,
	"Nebraska_Burt" int,
	"Nebraska_Butler" int,
	"Nebraska_Cass" int,
	"Nebraska_Cedar" int,
	"Nebraska_Chase" int,
	"Nebraska_Cherry" int,
	"Nebraska_Cheyenne" int,
	"Nebraska_Clay" int,
	"Nebraska_Colfax" int,
	"Nebraska_Cuming" int,
	"Nebraska_Custer" int,
	"Nebraska_Dakota" int,
	"Nebraska_Dawes" int,
	"Nebraska_Dawson" int,
	"Nebraska_Deuel" int,
	"Nebraska_Dixon" int,
	"Nebraska_Dodge" int,
	"Nebraska_Douglas" int,
	"Nebraska_Dundy" int,
	"Nebraska_Fillmore" int,
	"Nebraska_Franklin" int,
	"Nebraska_Frontier" int,
	"Nebraska_Furnas" int,
	"Nebraska_Gage" int,
	"Nebraska_Garden" int,
	"Nebraska_Garfield" int,
	"Nebraska_Gosper" int,
	"Nebraska_Grant" int,
	"Nebraska_Greeley" int,
	"Nebraska_Hall" int,
	"Nebraska_Hamilton" int,
	"Nebraska_Harlan" int,
	"Nebraska_Hayes" int,
	"Nebraska_Hitchcock" int,
	"Nebraska_Holt" int,
	"Nebraska_Hooker" int,
	"Nebraska_Howard" int,
	"Nebraska_Jefferson" int,
	"Nebraska_Johnson" int,
	"Nebraska_Kearney" int,
	"Nebraska_Keith" int,
	"Nebraska_Keya Paha" int,
	"Nebraska_Kimball" int,
	"Nebraska_Knox" int,
	"Nebraska_Lancaster" int,
	"Nebraska_Lincoln" int,
	"Nebraska_Logan" int,
	"Nebraska_Loup" int,
	"Nebraska_Madison" int,
	"Nebraska_McPherson" int,
	"Nebraska_Merrick" int,
	"Nebraska_Morrill" int,
	"Nebraska_Nance" int,
	"Nebraska_Nemaha" int,
	"Nebraska_Nuckolls" int,
	"Nebraska_Otoe" int,
	"Nebraska_Out of NE" int,
	"Nebraska_Pawnee" int,
	"Nebraska_Perkins" int,
	"Nebraska_Phelps" int,
	"Nebraska_Pierce" int,
	"Nebraska_Platte" int,
	"Nebraska_Polk" int,
	"Nebraska_Red Willow" int,
	"Nebraska_Richardson" int,
	"Nebraska_Rock" int,
	"Nebraska_Saline" int,
	"Nebraska_Sarpy" int,
	"Nebraska_Saunders" int,
	"Nebraska_Scotts Bluff" int,
	"Nebraska_Seward" int,
	"Nebraska_Sheridan" int,
	"Nebraska_Sherman" int,
	"Nebraska_Sioux" int,
	"Nebraska_Stanton" int,
	"Nebraska_Thayer" int,
	"Nebraska_Thomas" int,
	"Nebraska_Thurston" int,
	"Nebraska_Unassigned" int,
	"Nebraska_Valley" int,
	"Nebraska_Washington" int,
	"Nebraska_Wayne" int,
	"Nebraska_Webster" int,
	"Nebraska_Wheeler" int,
	"Nebraska_York" int,
	"Nevada_Carson City" int,
	"Nevada_Churchill" int,
	"Nevada_Clark" int,
	"Nevada_Douglas" int,
	"Nevada_Elko" int,
	"Nevada_Esmeralda" int,
	"Nevada_Eureka" int,
	"Nevada_Humboldt" int,
	"Nevada_Lander" int,
	"Nevada_Lincoln" int,
	"Nevada_Lyon" int,
	"Nevada_Mineral" int,
	"Nevada_Nye" int,
	"Nevada_Out of NV" int,
	"Nevada_Pershing" int,
	"Nevada_Storey" int,
	"Nevada_Unassigned" int,
	"Nevada_Washoe" int,
	"Nevada_White Pine" int,
	"New Hampshire_Belknap" int,
	"New Hampshire_Carroll" int,
	"New Hampshire_Cheshire" int,
	"New Hampshire_Coos" int,
	"New Hampshire_Grafton" int,
	"New Hampshire_Hillsborough" int,
	"New Hampshire_Merrimack" int,
	"New Hampshire_Out of NH" int,
	"New Hampshire_Rockingham" int,
	"New Hampshire_Strafford" int,
	"New Hampshire_Sullivan" int,
	"New Hampshire_Unassigned" int,
	"New Jersey_Atlantic" int,
	"New Jersey_Bergen" int,
	"New Jersey_Burlington" int,
	"New Jersey_Camden" int,
	"New Jersey_Cape May" int,
	"New Jersey_Cumberland" int,
	"New Jersey_Essex" int,
	"New Jersey_Gloucester" int,
	"New Jersey_Hudson" int,
	"New Jersey_Hunterdon" int,
	"New Jersey_Mercer" int,
	"New Jersey_Middlesex" int,
	"New Jersey_Monmouth" int,
	"New Jersey_Morris" int,
	"New Jersey_Ocean" int,
	"New Jersey_Out of NJ" int,
	"New Jersey_Passaic" int,
	"New Jersey_Salem" int,
	"New Jersey_Somerset" int,
	"New Jersey_Sussex" int,
	"New Jersey_Unassigned" int,
	"New Jersey_Union" int,
	"New Jersey_Warren" int,
	"New Mexico_Bernalillo" int,
	"New Mexico_Catron" int,
	"New Mexico_Chaves" int,
	"New Mexico_Cibola" int,
	"New Mexico_Colfax" int,
	"New Mexico_Curry" int,
	"New Mexico_De Baca" int,
	"New Mexico_Dona Ana" int,
	"New Mexico_Eddy" int,
	"New Mexico_Grant" int,
	"New Mexico_Guadalupe" int,
	"New Mexico_Harding" int,
	"New Mexico_Hidalgo" int,
	"New Mexico_Lea" int,
	"New Mexico_Lincoln" int,
	"New Mexico_Los Alamos" int,
	"New Mexico_Luna" int,
	"New Mexico_McKinley" int,
	"New Mexico_Mora" int,
	"New Mexico_Otero" int,
	"New Mexico_Out of NM" int,
	"New Mexico_Quay" int,
	"New Mexico_Rio Arriba" int,
	"New Mexico_Roosevelt" int,
	"New Mexico_San Juan" int,
	"New Mexico_San Miguel" int,
	"New Mexico_Sandoval" int,
	"New Mexico_Santa Fe" int,
	"New Mexico_Sierra" int,
	"New Mexico_Socorro" int,
	"New Mexico_Taos" int,
	"New Mexico_Torrance" int,
	"New Mexico_Unassigned" int,
	"New Mexico_Union" int,
	"New Mexico_Valencia" int,
	"New York_Albany" int,
	"New York_Allegany" int,
	"New York_Bronx" int,
	"New York_Broome" int,
	"New York_Cattaraugus" int,
	"New York_Cayuga" int,
	"New York_Chautauqua" int,
	"New York_Chemung" int,
	"New York_Chenango" int,
	"New York_Clinton" int,
	"New York_Columbia" int,
	"New York_Cortland" int,
	"New York_Delaware" int,
	"New York_Dutchess" int,
	"New York_Erie" int,
	"New York_Essex" int,
	"New York_Franklin" int,
	"New York_Fulton" int,
	"New York_Genesee" int,
	"New York_Greene" int,
	"New York_Hamilton" int,
	"New York_Herkimer" int,
	"New York_Jefferson" int,
	"New York_Kings" int,
	"New York_Lewis" int,
	"New York_Livingston" int,
	"New York_Madison" int,
	"New York_Monroe" int,
	"New York_Montgomery" int,
	"New York_Nassau" int,
	"New York_New York" int,
	"New York_Niagara" int,
	"New York_Oneida" int,
	"New York_Onondaga" int,
	"New York_Ontario" int,
	"New York_Orange" int,
	"New York_Orleans" int,
	"New York_Oswego" int,
	"New York_Otsego" int,
	"New York_Out of NY" int,
	"New York_Putnam" int,
	"New York_Queens" int,
	"New York_Rensselaer" int,
	"New York_Richmond" int,
	"New York_Rockland" int,
	"New York_Saratoga" int,
	"New York_Schenectady" int,
	"New York_Schoharie" int,
	"New York_Schuyler" int,
	"New York_Seneca" int,
	"New York_St. Lawrence" int,
	"New York_Steuben" int,
	"New York_Suffolk" int,
	"New York_Sullivan" int,
	"New York_Tioga" int,
	"New York_Tompkins" int,
	"New York_Ulster" int,
	"New York_Unassigned" int,
	"New York_Warren" int,
	"New York_Washington" int,
	"New York_Wayne" int,
	"New York_Westchester" int,
	"New York_Wyoming" int,
	"New York_Yates" int,
	"North Carolina_Alamance" int,
	"North Carolina_Alexander" int,
	"North Carolina_Alleghany" int,
	"North Carolina_Anson" int,
	"North Carolina_Ashe" int,
	"North Carolina_Avery" int,
	"North Carolina_Beaufort" int,
	"North Carolina_Bertie" int,
	"North Carolina_Bladen" int,
	"North Carolina_Brunswick" int,
	"North Carolina_Buncombe" int,
	"North Carolina_Burke" int,
	"North Carolina_Cabarrus" int,
	"North Carolina_Caldwell" int,
	"North Carolina_Camden" int,
	"North Carolina_Carteret" int,
	"North Carolina_Caswell" int,
	"North Carolina_Catawba" int,
	"North Carolina_Chatham" int,
	"North Carolina_Cherokee" int,
	"North Carolina_Chowan" int,
	"North Carolina_Clay" int,
	"North Carolina_Cleveland" int,
	"North Carolina_Columbus" int,
	"North Carolina_Craven" int,
	"North Carolina_Cumberland" int,
	"North Carolina_Currituck" int,
	"North Carolina_Dare" int,
	"North Carolina_Davidson" int,
	"North Carolina_Davie" int,
	"North Carolina_Duplin" int,
	"North Carolina_Durham" int,
	"North Carolina_Edgecombe" int,
	"North Carolina_Forsyth" int,
	"North Carolina_Franklin" int,
	"North Carolina_Gaston" int,
	"North Carolina_Gates" int,
	"North Carolina_Graham" int,
	"North Carolina_Granville" int,
	"North Carolina_Greene" int,
	"North Carolina_Guilford" int,
	"North Carolina_Halifax" int,
	"North Carolina_Harnett" int,
	"North Carolina_Haywood" int,
	"North Carolina_Henderson" int,
	"North Carolina_Hertford" int,
	"North Carolina_Hoke" int,
	"North Carolina_Hyde" int,
	"North Carolina_Iredell" int,
	"North Carolina_Jackson" int,
	"North Carolina_Johnston" int,
	"North Carolina_Jones" int,
	"North Carolina_Lee" int,
	"North Carolina_Lenoir" int,
	"North Carolina_Lincoln" int,
	"North Carolina_Macon" int,
	"North Carolina_Madison" int,
	"North Carolina_Martin" int,
	"North Carolina_McDowell" int,
	"North Carolina_Mecklenburg" int,
	"North Carolina_Mitchell" int,
	"North Carolina_Montgomery" int,
	"North Carolina_Moore" int,
	"North Carolina_Nash" int,
	"North Carolina_New Hanover" int,
	"North Carolina_Northampton" int,
	"North Carolina_Onslow" int,
	"North Carolina_Orange" int,
	"North Carolina_Out of NC" int,
	"North Carolina_Pamlico" int,
	"North Carolina_Pasquotank" int,
	"North Carolina_Pender" int,
	"North Carolina_Perquimans" int,
	"North Carolina_Person" int,
	"North Carolina_Pitt" int,
	"North Carolina_Polk" int,
	"North Carolina_Randolph" int,
	"North Carolina_Richmond" int,
	"North Carolina_Robeson" int,
	"North Carolina_Rockingham" int,
	"North Carolina_Rowan" int,
	"North Carolina_Rutherford" int,
	"North Carolina_Sampson" int,
	"North Carolina_Scotland" int,
	"North Carolina_Stanly" int,
	"North Carolina_Stokes" int,
	"North Carolina_Surry" int,
	"North Carolina_Swain" int,
	"North Carolina_Transylvania" int,
	"North Carolina_Tyrrell" int,
	"North Carolina_Unassigned" int,
	"North Carolina_Union" int,
	"North Carolina_Vance" int,
	"North Carolina_Wake" int,
	"North Carolina_Warren" int,
	"North Carolina_Washington" int,
	"North Carolina_Watauga" int,
	"North Carolina_Wayne" int,
	"North Carolina_Wilkes" int,
	"North Carolina_Wilson" int,
	"North Carolina_Yadkin" int,
	"North Carolina_Yancey" int,
	"North Dakota_Adams" int,
	"North Dakota_Barnes" int,
	"North Dakota_Benson" int,
	"North Dakota_Billings" int,
	"North Dakota_Bottineau" int,
	"North Dakota_Bowman" int,
	"North Dakota_Burke" int,
	"North Dakota_Burleigh" int,
	"North Dakota_Cass" int,
	"North Dakota_Cavalier" int,
	"North Dakota_Dickey" int,
	"North Dakota_Divide" int,
	"North Dakota_Dunn" int,
	"North Dakota_Eddy" int,
	"North Dakota_Emmons" int,
	"North Dakota_Foster" int,
	"North Dakota_Golden Valley" int,
	"North Dakota_Grand Forks" int,
	"North Dakota_Grant" int,
	"North Dakota_Griggs" int,
	"North Dakota_Hettinger" int,
	"North Dakota_Kidder" int,
	"North Dakota_LaMoure" int,
	"North Dakota_Logan" int,
	"North Dakota_McHenry" int,
	"North Dakota_McIntosh" int,
	"North Dakota_McKenzie" int,
	"North Dakota_McLean" int,
	"North Dakota_Mercer" int,
	"North Dakota_Morton" int,
	"North Dakota_Mountrail" int,
	"North Dakota_Nelson" int,
	"North Dakota_Oliver" int,
	"North Dakota_Out of ND" int,
	"North Dakota_Pembina" int,
	"North Dakota_Pierce" int,
	"North Dakota_Ramsey" int,
	"North Dakota_Ransom" int,
	"North Dakota_Renville" int,
	"North Dakota_Richland" int,
	"North Dakota_Rolette" int,
	"North Dakota_Sargent" int,
	"North Dakota_Sheridan" int,
	"North Dakota_Sioux" int,
	"North Dakota_Slope" int,
	"North Dakota_Stark" int,
	"North Dakota_Steele" int,
	"North Dakota_Stutsman" int,
	"North Dakota_Towner" int,
	"North Dakota_Traill" int,
	"North Dakota_Unassigned" int,
	"North Dakota_Walsh" int,
	"North Dakota_Ward" int,
	"North Dakota_Wells" int,
	"North Dakota_Williams" int,
	"Northern Mariana Islands" int,
	"Ohio_Adams" int,
	"Ohio_Allen" int,
	"Ohio_Ashland" int,
	"Ohio_Ashtabula" int,
	"Ohio_Athens" int,
	"Ohio_Auglaize" int,
	"Ohio_Belmont" int,
	"Ohio_Brown" int,
	"Ohio_Butler" int,
	"Ohio_Carroll" int,
	"Ohio_Champaign" int,
	"Ohio_Clark" int,
	"Ohio_Clermont" int,
	"Ohio_Clinton" int,
	"Ohio_Columbiana" int,
	"Ohio_Coshocton" int,
	"Ohio_Crawford" int,
	"Ohio_Cuyahoga" int,
	"Ohio_Darke" int,
	"Ohio_Defiance" int,
	"Ohio_Delaware" int,
	"Ohio_Erie" int,
	"Ohio_Fairfield" int,
	"Ohio_Fayette" int,
	"Ohio_Franklin" int,
	"Ohio_Fulton" int,
	"Ohio_Gallia" int,
	"Ohio_Geauga" int,
	"Ohio_Greene" int,
	"Ohio_Guernsey" int,
	"Ohio_Hamilton" int,
	"Ohio_Hancock" int,
	"Ohio_Hardin" int,
	"Ohio_Harrison" int,
	"Ohio_Henry" int,
	"Ohio_Highland" int,
	"Ohio_Hocking" int,
	"Ohio_Holmes" int,
	"Ohio_Huron" int,
	"Ohio_Jackson" int,
	"Ohio_Jefferson" int,
	"Ohio_Knox" int,
	"Ohio_Lake" int,
	"Ohio_Lawrence" int,
	"Ohio_Licking" int,
	"Ohio_Logan" int,
	"Ohio_Lorain" int,
	"Ohio_Lucas" int,
	"Ohio_Madison" int,
	"Ohio_Mahoning" int,
	"Ohio_Marion" int,
	"Ohio_Medina" int,
	"Ohio_Meigs" int,
	"Ohio_Mercer" int,
	"Ohio_Miami" int,
	"Ohio_Monroe" int,
	"Ohio_Montgomery" int,
	"Ohio_Morgan" int,
	"Ohio_Morrow" int,
	"Ohio_Muskingum" int,
	"Ohio_Noble" int,
	"Ohio_Ottawa" int,
	"Ohio_Out of OH" int,
	"Ohio_Paulding" int,
	"Ohio_Perry" int,
	"Ohio_Pickaway" int,
	"Ohio_Pike" int,
	"Ohio_Portage" int,
	"Ohio_Preble" int,
	"Ohio_Putnam" int,
	"Ohio_Richland" int,
	"Ohio_Ross" int,
	"Ohio_Sandusky" int,
	"Ohio_Scioto" int,
	"Ohio_Seneca" int,
	"Ohio_Shelby" int,
	"Ohio_Stark" int,
	"Ohio_Summit" int,
	"Ohio_Trumbull" int,
	"Ohio_Tuscarawas" int,
	"Ohio_Unassigned" int,
	"Ohio_Union" int,
	"Ohio_Van Wert" int,
	"Ohio_Vinton" int,
	"Ohio_Warren" int,
	"Ohio_Washington" int,
	"Ohio_Wayne" int,
	"Ohio_Williams" int,
	"Ohio_Wood" int,
	"Ohio_Wyandot" int,
	"Oklahoma_Adair" int,
	"Oklahoma_Alfalfa" int,
	"Oklahoma_Atoka" int,
	"Oklahoma_Beaver" int,
	"Oklahoma_Beckham" int,
	"Oklahoma_Blaine" int,
	"Oklahoma_Bryan" int,
	"Oklahoma_Caddo" int,
	"Oklahoma_Canadian" int,
	"Oklahoma_Carter" int,
	"Oklahoma_Cherokee" int,
	"Oklahoma_Choctaw" int,
	"Oklahoma_Cimarron" int,
	"Oklahoma_Cleveland" int,
	"Oklahoma_Coal" int,
	"Oklahoma_Comanche" int,
	"Oklahoma_Cotton" int,
	"Oklahoma_Craig" int,
	"Oklahoma_Creek" int,
	"Oklahoma_Custer" int,
	"Oklahoma_Delaware" int,
	"Oklahoma_Dewey" int,
	"Oklahoma_Ellis" int,
	"Oklahoma_Garfield" int,
	"Oklahoma_Garvin" int,
	"Oklahoma_Grady" int,
	"Oklahoma_Grant" int,
	"Oklahoma_Greer" int,
	"Oklahoma_Harmon" int,
	"Oklahoma_Harper" int,
	"Oklahoma_Haskell" int,
	"Oklahoma_Hughes" int,
	"Oklahoma_Jackson" int,
	"Oklahoma_Jefferson" int,
	"Oklahoma_Johnston" int,
	"Oklahoma_Kay" int,
	"Oklahoma_Kingfisher" int,
	"Oklahoma_Kiowa" int,
	"Oklahoma_Latimer" int,
	"Oklahoma_Le Flore" int,
	"Oklahoma_Lincoln" int,
	"Oklahoma_Logan" int,
	"Oklahoma_Love" int,
	"Oklahoma_Major" int,
	"Oklahoma_Marshall" int,
	"Oklahoma_Mayes" int,
	"Oklahoma_McClain" int,
	"Oklahoma_McCurtain" int,
	"Oklahoma_McIntosh" int,
	"Oklahoma_Murray" int,
	"Oklahoma_Muskogee" int,
	"Oklahoma_Noble" int,
	"Oklahoma_Nowata" int,
	"Oklahoma_Okfuskee" int,
	"Oklahoma_Oklahoma" int,
	"Oklahoma_Okmulgee" int,
	"Oklahoma_Osage" int,
	"Oklahoma_Ottawa" int,
	"Oklahoma_Out of OK" int,
	"Oklahoma_Pawnee" int,
	"Oklahoma_Payne" int,
	"Oklahoma_Pittsburg" int,
	"Oklahoma_Pontotoc" int,
	"Oklahoma_Pottawatomie" int,
	"Oklahoma_Pushmataha" int,
	"Oklahoma_Roger Mills" int,
	"Oklahoma_Rogers" int,
	"Oklahoma_Seminole" int,
	"Oklahoma_Sequoyah" int,
	"Oklahoma_Stephens" int,
	"Oklahoma_Texas" int,
	"Oklahoma_Tillman" int,
	"Oklahoma_Tulsa" int,
	"Oklahoma_Unassigned" int,
	"Oklahoma_Wagoner" int,
	"Oklahoma_Washington" int,
	"Oklahoma_Washita" int,
	"Oklahoma_Woods" int,
	"Oklahoma_Woodward" int,
	"Oregon_Baker" int,
	"Oregon_Benton" int,
	"Oregon_Clackamas" int,
	"Oregon_Clatsop" int,
	"Oregon_Columbia" int,
	"Oregon_Coos" int,
	"Oregon_Crook" int,
	"Oregon_Curry" int,
	"Oregon_Deschutes" int,
	"Oregon_Douglas" int,
	"Oregon_Gilliam" int,
	"Oregon_Grant" int,
	"Oregon_Harney" int,
	"Oregon_Hood River" int,
	"Oregon_Jackson" int,
	"Oregon_Jefferson" int,
	"Oregon_Josephine" int,
	"Oregon_Klamath" int,
	"Oregon_Lake" int,
	"Oregon_Lane" int,
	"Oregon_Lincoln" int,
	"Oregon_Linn" int,
	"Oregon_Malheur" int,
	"Oregon_Marion" int,
	"Oregon_Morrow" int,
	"Oregon_Multnomah" int,
	"Oregon_Out of OR" int,
	"Oregon_Polk" int,
	"Oregon_Sherman" int,
	"Oregon_Tillamook" int,
	"Oregon_Umatilla" int,
	"Oregon_Unassigned" int,
	"Oregon_Union" int,
	"Oregon_Wallowa" int,
	"Oregon_Wasco" int,
	"Oregon_Washington" int,
	"Oregon_Wheeler" int,
	"Oregon_Yamhill" int,
	"Pennsylvania_Adams" int,
	"Pennsylvania_Allegheny" int,
	"Pennsylvania_Armstrong" int,
	"Pennsylvania_Beaver" int,
	"Pennsylvania_Bedford" int,
	"Pennsylvania_Berks" int,
	"Pennsylvania_Blair" int,
	"Pennsylvania_Bradford" int,
	"Pennsylvania_Bucks" int,
	"Pennsylvania_Butler" int,
	"Pennsylvania_Cambria" int,
	"Pennsylvania_Cameron" int,
	"Pennsylvania_Carbon" int,
	"Pennsylvania_Centre" int,
	"Pennsylvania_Chester" int,
	"Pennsylvania_Clarion" int,
	"Pennsylvania_Clearfield" int,
	"Pennsylvania_Clinton" int,
	"Pennsylvania_Columbia" int,
	"Pennsylvania_Crawford" int,
	"Pennsylvania_Cumberland" int,
	"Pennsylvania_Dauphin" int,
	"Pennsylvania_Delaware" int,
	"Pennsylvania_Elk" int,
	"Pennsylvania_Erie" int,
	"Pennsylvania_Fayette" int,
	"Pennsylvania_Forest" int,
	"Pennsylvania_Franklin" int,
	"Pennsylvania_Fulton" int,
	"Pennsylvania_Greene" int,
	"Pennsylvania_Huntingdon" int,
	"Pennsylvania_Indiana" int,
	"Pennsylvania_Jefferson" int,
	"Pennsylvania_Juniata" int,
	"Pennsylvania_Lackawanna" int,
	"Pennsylvania_Lancaster" int,
	"Pennsylvania_Lawrence" int,
	"Pennsylvania_Lebanon" int,
	"Pennsylvania_Lehigh" int,
	"Pennsylvania_Luzerne" int,
	"Pennsylvania_Lycoming" int,
	"Pennsylvania_McKean" int,
	"Pennsylvania_Mercer" int,
	"Pennsylvania_Mifflin" int,
	"Pennsylvania_Monroe" int,
	"Pennsylvania_Montgomery" int,
	"Pennsylvania_Montour" int,
	"Pennsylvania_Northampton" int,
	"Pennsylvania_Northumberland" int,
	"Pennsylvania_Out of PA" int,
	"Pennsylvania_Perry" int,
	"Pennsylvania_Philadelphia" int,
	"Pennsylvania_Pike" int,
	"Pennsylvania_Potter" int,
	"Pennsylvania_Schuylkill" int,
	"Pennsylvania_Snyder" int,
	"Pennsylvania_Somerset" int,
	"Pennsylvania_Sullivan" int,
	"Pennsylvania_Susquehanna" int,
	"Pennsylvania_Tioga" int,
	"Pennsylvania_Unassigned" int,
	"Pennsylvania_Union" int,
	"Pennsylvania_Venango" int,
	"Pennsylvania_Warren" int,
	"Pennsylvania_Washington" int,
	"Pennsylvania_Wayne" int,
	"Pennsylvania_Westmoreland" int,
	"Pennsylvania_Wyoming" int,
	"Pennsylvania_York" int,
	"Puerto Rico_Adjuntas" int,
	"Puerto Rico_Aguada" int,
	"Puerto Rico_Aguadilla" int,
	"Puerto Rico_Aguas Buenas" int,
	"Puerto Rico_Aibonito" int,
	"Puerto Rico_Anasco" int,
	"Puerto Rico_Arecibo" int,
	"Puerto Rico_Arroyo" int,
	"Puerto Rico_Barceloneta" int,
	"Puerto Rico_Barranquitas" int,
	"Puerto Rico_Bayamon" int,
	"Puerto Rico_Cabo Rojo" int,
	"Puerto Rico_Caguas" int,
	"Puerto Rico_Camuy" int,
	"Puerto Rico_Canovanas" int,
	"Puerto Rico_Carolina" int,
	"Puerto Rico_Catano" int,
	"Puerto Rico_Cayey" int,
	"Puerto Rico_Ceiba" int,
	"Puerto Rico_Ciales" int,
	"Puerto Rico_Cidra" int,
	"Puerto Rico_Coamo" int,
	"Puerto Rico_Comerio" int,
	"Puerto Rico_Corozal" int,
	"Puerto Rico_Culebra" int,
	"Puerto Rico_Dorado" int,
	"Puerto Rico_Fajardo" int,
	"Puerto Rico_Florida" int,
	"Puerto Rico_Guanica" int,
	"Puerto Rico_Guayama" int,
	"Puerto Rico_Guayanilla" int,
	"Puerto Rico_Guaynabo" int,
	"Puerto Rico_Gurabo" int,
	"Puerto Rico_Hatillo" int,
	"Puerto Rico_Hormigueros" int,
	"Puerto Rico_Humacao" int,
	"Puerto Rico_Isabela" int,
	"Puerto Rico_Jayuya" int,
	"Puerto Rico_Juana Diaz" int,
	"Puerto Rico_Juncos" int,
	"Puerto Rico_Lajas" int,
	"Puerto Rico_Lares" int,
	"Puerto Rico_Las Marias" int,
	"Puerto Rico_Las Piedras" int,
	"Puerto Rico_Loiza" int,
	"Puerto Rico_Luquillo" int,
	"Puerto Rico_Manati" int,
	"Puerto Rico_Maricao" int,
	"Puerto Rico_Maunabo" int,
	"Puerto Rico_Mayaguez" int,
	"Puerto Rico_Moca" int,
	"Puerto Rico_Morovis" int,
	"Puerto Rico_Naguabo" int,
	"Puerto Rico_Naranjito" int,
	"Puerto Rico_Orocovis" int,
	"Puerto Rico_Out of PR" int,
	"Puerto Rico_Patillas" int,
	"Puerto Rico_Penuelas" int,
	"Puerto Rico_Ponce" int,
	"Puerto Rico_Quebradillas" int,
	"Puerto Rico_Rincon" int,
	"Puerto Rico_Rio Grande" int,
	"Puerto Rico_Sabana Grande" int,
	"Puerto Rico_Salinas" int,
	"Puerto Rico_San German" int,
	"Puerto Rico_San Juan" int,
	"Puerto Rico_San Lorenzo" int,
	"Puerto Rico_San Sebastian" int,
	"Puerto Rico_Santa Isabel" int,
	"Puerto Rico_Toa Alta" int,
	"Puerto Rico_Toa Baja" int,
	"Puerto Rico_Trujillo Alto" int,
	"Puerto Rico_Unassigned" int,
	"Puerto Rico_Utuado" int,
	"Puerto Rico_Vega Alta" int,
	"Puerto Rico_Vega Baja" int,
	"Puerto Rico_Vieques" int,
	"Puerto Rico_Villalba" int,
	"Puerto Rico_Yabucoa" int,
	"Puerto Rico_Yauco" int,
	"Rhode Island_Bristol" int,
	"Rhode Island_Kent" int,
	"Rhode Island_Newport" int,
	"Rhode Island_Out of RI" int,
	"Rhode Island_Providence" int,
	"Rhode Island_Unassigned" int,
	"Rhode Island_Washington" int,
	"South Carolina_Abbeville" int,
	"South Carolina_Aiken" int,
	"South Carolina_Allendale" int,
	"South Carolina_Anderson" int,
	"South Carolina_Bamberg" int,
	"South Carolina_Barnwell" int,
	"South Carolina_Beaufort" int,
	"South Carolina_Berkeley" int,
	"South Carolina_Calhoun" int,
	"South Carolina_Charleston" int,
	"South Carolina_Cherokee" int,
	"South Carolina_Chester" int,
	"South Carolina_Chesterfield" int,
	"South Carolina_Clarendon" int,
	"South Carolina_Colleton" int,
	"South Carolina_Darlington" int
);