CREATE TABLE CONVENIENT_us_deaths_1(
	"Province_State_Admin2" varchar2(10) primary key,
	"Alabama_Autauga" int,
	"Alabama_Baldwin" int,
	"Alabama_Barbour" int,
	"Alabama_Bibb" int,
	"Alabama_Blount" int,
	"Alabama_Bullock" int,
	"Alabama_Butler" int,
	"Alabama_Calhoun" int,
	"Alabama_Chambers" int,
	"Alabama_Cherokee" int,
	"Alabama_Chilton" int,
	"Alabama_Choctaw" int,
	"Alabama_Clarke" int,
	"Alabama_Clay" int,
	"Alabama_Cleburne" int,
	"Alabama_Coffee" int,
	"Alabama_Colbert" int,
	"Alabama_Conecuh" int,
	"Alabama_Coosa" int,
	"Alabama_Covington" int,
	"Alabama_Crenshaw" int,
	"Alabama_Cullman" int,
	"Alabama_Dale" int,
	"Alabama_Dallas" int,
	"Alabama_DeKalb" int,
	"Alabama_Elmore" int,
	"Alabama_Escambia" int,
	"Alabama_Etowah" int,
	"Alabama_Fayette" int,
	"Alabama_Franklin" int,
	"Alabama_Geneva" int,
	"Alabama_Greene" int,
	"Alabama_Hale" int,
	"Alabama_Henry" int,
	"Alabama_Houston" int,
	"Alabama_Jackson" int,
	"Alabama_Jefferson" int,
	"Alabama_Lamar" int,
	"Alabama_Lauderdale" int,
	"Alabama_Lawrence" int,
	"Alabama_Lee" int,
	"Alabama_Limestone" int,
	"Alabama_Lowndes" int,
	"Alabama_Macon" int,
	"Alabama_Madison" int,
	"Alabama_Marengo" int,
	"Alabama_Marion" int,
	"Alabama_Marshall" int,
	"Alabama_Mobile" int,
	"Alabama_Monroe" int,
	"Alabama_Montgomery" int,
	"Alabama_Morgan" int,
	"Alabama_Out of AL" int,
	"Alabama_Perry" int,
	"Alabama_Pickens" int,
	"Alabama_Pike" int,
	"Alabama_Randolph" int,
	"Alabama_Russell" int,
	"Alabama_Shelby" int,
	"Alabama_St. Clair" int,
	"Alabama_Sumter" int,
	"Alabama_Talladega" int,
	"Alabama_Tallapoosa" int,
	"Alabama_Tuscaloosa" int,
	"Alabama_Unassigned" int,
	"Alabama_Walker" int,
	"Alabama_Washington" int,
	"Alabama_Wilcox" int,
	"Alabama_Winston" int,
	"Alaska_Aleutians East" int,
	"Alaska_Aleutians West" int,
	"Alaska_Anchorage" int,
	"Alaska_Bethel" int,
	"Alaska_Bristol Bay" int,
	"Alaska_Bristol Bay plus Lake and Peninsula" int,
	"Alaska_Denali" int,
	"Alaska_Dillingham" int,
	"Alaska_Fairbanks North Star" int,
	"Alaska_Haines" int,
	"Alaska_Hoonah-Angoon" int,
	"Alaska_Juneau" int,
	"Alaska_Kenai Peninsula" int,
	"Alaska_Ketchikan Gateway" int,
	"Alaska_Kodiak Island" int,
	"Alaska_Kusilvak" int,
	"Alaska_Matanuska-Susitna" int,
	"Alaska_Nome" int,
	"Alaska_North Slope" int,
	"Alaska_Northwest Arctic" int,
	"Alaska_Out of AK" int,
	"Alaska_Petersburg" int,
	"Alaska_Prince of Wales-Hyder" int,
	"Alaska_Sitka" int,
	"Alaska_Skagway" int,
	"Alaska_Southeast Fairbanks" int,
	"Alaska_Unassigned" int,
	"Alaska_Valdez-Cordova" int,
	"Alaska_Wrangell" int,
	"Alaska_Yakutat" int,
	"Alaska_Yukon-Koyukuk" int,
	"American Samoa" int,
	"Arizona_Apache" int,
	"Arizona_Cochise" int,
	"Arizona_Coconino" int,
	"Arizona_Gila" int,
	"Arizona_Graham" int,
	"Arizona_Greenlee" int,
	"Arizona_La Paz" int,
	"Arizona_Maricopa" int,
	"Arizona_Mohave" int,
	"Arizona_Navajo" int,
	"Arizona_Out of AZ" int,
	"Arizona_Pima" int,
	"Arizona_Pinal" int,
	"Arizona_Santa Cruz" int,
	"Arizona_Unassigned" int,
	"Arizona_Yavapai" int,
	"Arizona_Yuma" int,
	"Arkansas_Arkansas" int,
	"Arkansas_Ashley" int,
	"Arkansas_Baxter" int,
	"Arkansas_Benton" int,
	"Arkansas_Boone" int,
	"Arkansas_Bradley" int,
	"Arkansas_Calhoun" int,
	"Arkansas_Carroll" int,
	"Arkansas_Chicot" int,
	"Arkansas_Clark" int,
	"Arkansas_Clay" int,
	"Arkansas_Cleburne" int,
	"Arkansas_Cleveland" int,
	"Arkansas_Columbia" int,
	"Arkansas_Conway" int,
	"Arkansas_Craighead" int,
	"Arkansas_Crawford" int,
	"Arkansas_Crittenden" int,
	"Arkansas_Cross" int,
	"Arkansas_Dallas" int,
	"Arkansas_Desha" int,
	"Arkansas_Drew" int,
	"Arkansas_Faulkner" int,
	"Arkansas_Franklin" int,
	"Arkansas_Fulton" int,
	"Arkansas_Garland" int,
	"Arkansas_Grant" int,
	"Arkansas_Greene" int,
	"Arkansas_Hempstead" int,
	"Arkansas_Hot Spring" int,
	"Arkansas_Howard" int,
	"Arkansas_Independence" int,
	"Arkansas_Izard" int,
	"Arkansas_Jackson" int,
	"Arkansas_Jefferson" int,
	"Arkansas_Johnson" int,
	"Arkansas_Lafayette" int,
	"Arkansas_Lawrence" int,
	"Arkansas_Lee" int,
	"Arkansas_Lincoln" int,
	"Arkansas_Little River" int,
	"Arkansas_Logan" int,
	"Arkansas_Lonoke" int,
	"Arkansas_Madison" int,
	"Arkansas_Marion" int,
	"Arkansas_Miller" int,
	"Arkansas_Mississippi" int,
	"Arkansas_Monroe" int,
	"Arkansas_Montgomery" int,
	"Arkansas_Nevada" int,
	"Arkansas_Newton" int,
	"Arkansas_Ouachita" int,
	"Arkansas_Out of AR" int,
	"Arkansas_Perry" int,
	"Arkansas_Phillips" int,
	"Arkansas_Pike" int,
	"Arkansas_Poinsett" int,
	"Arkansas_Polk" int,
	"Arkansas_Pope" int,
	"Arkansas_Prairie" int,
	"Arkansas_Pulaski" int,
	"Arkansas_Randolph" int,
	"Arkansas_Saline" int,
	"Arkansas_Scott" int,
	"Arkansas_Searcy" int,
	"Arkansas_Sebastian" int,
	"Arkansas_Sevier" int,
	"Arkansas_Sharp" int,
	"Arkansas_St. Francis" int,
	"Arkansas_Stone" int,
	"Arkansas_Unassigned" int,
	"Arkansas_Union" int,
	"Arkansas_Van Buren" int,
	"Arkansas_Washington" int,
	"Arkansas_White" int,
	"Arkansas_Woodruff" int,
	"Arkansas_Yell" int,
	"California_Alameda" int,
	"California_Alpine" int,
	"California_Amador" int,
	"California_Butte" int,
	"California_Calaveras" int,
	"California_Colusa" int,
	"California_Contra Costa" int,
	"California_Del Norte" int,
	"California_El Dorado" int,
	"California_Fresno" int,
	"California_Glenn" int,
	"California_Humboldt" int,
	"California_Imperial" int,
	"California_Inyo" int,
	"California_Kern" int,
	"California_Kings" int,
	"California_Lake" int,
	"California_Lassen" int,
	"California_Los Angeles" int,
	"California_Madera" int,
	"California_Marin" int,
	"California_Mariposa" int,
	"California_Mendocino" int,
	"California_Merced" int,
	"California_Modoc" int,
	"California_Mono" int,
	"California_Monterey" int,
	"California_Napa" int,
	"California_Nevada" int,
	"California_Orange" int,
	"California_Out of CA" int,
	"California_Placer" int,
	"California_Plumas" int,
	"California_Riverside" int,
	"California_Sacramento" int,
	"California_San Benito" int,
	"California_San Bernardino" int,
	"California_San Diego" int,
	"California_San Francisco" int,
	"California_San Joaquin" int,
	"California_San Luis Obispo" int,
	"California_San Mateo" int,
	"California_Santa Barbara" int,
	"California_Santa Clara" int,
	"California_Santa Cruz" int,
	"California_Shasta" int,
	"California_Sierra" int,
	"California_Siskiyou" int,
	"California_Solano" int,
	"California_Sonoma" int,
	"California_Stanislaus" int,
	"California_Sutter" int,
	"California_Tehama" int,
	"California_Trinity" int,
	"California_Tulare" int,
	"California_Tuolumne" int,
	"California_Unassigned" int,
	"California_Ventura" int,
	"California_Yolo" int,
	"California_Yuba" int,
	"Colorado_Adams" int,
	"Colorado_Alamosa" int,
	"Colorado_Arapahoe" int,
	"Colorado_Archuleta" int,
	"Colorado_Baca" int,
	"Colorado_Bent" int,
	"Colorado_Boulder" int,
	"Colorado_Broomfield" int,
	"Colorado_Chaffee" int,
	"Colorado_Cheyenne" int,
	"Colorado_Clear Creek" int,
	"Colorado_Conejos" int,
	"Colorado_Costilla" int,
	"Colorado_Crowley" int,
	"Colorado_Custer" int,
	"Colorado_Delta" int,
	"Colorado_Denver" int,
	"Colorado_Dolores" int,
	"Colorado_Douglas" int,
	"Colorado_Eagle" int,
	"Colorado_El Paso" int,
	"Colorado_Elbert" int,
	"Colorado_Fremont" int,
	"Colorado_Garfield" int,
	"Colorado_Gilpin" int,
	"Colorado_Grand" int,
	"Colorado_Gunnison" int,
	"Colorado_Hinsdale" int,
	"Colorado_Huerfano" int,
	"Colorado_Jackson" int,
	"Colorado_Jefferson" int,
	"Colorado_Kiowa" int,
	"Colorado_Kit Carson" int,
	"Colorado_La Plata" int,
	"Colorado_Lake" int,
	"Colorado_Larimer" int,
	"Colorado_Las Animas" int,
	"Colorado_Lincoln" int,
	"Colorado_Logan" int,
	"Colorado_Mesa" int,
	"Colorado_Mineral" int,
	"Colorado_Moffat" int,
	"Colorado_Montezuma" int,
	"Colorado_Montrose" int,
	"Colorado_Morgan" int,
	"Colorado_Otero" int,
	"Colorado_Ouray" int,
	"Colorado_Out of CO" int,
	"Colorado_Park" int,
	"Colorado_Phillips" int,
	"Colorado_Pitkin" int,
	"Colorado_Prowers" int,
	"Colorado_Pueblo" int,
	"Colorado_Rio Blanco" int,
	"Colorado_Rio Grande" int,
	"Colorado_Routt" int,
	"Colorado_Saguache" int,
	"Colorado_San Juan" int,
	"Colorado_San Miguel" int,
	"Colorado_Sedgwick" int,
	"Colorado_Summit" int,
	"Colorado_Teller" int,
	"Colorado_Unassigned" int,
	"Colorado_Washington" int,
	"Colorado_Weld" int,
	"Colorado_Yuma" int,
	"Connecticut_Fairfield" int,
	"Connecticut_Hartford" int,
	"Connecticut_Litchfield" int,
	"Connecticut_Middlesex" int,
	"Connecticut_New Haven" int,
	"Connecticut_New London" int,
	"Connecticut_Out of CT" int,
	"Connecticut_Tolland" int,
	"Connecticut_Unassigned" int,
	"Connecticut_Windham" int,
	"Delaware_Kent" int,
	"Delaware_New Castle" int,
	"Delaware_Out of DE" int,
	"Delaware_Sussex" int,
	"Delaware_Unassigned" int,
	"Diamond Princess" int,
	"District of Columbia_District of Columbia" int,
	"District of Columbia_Out of DC" int,
	"District of Columbia_Unassigned" int,
	"Florida_Alachua" int,
	"Florida_Baker" int,
	"Florida_Bay" int,
	"Florida_Bradford" int,
	"Florida_Brevard" int,
	"Florida_Broward" int,
	"Florida_Calhoun" int,
	"Florida_Charlotte" int,
	"Florida_Citrus" int,
	"Florida_Clay" int,
	"Florida_Collier" int,
	"Florida_Columbia" int,
	"Florida_DeSoto" int,
	"Florida_Dixie" int,
	"Florida_Duval" int,
	"Florida_Escambia" int,
	"Florida_Flagler" int,
	"Florida_Franklin" int,
	"Florida_Gadsden" int,
	"Florida_Gilchrist" int,
	"Florida_Glades" int,
	"Florida_Gulf" int,
	"Florida_Hamilton" int,
	"Florida_Hardee" int,
	"Florida_Hendry" int,
	"Florida_Hernando" int,
	"Florida_Highlands" int,
	"Florida_Hillsborough" int,
	"Florida_Holmes" int,
	"Florida_Indian River" int,
	"Florida_Jackson" int,
	"Florida_Jefferson" int,
	"Florida_Lafayette" int,
	"Florida_Lake" int,
	"Florida_Lee" int,
	"Florida_Leon" int,
	"Florida_Levy" int,
	"Florida_Liberty" int,
	"Florida_Madison" int,
	"Florida_Manatee" int,
	"Florida_Marion" int,
	"Florida_Martin" int,
	"Florida_Miami-Dade" int,
	"Florida_Monroe" int,
	"Florida_Nassau" int,
	"Florida_Okaloosa" int,
	"Florida_Okeechobee" int,
	"Florida_Orange" int,
	"Florida_Osceola" int,
	"Florida_Out of FL" int,
	"Florida_Palm Beach" int,
	"Florida_Pasco" int,
	"Florida_Pinellas" int,
	"Florida_Polk" int,
	"Florida_Putnam" int,
	"Florida_Santa Rosa" int,
	"Florida_Sarasota" int,
	"Florida_Seminole" int,
	"Florida_St. Johns" int,
	"Florida_St. Lucie" int,
	"Florida_Sumter" int,
	"Florida_Suwannee" int,
	"Florida_Taylor" int,
	"Florida_Unassigned" int,
	"Florida_Union" int,
	"Florida_Volusia" int,
	"Florida_Wakulla" int,
	"Florida_Walton" int,
	"Florida_Washington" int,
	"Georgia_Appling" int,
	"Georgia_Atkinson" int,
	"Georgia_Bacon" int,
	"Georgia_Baker" int,
	"Georgia_Baldwin" int,
	"Georgia_Banks" int,
	"Georgia_Barrow" int,
	"Georgia_Bartow" int,
	"Georgia_Ben Hill" int,
	"Georgia_Berrien" int,
	"Georgia_Bibb" int,
	"Georgia_Bleckley" int,
	"Georgia_Brantley" int,
	"Georgia_Brooks" int,
	"Georgia_Bryan" int,
	"Georgia_Bulloch" int,
	"Georgia_Burke" int,
	"Georgia_Butts" int,
	"Georgia_Calhoun" int,
	"Georgia_Camden" int,
	"Georgia_Candler" int,
	"Georgia_Carroll" int,
	"Georgia_Catoosa" int,
	"Georgia_Charlton" int,
	"Georgia_Chatham" int,
	"Georgia_Chattahoochee" int,
	"Georgia_Chattooga" int,
	"Georgia_Cherokee" int,
	"Georgia_Clarke" int,
	"Georgia_Clay" int,
	"Georgia_Clayton" int,
	"Georgia_Clinch" int,
	"Georgia_Cobb" int,
	"Georgia_Coffee" int,
	"Georgia_Colquitt" int,
	"Georgia_Columbia" int,
	"Georgia_Cook" int,
	"Georgia_Coweta" int,
	"Georgia_Crawford" int,
	"Georgia_Crisp" int,
	"Georgia_Dade" int,
	"Georgia_Dawson" int,
	"Georgia_DeKalb" int,
	"Georgia_Decatur" int,
	"Georgia_Dodge" int,
	"Georgia_Dooly" int,
	"Georgia_Dougherty" int,
	"Georgia_Douglas" int,
	"Georgia_Early" int,
	"Georgia_Echols" int,
	"Georgia_Effingham" int,
	"Georgia_Elbert" int,
	"Georgia_Emanuel" int,
	"Georgia_Evans" int,
	"Georgia_Fannin" int,
	"Georgia_Fayette" int,
	"Georgia_Floyd" int,
	"Georgia_Forsyth" int,
	"Georgia_Franklin" int,
	"Georgia_Fulton" int,
	"Georgia_Gilmer" int,
	"Georgia_Glascock" int,
	"Georgia_Glynn" int,
	"Georgia_Gordon" int,
	"Georgia_Grady" int,
	"Georgia_Greene" int,
	"Georgia_Gwinnett" int,
	"Georgia_Habersham" int,
	"Georgia_Hall" int,
	"Georgia_Hancock" int,
	"Georgia_Haralson" int,
	"Georgia_Harris" int,
	"Georgia_Hart" int,
	"Georgia_Heard" int,
	"Georgia_Henry" int,
	"Georgia_Houston" int,
	"Georgia_Irwin" int,
	"Georgia_Jackson" int,
	"Georgia_Jasper" int,
	"Georgia_Jeff Davis" int,
	"Georgia_Jefferson" int,
	"Georgia_Jenkins" int,
	"Georgia_Johnson" int,
	"Georgia_Jones" int,
	"Georgia_Lamar" int,
	"Georgia_Lanier" int,
	"Georgia_Laurens" int,
	"Georgia_Lee" int,
	"Georgia_Liberty" int,
	"Georgia_Lincoln" int,
	"Georgia_Long" int,
	"Georgia_Lowndes" int,
	"Georgia_Lumpkin" int,
	"Georgia_Macon" int,
	"Georgia_Madison" int,
	"Georgia_Marion" int,
	"Georgia_McDuffie" int,
	"Georgia_McIntosh" int,
	"Georgia_Meriwether" int,
	"Georgia_Miller" int,
	"Georgia_Mitchell" int,
	"Georgia_Monroe" int,
	"Georgia_Montgomery" int,
	"Georgia_Morgan" int,
	"Georgia_Murray" int,
	"Georgia_Muscogee" int,
	"Georgia_Newton" int,
	"Georgia_Oconee" int,
	"Georgia_Oglethorpe" int,
	"Georgia_Out of GA" int,
	"Georgia_Paulding" int,
	"Georgia_Peach" int,
	"Georgia_Pickens" int,
	"Georgia_Pierce" int,
	"Georgia_Pike" int,
	"Georgia_Polk" int,
	"Georgia_Pulaski" int,
	"Georgia_Putnam" int,
	"Georgia_Quitman" int,
	"Georgia_Rabun" int,
	"Georgia_Randolph" int,
	"Georgia_Richmond" int,
	"Georgia_Rockdale" int,
	"Georgia_Schley" int,
	"Georgia_Screven" int,
	"Georgia_Seminole" int,
	"Georgia_Spalding" int,
	"Georgia_Stephens" int,
	"Georgia_Stewart" int,
	"Georgia_Sumter" int,
	"Georgia_Talbot" int,
	"Georgia_Taliaferro" int,
	"Georgia_Tattnall" int,
	"Georgia_Taylor" int,
	"Georgia_Telfair" int,
	"Georgia_Terrell" int,
	"Georgia_Thomas" int,
	"Georgia_Tift" int,
	"Georgia_Toombs" int,
	"Georgia_Towns" int,
	"Georgia_Treutlen" int,
	"Georgia_Troup" int,
	"Georgia_Turner" int,
	"Georgia_Twiggs" int,
	"Georgia_Unassigned" int,
	"Georgia_Union" int,
	"Georgia_Upson" int,
	"Georgia_Walker" int,
	"Georgia_Walton" int,
	"Georgia_Ware" int,
	"Georgia_Warren" int,
	"Georgia_Washington" int,
	"Georgia_Wayne" int,
	"Georgia_Webster" int,
	"Georgia_Wheeler" int,
	"Georgia_White" int,
	"Georgia_Whitfield" int,
	"Georgia_Wilcox" int,
	"Georgia_Wilkes" int,
	"Georgia_Wilkinson" int,
	"Georgia_Worth" int,
	"Grand Princess" int,
	"Guam" int,
	"Hawaii_Hawaii" int,
	"Hawaii_Honolulu" int,
	"Hawaii_Kalawao" int,
	"Hawaii_Kauai" int,
	"Hawaii_Maui" int,
	"Hawaii_Out of HI" int,
	"Hawaii_Unassigned" int,
	"Idaho_Ada" int,
	"Idaho_Adams" int,
	"Idaho_Bannock" int,
	"Idaho_Bear Lake" int,
	"Idaho_Benewah" int,
	"Idaho_Bingham" int,
	"Idaho_Blaine" int,
	"Idaho_Boise" int,
	"Idaho_Bonner" int,
	"Idaho_Bonneville" int,
	"Idaho_Boundary" int,
	"Idaho_Butte" int,
	"Idaho_Camas" int,
	"Idaho_Canyon" int,
	"Idaho_Caribou" int,
	"Idaho_Cassia" int,
	"Idaho_Clark" int,
	"Idaho_Clearwater" int,
	"Idaho_Custer" int,
	"Idaho_Elmore" int,
	"Idaho_Franklin" int,
	"Idaho_Fremont" int,
	"Idaho_Gem" int,
	"Idaho_Gooding" int,
	"Idaho_Idaho" int,
	"Idaho_Jefferson" int,
	"Idaho_Jerome" int,
	"Idaho_Kootenai" int,
	"Idaho_Latah" int,
	"Idaho_Lemhi" int,
	"Idaho_Lewis" int,
	"Idaho_Lincoln" int,
	"Idaho_Madison" int,
	"Idaho_Minidoka" int,
	"Idaho_Nez Perce" int,
	"Idaho_Oneida" int,
	"Idaho_Out of ID" int,
	"Idaho_Owyhee" int,
	"Idaho_Payette" int,
	"Idaho_Power" int,
	"Idaho_Shoshone" int,
	"Idaho_Teton" int,
	"Idaho_Twin Falls" int,
	"Idaho_Unassigned" int,
	"Idaho_Valley" int,
	"Idaho_Washington" int,
	"Illinois_Adams" int,
	"Illinois_Alexander" int,
	"Illinois_Bond" int,
	"Illinois_Boone" int,
	"Illinois_Brown" int,
	"Illinois_Bureau" int,
	"Illinois_Calhoun" int,
	"Illinois_Carroll" int,
	"Illinois_Cass" int,
	"Illinois_Champaign" int,
	"Illinois_Christian" int,
	"Illinois_Clark" int,
	"Illinois_Clay" int,
	"Illinois_Clinton" int,
	"Illinois_Coles" int,
	"Illinois_Cook" int,
	"Illinois_Crawford" int,
	"Illinois_Cumberland" int,
	"Illinois_De Witt" int,
	"Illinois_DeKalb" int,
	"Illinois_Douglas" int,
	"Illinois_DuPage" int,
	"Illinois_Edgar" int,
	"Illinois_Edwards" int,
	"Illinois_Effingham" int,
	"Illinois_Fayette" int,
	"Illinois_Ford" int,
	"Illinois_Franklin" int,
	"Illinois_Fulton" int,
	"Illinois_Gallatin" int,
	"Illinois_Greene" int,
	"Illinois_Grundy" int,
	"Illinois_Hamilton" int,
	"Illinois_Hancock" int,
	"Illinois_Hardin" int,
	"Illinois_Henderson" int,
	"Illinois_Henry" int,
	"Illinois_Iroquois" int,
	"Illinois_Jackson" int,
	"Illinois_Jasper" int,
	"Illinois_Jefferson" int,
	"Illinois_Jersey" int,
	"Illinois_Jo Daviess" int,
	"Illinois_Johnson" int,
	"Illinois_Kane" int,
	"Illinois_Kankakee" int,
	"Illinois_Kendall" int,
	"Illinois_Knox" int,
	"Illinois_LaSalle" int,
	"Illinois_Lake" int,
	"Illinois_Lawrence" int,
	"Illinois_Lee" int,
	"Illinois_Livingston" int,
	"Illinois_Logan" int,
	"Illinois_Macon" int,
	"Illinois_Macoupin" int,
	"Illinois_Madison" int,
	"Illinois_Marion" int,
	"Illinois_Marshall" int,
	"Illinois_Mason" int,
	"Illinois_Massac" int,
	"Illinois_McDonough" int,
	"Illinois_McHenry" int,
	"Illinois_McLean" int,
	"Illinois_Menard" int,
	"Illinois_Mercer" int,
	"Illinois_Monroe" int,
	"Illinois_Montgomery" int,
	"Illinois_Morgan" int,
	"Illinois_Moultrie" int,
	"Illinois_Ogle" int,
	"Illinois_Out of IL" int,
	"Illinois_Peoria" int,
	"Illinois_Perry" int,
	"Illinois_Piatt" int,
	"Illinois_Pike" int,
	"Illinois_Pope" int,
	"Illinois_Pulaski" int,
	"Illinois_Putnam" int,
	"Illinois_Randolph" int,
	"Illinois_Richland" int,
	"Illinois_Rock Island" int,
	"Illinois_Saline" int,
	"Illinois_Sangamon" int,
	"Illinois_Schuyler" int,
	"Illinois_Scott" int,
	"Illinois_Shelby" int,
	"Illinois_St. Clair" int,
	"Illinois_Stark" int,
	"Illinois_Stephenson" int,
	"Illinois_Tazewell" int,
	"Illinois_Unassigned" int,
	"Illinois_Union" int,
	"Illinois_Vermilion" int,
	"Illinois_Wabash" int,
	"Illinois_Warren" int,
	"Illinois_Washington" int,
	"Illinois_Wayne" int,
	"Illinois_White" int,
	"Illinois_Whiteside" int,
	"Illinois_Will" int,
	"Illinois_Williamson" int,
	"Illinois_Winnebago" int,
	"Illinois_Woodford" int,
	"Indiana_Adams" int,
	"Indiana_Allen" int,
	"Indiana_Bartholomew" int,
	"Indiana_Benton" int,
	"Indiana_Blackford" int,
	"Indiana_Boone" int,
	"Indiana_Brown" int,
	"Indiana_Carroll" int,
	"Indiana_Cass" int,
	"Indiana_Clark" int,
	"Indiana_Clay" int,
	"Indiana_Clinton" int,
	"Indiana_Crawford" int,
	"Indiana_Daviess" int,
	"Indiana_DeKalb" int,
	"Indiana_Dearborn" int,
	"Indiana_Decatur" int,
	"Indiana_Delaware" int,
	"Indiana_Dubois" int,
	"Indiana_Elkhart" int,
	"Indiana_Fayette" int,
	"Indiana_Floyd" int,
	"Indiana_Fountain" int,
	"Indiana_Franklin" int,
	"Indiana_Fulton" int,
	"Indiana_Gibson" int,
	"Indiana_Grant" int,
	"Indiana_Greene" int,
	"Indiana_Hamilton" int,
	"Indiana_Hancock" int,
	"Indiana_Harrison" int,
	"Indiana_Hendricks" int,
	"Indiana_Henry" int,
	"Indiana_Howard" int,
	"Indiana_Huntington" int,
	"Indiana_Jackson" int,
	"Indiana_Jasper" int,
	"Indiana_Jay" int,
	"Indiana_Jefferson" int,
	"Indiana_Jennings" int,
	"Indiana_Johnson" int,
	"Indiana_Knox" int,
	"Indiana_Kosciusko" int,
	"Indiana_LaGrange" int,
	"Indiana_LaPorte" int,
	"Indiana_Lake" int,
	"Indiana_Lawrence" int,
	"Indiana_Madison" int,
	"Indiana_Marion" int,
	"Indiana_Marshall" int,
	"Indiana_Martin" int,
	"Indiana_Miami" int,
	"Indiana_Monroe" int,
	"Indiana_Montgomery" int,
	"Indiana_Morgan" int,
	"Indiana_Newton" int,
	"Indiana_Noble" int,
	"Indiana_Ohio" int,
	"Indiana_Orange" int,
	"Indiana_Out of IN" int,
	"Indiana_Owen" int,
	"Indiana_Parke" int,
	"Indiana_Perry" int,
	"Indiana_Pike" int,
	"Indiana_Porter" int,
	"Indiana_Posey" int,
	"Indiana_Pulaski" int,
	"Indiana_Putnam" int,
	"Indiana_Randolph" int,
	"Indiana_Ripley" int,
	"Indiana_Rush" int,
	"Indiana_Scott" int,
	"Indiana_Shelby" int,
	"Indiana_Spencer" int,
	"Indiana_St. Joseph" int,
	"Indiana_Starke" int,
	"Indiana_Steuben" int,
	"Indiana_Sullivan" int,
	"Indiana_Switzerland" int,
	"Indiana_Tippecanoe" int,
	"Indiana_Tipton" int,
	"Indiana_Unassigned" int,
	"Indiana_Union" int,
	"Indiana_Vanderburgh" int,
	"Indiana_Vermillion" int,
	"Indiana_Vigo" int,
	"Indiana_Wabash" int,
	"Indiana_Warren" int,
	"Indiana_Warrick" int,
	"Indiana_Washington" int,
	"Indiana_Wayne" int,
	"Indiana_Wells" int,
	"Indiana_White" int,
	"Indiana_Whitley" int,
	"Iowa_Adair" int,
	"Iowa_Adams" int,
	"Iowa_Allamakee" int,
	"Iowa_Appanoose" int,
	"Iowa_Audubon" int,
	"Iowa_Benton" int,
	"Iowa_Black Hawk" int,
	"Iowa_Boone" int,
	"Iowa_Bremer" int,
	"Iowa_Buchanan" int,
	"Iowa_Buena Vista" int
);