CREATE TABLE CONVENIENT_us_confirmed_cases(
	"Province_State_Admin2" varchar2(10) primary key,
	"Alabama_Autauga" int,
	"Alabama_Baldwin" int,
	"Alabama_Barbour" int,
	"Alabama_Bibb" int,
	"Alabama_Blount" int,
	"Alabama_Bullock" int,
	"Alabama_Butler" int,
	"Alabama_Calhoun" int,
	"Alabama_Chambers" int,
	"Alabama_Cherokee" int,
	"Alabama_Chilton" int,
	"Alabama_Choctaw" int,
	"Alabama_Clarke" int,
	"Alabama_Clay" int,
	"Alabama_Cleburne" int,
	"Alabama_Coffee" int,
	"Alabama_Colbert" int,
	"Alabama_Conecuh" int,
	"Alabama_Coosa" int,
	"Alabama_Covington" int,
	"Alabama_Crenshaw" int,
	"Alabama_Cullman" int,
	"Alabama_Dale" int,
	"Alabama_Dallas" int,
	"Alabama_DeKalb" int,
	"Alabama_Elmore" int,
	"Alabama_Escambia" int,
	"Alabama_Etowah" int,
	"Alabama_Fayette" int,
	"Alabama_Franklin" int,
	"Alabama_Geneva" int,
	"Alabama_Greene" int,
	"Alabama_Hale" int,
	"Alabama_Henry" int,
	"Alabama_Houston" int,
	"Alabama_Jackson" int,
	"Alabama_Jefferson" int,
	"Alabama_Lamar" int,
	"Alabama_Lauderdale" int,
	"Alabama_Lawrence" int,
	"Alabama_Lee" int,
	"Alabama_Limestone" int,
	"Alabama_Lowndes" int,
	"Alabama_Macon" int,
	"Alabama_Madison" int,
	"Alabama_Marengo" int,
	"Alabama_Marion" int,
	"Alabama_Marshall" int,
	"Alabama_Mobile" int,
	"Alabama_Monroe" int,
	"Alabama_Montgomery" int,
	"Alabama_Morgan" int,
	"Alabama_Out of AL" int,
	"Alabama_Perry" int,
	"Alabama_Pickens" int,
	"Alabama_Pike" int,
	"Alabama_Randolph" int,
	"Alabama_Russell" int,
	"Alabama_Shelby" int,
	"Alabama_St. Clair" int,
	"Alabama_Sumter" int,
	"Alabama_Talladega" int,
	"Alabama_Tallapoosa" int,
	"Alabama_Tuscaloosa" int,
	"Alabama_Unassigned" int,
	"Alabama_Walker" int,
	"Alabama_Washington" int,
	"Alabama_Wilcox" int,
	"Alabama_Winston" int,
	"Alaska_Aleutians East" int,
	"Alaska_Aleutians West" int,
	"Alaska_Anchorage" int,
	"Alaska_Bethel" int,
	"Alaska_Bristol Bay" int,
	"Alaska_Bristol Bay plus Lake and Peninsula" int,
	"Alaska_Denali" int,
	"Alaska_Dillingham" int,
	"Alaska_Fairbanks North Star" int,
	"Alaska_Haines" int,
	"Alaska_Hoonah-Angoon" int,
	"Alaska_Juneau" int,
	"Alaska_Kenai Peninsula" int,
	"Alaska_Ketchikan Gateway" int,
	"Alaska_Kodiak Island" int,
	"Alaska_Kusilvak" int,
	"Alaska_Matanuska-Susitna" int,
	"Alaska_Nome" int,
	"Alaska_North Slope" int,
	"Alaska_Northwest Arctic" int,
	"Alaska_Out of AK" int,
	"Alaska_Petersburg" int,
	"Alaska_Prince of Wales-Hyder" int,
	"Alaska_Sitka" int,
	"Alaska_Skagway" int,
	"Alaska_Southeast Fairbanks" int,
	"Alaska_Unassigned" int,
	"Alaska_Valdez-Cordova" int,
	"Alaska_Wrangell" int,
	"Alaska_Yakutat" int,
	"Alaska_Yukon-Koyukuk" int,
	"American Samoa" int,
	"Arizona_Apache" int,
	"Arizona_Cochise" int,
	"Arizona_Coconino" int,
	"Arizona_Gila" int,
	"Arizona_Graham" int,
	"Arizona_Greenlee" int,
	"Arizona_La Paz" int,
	"Arizona_Maricopa" int,
	"Arizona_Mohave" int,
	"Arizona_Navajo" int,
	"Arizona_Out of AZ" int,
	"Arizona_Pima" int,
	"Arizona_Pinal" int,
	"Arizona_Santa Cruz" int,
	"Arizona_Unassigned" int,
	"Arizona_Yavapai" int,
	"Arizona_Yuma" int,
	"Arkansas_Arkansas" int,
	"Arkansas_Ashley" int,
	"Arkansas_Baxter" int,
	"Arkansas_Benton" int,
	"Arkansas_Boone" int,
	"Arkansas_Bradley" int,
	"Arkansas_Calhoun" int,
	"Arkansas_Carroll" int,
	"Arkansas_Chicot" int,
	"Arkansas_Clark" int,
	"Arkansas_Clay" int,
	"Arkansas_Cleburne" int,
	"Arkansas_Cleveland" int,
	"Arkansas_Columbia" int,
	"Arkansas_Conway" int,
	"Arkansas_Craighead" int,
	"Arkansas_Crawford" int,
	"Arkansas_Crittenden" int,
	"Arkansas_Cross" int,
	"Arkansas_Dallas" int,
	"Arkansas_Desha" int,
	"Arkansas_Drew" int,
	"Arkansas_Faulkner" int,
	"Arkansas_Franklin" int,
	"Arkansas_Fulton" int,
	"Arkansas_Garland" int,
	"Arkansas_Grant" int,
	"Arkansas_Greene" int,
	"Arkansas_Hempstead" int,
	"Arkansas_Hot Spring" int,
	"Arkansas_Howard" int,
	"Arkansas_Independence" int,
	"Arkansas_Izard" int,
	"Arkansas_Jackson" int,
	"Arkansas_Jefferson" int,
	"Arkansas_Johnson" int,
	"Arkansas_Lafayette" int,
	"Arkansas_Lawrence" int,
	"Arkansas_Lee" int,
	"Arkansas_Lincoln" int,
	"Arkansas_Little River" int,
	"Arkansas_Logan" int,
	"Arkansas_Lonoke" int,
	"Arkansas_Madison" int,
	"Arkansas_Marion" int,
	"Arkansas_Miller" int,
	"Arkansas_Mississippi" int,
	"Arkansas_Monroe" int,
	"Arkansas_Montgomery" int,
	"Arkansas_Nevada" int,
	"Arkansas_Newton" int,
	"Arkansas_Ouachita" int,
	"Arkansas_Out of AR" int,
	"Arkansas_Perry" int,
	"Arkansas_Phillips" int,
	"Arkansas_Pike" int,
	"Arkansas_Poinsett" int,
	"Arkansas_Polk" int,
	"Arkansas_Pope" int,
	"Arkansas_Prairie" int,
	"Arkansas_Pulaski" int,
	"Arkansas_Randolph" int,
	"Arkansas_Saline" int,
	"Arkansas_Scott" int,
	"Arkansas_Searcy" int,
	"Arkansas_Sebastian" int,
	"Arkansas_Sevier" int,
	"Arkansas_Sharp" int,
	"Arkansas_St. Francis" int,
	"Arkansas_Stone" int,
	"Arkansas_Unassigned" int,
	"Arkansas_Union" int,
	"Arkansas_Van Buren" int,
	"Arkansas_Washington" int,
	"Arkansas_White" int,
	"Arkansas_Woodruff" int,
	"Arkansas_Yell" int,
	"California_Alameda" int,
	"California_Alpine" int,
	"California_Amador" int,
	"California_Butte" int,
	"California_Calaveras" int,
	"California_Colusa" int,
	"California_Contra Costa" int,
	"California_Del Norte" int,
	"California_El Dorado" int,
	"California_Fresno" int,
	"California_Glenn" int,
	"California_Humboldt" int,
	"California_Imperial" int,
	"California_Inyo" int,
	"California_Kern" int,
	"California_Kings" int,
	"California_Lake" int,
	"California_Lassen" int,
	"California_Los Angeles" int,
	"California_Madera" int,
	"California_Marin" int,
	"California_Mariposa" int,
	"California_Mendocino" int,
	"California_Merced" int,
	"California_Modoc" int,
	"California_Mono" int,
	"California_Monterey" int,
	"California_Napa" int,
	"California_Nevada" int,
	"California_Orange" int,
	"California_Out of CA" int,
	"California_Placer" int,
	"California_Plumas" int,
	"California_Riverside" int,
	"California_Sacramento" int,
	"California_San Benito" int,
	"California_San Bernardino" int,
	"California_San Diego" int,
	"California_San Francisco" int,
	"California_San Joaquin" int,
	"California_San Luis Obispo" int,
	"California_San Mateo" int,
	"California_Santa Barbara" int,
	"California_Santa Clara" int,
	"California_Santa Cruz" int,
	"California_Shasta" int,
	"California_Sierra" int,
	"California_Siskiyou" int,
	"California_Solano" int,
	"California_Sonoma" int,
	"California_Stanislaus" int,
	"California_Sutter" int,
	"California_Tehama" int,
	"California_Trinity" int,
	"California_Tulare" int,
	"California_Tuolumne" int,
	"California_Unassigned" int,
	"California_Ventura" int,
	"California_Yolo" int,
	"California_Yuba" int,
	"Colorado_Adams" int,
	"Colorado_Alamosa" int,
	"Colorado_Arapahoe" int,
	"Colorado_Archuleta" int,
	"Colorado_Baca" int,
	"Colorado_Bent" int,
	"Colorado_Boulder" int,
	"Colorado_Broomfield" int,
	"Colorado_Chaffee" int,
	"Colorado_Cheyenne" int,
	"Colorado_Clear Creek" int,
	"Colorado_Conejos" int,
	"Colorado_Costilla" int,
	"Colorado_Crowley" int,
	"Colorado_Custer" int,
	"Colorado_Delta" int,
	"Colorado_Denver" int,
	"Colorado_Dolores" int,
	"Colorado_Douglas" int,
	"Colorado_Eagle" int,
	"Colorado_El Paso" int,
	"Colorado_Elbert" int,
	"Colorado_Fremont" int,
	"Colorado_Garfield" int,
	"Colorado_Gilpin" int,
	"Colorado_Grand" int,
	"Colorado_Gunnison" int,
	"Colorado_Hinsdale" int,
	"Colorado_Huerfano" int,
	"Colorado_Jackson" int,
	"Colorado_Jefferson" int,
	"Colorado_Kiowa" int,
	"Colorado_Kit Carson" int,
	"Colorado_La Plata" int,
	"Colorado_Lake" int,
	"Colorado_Larimer" int,
	"Colorado_Las Animas" int,
	"Colorado_Lincoln" int,
	"Colorado_Logan" int,
	"Colorado_Mesa" int,
	"Colorado_Mineral" int,
	"Colorado_Moffat" int,
	"Colorado_Montezuma" int,
	"Colorado_Montrose" int,
	"Colorado_Morgan" int,
	"Colorado_Otero" int,
	"Colorado_Ouray" int,
	"Colorado_Out of CO" int,
	"Colorado_Park" int,
	"Colorado_Phillips" int,
	"Colorado_Pitkin" int,
	"Colorado_Prowers" int,
	"Colorado_Pueblo" int,
	"Colorado_Rio Blanco" int,
	"Colorado_Rio Grande" int,
	"Colorado_Routt" int,
	"Colorado_Saguache" int,
	"Colorado_San Juan" int,
	"Colorado_San Miguel" int,
	"Colorado_Sedgwick" int,
	"Colorado_Summit" int,
	"Colorado_Teller" int,
	"Colorado_Unassigned" int,
	"Colorado_Washington" int,
	"Colorado_Weld" int,
	"Colorado_Yuma" int,
	"Connecticut_Fairfield" int,
	"Connecticut_Hartford" int,
	"Connecticut_Litchfield" int,
	"Connecticut_Middlesex" int,
	"Connecticut_New Haven" int,
	"Connecticut_New London" int,
	"Connecticut_Out of CT" int,
	"Connecticut_Tolland" int,
	"Connecticut_Unassigned" int,
	"Connecticut_Windham" int,
	"Delaware_Kent" int,
	"Delaware_New Castle" int,
	"Delaware_Out of DE" int,
	"Delaware_Sussex" int,
	"Delaware_Unassigned" int,
	"Diamond Princess" int,
	"District of Columbia_District of Columbia" int,
	"District of Columbia_Out of DC" int,
	"District of Columbia_Unassigned" int,
	"Florida_Alachua" int,
	"Florida_Baker" int,
	"Florida_Bay" int,
	"Florida_Bradford" int,
	"Florida_Brevard" int,
	"Florida_Broward" int,
	"Florida_Calhoun" int,
	"Florida_Charlotte" int,
	"Florida_Citrus" int,
	"Florida_Clay" int,
	"Florida_Collier" int,
	"Florida_Columbia" int,
	"Florida_DeSoto" int,
	"Florida_Dixie" int,
	"Florida_Duval" int,
	"Florida_Escambia" int,
	"Florida_Flagler" int,
	"Florida_Franklin" int,
	"Florida_Gadsden" int,
	"Florida_Gilchrist" int,
	"Florida_Glades" int,
	"Florida_Gulf" int,
	"Florida_Hamilton" int,
	"Florida_Hardee" int,
	"Florida_Hendry" int,
	"Florida_Hernando" int,
	"Florida_Highlands" int,
	"Florida_Hillsborough" int,
	"Florida_Holmes" int,
	"Florida_Indian River" int,
	"Florida_Jackson" int,
	"Florida_Jefferson" int,
	"Florida_Lafayette" int,
	"Florida_Lake" int,
	"Florida_Lee" int,
	"Florida_Leon" int,
	"Florida_Levy" int,
	"Florida_Liberty" int,
	"Florida_Madison" int,
	"Florida_Manatee" int,
	"Florida_Marion" int,
	"Florida_Martin" int,
	"Florida_Miami-Dade" int,
	"Florida_Monroe" int,
	"Florida_Nassau" int,
	"Florida_Okaloosa" int,
	"Florida_Okeechobee" int,
	"Florida_Orange" int,
	"Florida_Osceola" int,
	"Florida_Out of FL" int,
	"Florida_Palm Beach" int,
	"Florida_Pasco" int,
	"Florida_Pinellas" int,
	"Florida_Polk" int,
	"Florida_Putnam" int,
	"Florida_Santa Rosa" int,
	"Florida_Sarasota" int,
	"Florida_Seminole" int,
	"Florida_St. Johns" int,
	"Florida_St. Lucie" int,
	"Florida_Sumter" int,
	"Florida_Suwannee" int,
	"Florida_Taylor" int,
	"Florida_Unassigned" int,
	"Florida_Union" int,
	"Florida_Volusia" int,
	"Florida_Wakulla" int,
	"Florida_Walton" int,
	"Florida_Washington" int,
	"Georgia_Appling" int,
	"Georgia_Atkinson" int,
	"Georgia_Bacon" int,
	"Georgia_Baker" int,
	"Georgia_Baldwin" int,
	"Georgia_Banks" int,
	"Georgia_Barrow" int,
	"Georgia_Bartow" int,
	"Georgia_Ben Hill" int,
	"Georgia_Berrien" int,
	"Georgia_Bibb" int,
	"Georgia_Bleckley" int,
	"Georgia_Brantley" int,
	"Georgia_Brooks" int,
	"Georgia_Bryan" int,
	"Georgia_Bulloch" int,
	"Georgia_Burke" int,
	"Georgia_Butts" int,
	"Georgia_Calhoun" int,
	"Georgia_Camden" int,
	"Georgia_Candler" int,
	"Georgia_Carroll" int,
	"Georgia_Catoosa" int,
	"Georgia_Charlton" int,
	"Georgia_Chatham" int,
	"Georgia_Chattahoochee" int,
	"Georgia_Chattooga" int,
	"Georgia_Cherokee" int,
	"Georgia_Clarke" int,
	"Georgia_Clay" int,
	"Georgia_Clayton" int,
	"Georgia_Clinch" int,
	"Georgia_Cobb" int,
	"Georgia_Coffee" int,
	"Georgia_Colquitt" int,
	"Georgia_Columbia" int,
	"Georgia_Cook" int,
	"Georgia_Coweta" int,
	"Georgia_Crawford" int,
	"Georgia_Crisp" int,
	"Georgia_Dade" int,
	"Georgia_Dawson" int,
	"Georgia_DeKalb" int,
	"Georgia_Decatur" int,
	"Georgia_Dodge" int,
	"Georgia_Dooly" int,
	"Georgia_Dougherty" int,
	"Georgia_Douglas" int,
	"Georgia_Early" int,
	"Georgia_Echols" int,
	"Georgia_Effingham" int,
	"Georgia_Elbert" int,
	"Georgia_Emanuel" int,
	"Georgia_Evans" int,
	"Georgia_Fannin" int,
	"Georgia_Fayette" int,
	"Georgia_Floyd" int,
	"Georgia_Forsyth" int,
	"Georgia_Franklin" int,
	"Georgia_Fulton" int,
	"Georgia_Gilmer" int,
	"Georgia_Glascock" int,
	"Georgia_Glynn" int,
	"Georgia_Gordon" int,
	"Georgia_Grady" int,
	"Georgia_Greene" int,
	"Georgia_Gwinnett" int,
	"Georgia_Habersham" int,
	"Georgia_Hall" int,
	"Georgia_Hancock" int,
	"Georgia_Haralson" int,
	"Georgia_Harris" int,
	"Georgia_Hart" int,
	"Georgia_Heard" int,
	"Georgia_Henry" int,
	"Georgia_Houston" int,
	"Georgia_Irwin" int,
	"Georgia_Jackson" int,
	"Georgia_Jasper" int,
	"Georgia_Jeff Davis" int,
	"Georgia_Jefferson" int,
	"Georgia_Jenkins" int,
	"Georgia_Johnson" int,
	"Georgia_Jones" int,
	"Georgia_Lamar" int,
	"Georgia_Lanier" int,
	"Georgia_Laurens" int,
	"Georgia_Lee" int,
	"Georgia_Liberty" int,
	"Georgia_Lincoln" int,
	"Georgia_Long" int,
	"Georgia_Lowndes" int,
	"Georgia_Lumpkin" int,
	"Georgia_Macon" int,
	"Georgia_Madison" int,
	"Georgia_Marion" int,
	"Georgia_McDuffie" int,
	"Georgia_McIntosh" int,
	"Georgia_Meriwether" int,
	"Georgia_Miller" int,
	"Georgia_Mitchell" int,
	"Georgia_Monroe" int,
	"Georgia_Montgomery" int,
	"Georgia_Morgan" int,
	"Georgia_Murray" int,
	"Georgia_Muscogee" int,
	"Georgia_Newton" int,
	"Georgia_Oconee" int,
	"Georgia_Oglethorpe" int,
	"Georgia_Out of GA" int,
	"Georgia_Paulding" int,
	"Georgia_Peach" int,
	"Georgia_Pickens" int,
	"Georgia_Pierce" int,
	"Georgia_Pike" int,
	"Georgia_Polk" int,
	"Georgia_Pulaski" int,
	"Georgia_Putnam" int,
	"Georgia_Quitman" int,
	"Georgia_Rabun" int,
	"Georgia_Randolph" int,
	"Georgia_Richmond" int,
	"Georgia_Rockdale" int,
	"Georgia_Schley" int,
	"Georgia_Screven" int,
	"Georgia_Seminole" int,
	"Georgia_Spalding" int,
	"Georgia_Stephens" int,
	"Georgia_Stewart" int,
	"Georgia_Sumter" int,
	"Georgia_Talbot" int,
	"Georgia_Taliaferro" int,
	"Georgia_Tattnall" int,
	"Georgia_Taylor" int,
	"Georgia_Telfair" int,
	"Georgia_Terrell" int,
	"Georgia_Thomas" int,
	"Georgia_Tift" int,
	"Georgia_Toombs" int,
	"Georgia_Towns" int,
	"Georgia_Treutlen" int,
	"Georgia_Troup" int,
	"Georgia_Turner" int,
	"Georgia_Twiggs" int,
	"Georgia_Unassigned" int,
	"Georgia_Union" int,
	"Georgia_Upson" int,
	"Georgia_Walker" int,
	"Georgia_Walton" int,
	"Georgia_Ware" int,
	"Georgia_Warren" int,
	"Georgia_Washington" int,
	"Georgia_Wayne" int,
	"Georgia_Webster" int,
	"Georgia_Wheeler" int,
	"Georgia_White" int,
	"Georgia_Whitfield" int,
	"Georgia_Wilcox" int,
	"Georgia_Wilkes" int,
	"Georgia_Wilkinson" int,
	"Georgia_Worth" int,
	"Grand Princess" int,
	"Guam" int,
	"Hawaii_Hawaii" int,
	"Hawaii_Honolulu" int,
	"Hawaii_Kalawao" int,
	"Hawaii_Kauai" int,
	"Hawaii_Maui" int,
	"Hawaii_Out of HI" int,
	"Hawaii_Unassigned" int,
	"Idaho_Ada" int,
	"Idaho_Adams" int,
	"Idaho_Bannock" int,
	"Idaho_Bear Lake" int,
	"Idaho_Benewah" int,
	"Idaho_Bingham" int,
	"Idaho_Blaine" int,
	"Idaho_Boise" int,
	"Idaho_Bonner" int,
	"Idaho_Bonneville" int,
	"Idaho_Boundary" int,
	"Idaho_Butte" int,
	"Idaho_Camas" int,
	"Idaho_Canyon" int,
	"Idaho_Caribou" int,
	"Idaho_Cassia" int,
	"Idaho_Clark" int,
	"Idaho_Clearwater" int,
	"Idaho_Custer" int,
	"Idaho_Elmore" int,
	"Idaho_Franklin" int,
	"Idaho_Fremont" int,
	"Idaho_Gem" int,
	"Idaho_Gooding" int,
	"Idaho_Idaho" int,
	"Idaho_Jefferson" int,
	"Idaho_Jerome" int,
	"Idaho_Kootenai" int,
	"Idaho_Latah" int,
	"Idaho_Lemhi" int,
	"Idaho_Lewis" int,
	"Idaho_Lincoln" int,
	"Idaho_Madison" int,
	"Idaho_Minidoka" int,
	"Idaho_Nez Perce" int,
	"Idaho_Oneida" int,
	"Idaho_Out of ID" int,
	"Idaho_Owyhee" int,
	"Idaho_Payette" int,
	"Idaho_Power" int,
	"Idaho_Shoshone" int,
	"Idaho_Teton" int,
	"Idaho_Twin Falls" int,
	"Idaho_Unassigned" int,
	"Idaho_Valley" int,
	"Idaho_Washington" int,
	"Illinois_Adams" int,
	"Illinois_Alexander" int,
	"Illinois_Bond" int,
	"Illinois_Boone" int,
	"Illinois_Brown" int,
	"Illinois_Bureau" int,
	"Illinois_Calhoun" int,
	"Illinois_Carroll" int,
	"Illinois_Cass" int,
	"Illinois_Champaign" int,
	"Illinois_Christian" int,
	"Illinois_Clark" int,
	"Illinois_Clay" int,
	"Illinois_Clinton" int,
	"Illinois_Coles" int,
	"Illinois_Cook" int,
	"Illinois_Crawford" int,
	"Illinois_Cumberland" int,
	"Illinois_De Witt" int,
	"Illinois_DeKalb" int,
	"Illinois_Douglas" int,
	"Illinois_DuPage" int,
	"Illinois_Edgar" int,
	"Illinois_Edwards" int,
	"Illinois_Effingham" int,
	"Illinois_Fayette" int,
	"Illinois_Ford" int,
	"Illinois_Franklin" int,
	"Illinois_Fulton" int,
	"Illinois_Gallatin" int,
	"Illinois_Greene" int,
	"Illinois_Grundy" int,
	"Illinois_Hamilton" int,
	"Illinois_Hancock" int,
	"Illinois_Hardin" int,
	"Illinois_Henderson" int,
	"Illinois_Henry" int,
	"Illinois_Iroquois" int,
	"Illinois_Jackson" int,
	"Illinois_Jasper" int,
	"Illinois_Jefferson" int,
	"Illinois_Jersey" int,
	"Illinois_Jo Daviess" int,
	"Illinois_Johnson" int,
	"Illinois_Kane" int,
	"Illinois_Kankakee" int,
	"Illinois_Kendall" int,
	"Illinois_Knox" int,
	"Illinois_LaSalle" int,
	"Illinois_Lake" int,
	"Illinois_Lawrence" int,
	"Illinois_Lee" int,
	"Illinois_Livingston" int,
	"Illinois_Logan" int,
	"Illinois_Macon" int,
	"Illinois_Macoupin" int,
	"Illinois_Madison" int,
	"Illinois_Marion" int,
	"Illinois_Marshall" int,
	"Illinois_Mason" int,
	"Illinois_Massac" int,
	"Illinois_McDonough" int,
	"Illinois_McHenry" int,
	"Illinois_McLean" int,
	"Illinois_Menard" int,
	"Illinois_Mercer" int,
	"Illinois_Monroe" int,
	"Illinois_Montgomery" int,
	"Illinois_Morgan" int,
	"Illinois_Moultrie" int,
	"Illinois_Ogle" int,
	"Illinois_Out of IL" int,
	"Illinois_Peoria" int,
	"Illinois_Perry" int,
	"Illinois_Piatt" int,
	"Illinois_Pike" int,
	"Illinois_Pope" int,
	"Illinois_Pulaski" int,
	"Illinois_Putnam" int,
	"Illinois_Randolph" int,
	"Illinois_Richland" int,
	"Illinois_Rock Island" int,
	"Illinois_Saline" int,
	"Illinois_Sangamon" int,
	"Illinois_Schuyler" int,
	"Illinois_Scott" int,
	"Illinois_Shelby" int,
	"Illinois_St. Clair" int,
	"Illinois_Stark" int,
	"Illinois_Stephenson" int,
	"Illinois_Tazewell" int,
	"Illinois_Unassigned" int,
	"Illinois_Union" int,
	"Illinois_Vermilion" int,
	"Illinois_Wabash" int,
	"Illinois_Warren" int,
	"Illinois_Washington" int,
	"Illinois_Wayne" int,
	"Illinois_White" int,
	"Illinois_Whiteside" int,
	"Illinois_Will" int,
	"Illinois_Williamson" int,
	"Illinois_Winnebago" int,
	"Illinois_Woodford" int,
	"Indiana_Adams" int,
	"Indiana_Allen" int,
	"Indiana_Bartholomew" int,
	"Indiana_Benton" int,
	"Indiana_Blackford" int,
	"Indiana_Boone" int,
	"Indiana_Brown" int,
	"Indiana_Carroll" int,
	"Indiana_Cass" int,
	"Indiana_Clark" int,
	"Indiana_Clay" int,
	"Indiana_Clinton" int,
	"Indiana_Crawford" int,
	"Indiana_Daviess" int,
	"Indiana_DeKalb" int,
	"Indiana_Dearborn" int,
	"Indiana_Decatur" int,
	"Indiana_Delaware" int,
	"Indiana_Dubois" int,
	"Indiana_Elkhart" int,
	"Indiana_Fayette" int,
	"Indiana_Floyd" int,
	"Indiana_Fountain" int,
	"Indiana_Franklin" int,
	"Indiana_Fulton" int,
	"Indiana_Gibson" int,
	"Indiana_Grant" int,
	"Indiana_Greene" int,
	"Indiana_Hamilton" int,
	"Indiana_Hancock" int,
	"Indiana_Harrison" int,
	"Indiana_Hendricks" int,
	"Indiana_Henry" int,
	"Indiana_Howard" int,
	"Indiana_Huntington" int,
	"Indiana_Jackson" int,
	"Indiana_Jasper" int,
	"Indiana_Jay" int,
	"Indiana_Jefferson" int,
	"Indiana_Jennings" int,
	"Indiana_Johnson" int,
	"Indiana_Knox" int,
	"Indiana_Kosciusko" int,
	"Indiana_LaGrange" int,
	"Indiana_LaPorte" int,
	"Indiana_Lake" int,
	"Indiana_Lawrence" int,
	"Indiana_Madison" int,
	"Indiana_Marion" int,
	"Indiana_Marshall" int,
	"Indiana_Martin" int,
	"Indiana_Miami" int,
	"Indiana_Monroe" int,
	"Indiana_Montgomery" int,
	"Indiana_Morgan" int,
	"Indiana_Newton" int,
	"Indiana_Noble" int,
	"Indiana_Ohio" int,
	"Indiana_Orange" int,
	"Indiana_Out of IN" int,
	"Indiana_Owen" int,
	"Indiana_Parke" int,
	"Indiana_Perry" int,
	"Indiana_Pike" int,
	"Indiana_Porter" int,
	"Indiana_Posey" int,
	"Indiana_Pulaski" int,
	"Indiana_Putnam" int,
	"Indiana_Randolph" int,
	"Indiana_Ripley" int,
	"Indiana_Rush" int,
	"Indiana_Scott" int,
	"Indiana_Shelby" int,
	"Indiana_Spencer" int,
	"Indiana_St. Joseph" int,
	"Indiana_Starke" int,
	"Indiana_Steuben" int,
	"Indiana_Sullivan" int,
	"Indiana_Switzerland" int,
	"Indiana_Tippecanoe" int,
	"Indiana_Tipton" int,
	"Indiana_Unassigned" int,
	"Indiana_Union" int,
	"Indiana_Vanderburgh" int,
	"Indiana_Vermillion" int,
	"Indiana_Vigo" int,
	"Indiana_Wabash" int,
	"Indiana_Warren" int,
	"Indiana_Warrick" int,
	"Indiana_Washington" int,
	"Indiana_Wayne" int,
	"Indiana_Wells" int,
	"Indiana_White" int,
	"Indiana_Whitley" int,
	"Iowa_Adair" int,
	"Iowa_Adams" int,
	"Iowa_Allamakee" int,
	"Iowa_Appanoose" int,
	"Iowa_Audubon" int,
	"Iowa_Benton" int,
	"Iowa_Black Hawk" int,
	"Iowa_Boone" int,
	"Iowa_Bremer" int,
	"Iowa_Buchanan" int,
	"Iowa_Buena Vista" int,
	"Iowa_Butler" int,
	"Iowa_Calhoun" int,
	"Iowa_Carroll" int,
	"Iowa_Cass" int,
	"Iowa_Cedar" int,
	"Iowa_Cerro Gordo" int,
	"Iowa_Cherokee" int,
	"Iowa_Chickasaw" int,
	"Iowa_Clarke" int,
	"Iowa_Clay" int,
	"Iowa_Clayton" int,
	"Iowa_Clinton" int,
	"Iowa_Crawford" int,
	"Iowa_Dallas" int,
	"Iowa_Davis" int,
	"Iowa_Decatur" int,
	"Iowa_Delaware" int,
	"Iowa_Des Moines" int,
	"Iowa_Dickinson" int,
	"Iowa_Dubuque" int,
	"Iowa_Emmet" int,
	"Iowa_Fayette" int,
	"Iowa_Floyd" int,
	"Iowa_Franklin" int,
	"Iowa_Fremont" int,
	"Iowa_Greene" int,
	"Iowa_Grundy" int,
	"Iowa_Guthrie" int,
	"Iowa_Hamilton" int,
	"Iowa_Hancock" int,
	"Iowa_Hardin" int,
	"Iowa_Harrison" int,
	"Iowa_Henry" int,
	"Iowa_Howard" int,
	"Iowa_Humboldt" int,
	"Iowa_Ida" int,
	"Iowa_Iowa" int,
	"Iowa_Jackson" int,
	"Iowa_Jasper" int,
	"Iowa_Jefferson" int,
	"Iowa_Johnson" int,
	"Iowa_Jones" int,
	"Iowa_Keokuk" int,
	"Iowa_Kossuth" int,
	"Iowa_Lee" int,
	"Iowa_Linn" int,
	"Iowa_Louisa" int,
	"Iowa_Lucas" int,
	"Iowa_Lyon" int,
	"Iowa_Madison" int,
	"Iowa_Mahaska" int,
	"Iowa_Marion" int,
	"Iowa_Marshall" int,
	"Iowa_Mills" int,
	"Iowa_Mitchell" int,
	"Iowa_Monona" int,
	"Iowa_Monroe" int,
	"Iowa_Montgomery" int,
	"Iowa_Muscatine" int,
	"Iowa_O'Brien" int,
	"Iowa_Osceola" int,
	"Iowa_Out of IA" int,
	"Iowa_Page" int,
	"Iowa_Palo Alto" int,
	"Iowa_Plymouth" int,
	"Iowa_Pocahontas" int,
	"Iowa_Polk" int,
	"Iowa_Pottawattamie" int,
	"Iowa_Poweshiek" int,
	"Iowa_Ringgold" int,
	"Iowa_Sac" int,
	"Iowa_Scott" int,
	"Iowa_Shelby" int,
	"Iowa_Sioux" int,
	"Iowa_Story" int,
	"Iowa_Tama" int,
	"Iowa_Taylor" int,
	"Iowa_Unassigned" int,
	"Iowa_Union" int,
	"Iowa_Van Buren" int,
	"Iowa_Wapello" int,
	"Iowa_Warren" int,
	"Iowa_Washington" int,
	"Iowa_Wayne" int,
	"Iowa_Webster" int,
	"Iowa_Winnebago" int,
	"Iowa_Winneshiek" int,
	"Iowa_Woodbury" int,
	"Iowa_Worth" int,
	"Iowa_Wright" int,
	"Kansas_Allen" int,
	"Kansas_Anderson" int,
	"Kansas_Atchison" int,
	"Kansas_Barber" int,
	"Kansas_Barton" int,
	"Kansas_Bourbon" int,
	"Kansas_Brown" int,
	"Kansas_Butler" int,
	"Kansas_Chase" int,
	"Kansas_Chautauqua" int,
	"Kansas_Cherokee" int,
	"Kansas_Cheyenne" int,
	"Kansas_Clark" int,
	"Kansas_Clay" int,
	"Kansas_Cloud" int,
	"Kansas_Coffey" int,
	"Kansas_Comanche" int,
	"Kansas_Cowley" int,
	"Kansas_Crawford" int,
	"Kansas_Decatur" int,
	"Kansas_Dickinson" int,
	"Kansas_Doniphan" int,
	"Kansas_Douglas" int,
	"Kansas_Edwards" int,
	"Kansas_Elk" int,
	"Kansas_Ellis" int,
	"Kansas_Ellsworth" int,
	"Kansas_Finney" int,
	"Kansas_Ford" int,
	"Kansas_Franklin" int,
	"Kansas_Geary" int,
	"Kansas_Gove" int,
	"Kansas_Graham" int,
	"Kansas_Grant" int,
	"Kansas_Gray" int,
	"Kansas_Greeley" int,
	"Kansas_Greenwood" int,
	"Kansas_Hamilton" int,
	"Kansas_Harper" int,
	"Kansas_Harvey" int,
	"Kansas_Haskell" int,
	"Kansas_Hodgeman" int,
	"Kansas_Jackson" int,
	"Kansas_Jefferson" int,
	"Kansas_Jewell" int,
	"Kansas_Johnson" int,
	"Kansas_Kearny" int,
	"Kansas_Kingman" int,
	"Kansas_Kiowa" int,
	"Kansas_Labette" int,
	"Kansas_Lane" int,
	"Kansas_Leavenworth" int,
	"Kansas_Lincoln" int,
	"Kansas_Linn" int,
	"Kansas_Logan" int,
	"Kansas_Lyon" int,
	"Kansas_Marion" int,
	"Kansas_Marshall" int,
	"Kansas_McPherson" int,
	"Kansas_Meade" int,
	"Kansas_Miami" int,
	"Kansas_Mitchell" int,
	"Kansas_Montgomery" int,
	"Kansas_Morris" int,
	"Kansas_Morton" int,
	"Kansas_Nemaha" int,
	"Kansas_Neosho" int,
	"Kansas_Ness" int,
	"Kansas_Norton" int,
	"Kansas_Osage" int,
	"Kansas_Osborne" int,
	"Kansas_Ottawa" int,
	"Kansas_Out of KS" int,
	"Kansas_Pawnee" int,
	"Kansas_Phillips" int,
	"Kansas_Pottawatomie" int,
	"Kansas_Pratt" int,
	"Kansas_Rawlins" int,
	"Kansas_Reno" int,
	"Kansas_Republic" int,
	"Kansas_Rice" int,
	"Kansas_Riley" int,
	"Kansas_Rooks" int,
	"Kansas_Rush" int,
	"Kansas_Russell" int,
	"Kansas_Saline" int,
	"Kansas_Scott" int,
	"Kansas_Sedgwick" int,
	"Kansas_Seward" int,
	"Kansas_Shawnee" int,
	"Kansas_Sheridan" int,
	"Kansas_Sherman" int,
	"Kansas_Smith" int,
	"Kansas_Stafford" int,
	"Kansas_Stanton" int,
	"Kansas_Stevens" int,
	"Kansas_Sumner" int,
	"Kansas_Thomas" int,
	"Kansas_Trego" int,
	"Kansas_Unassigned" int,
	"Kansas_Wabaunsee" int,
	"Kansas_Wallace" int,
	"Kansas_Washington" int,
	"Kansas_Wichita" int,
	"Kansas_Wilson" int,
	"Kansas_Woodson" int,
	"Kansas_Wyandotte" int,
	"Kentucky_Adair" int,
	"Kentucky_Allen" int,
	"Kentucky_Anderson" int,
	"Kentucky_Ballard" int,
	"Kentucky_Barren" int,
	"Kentucky_Bath" int,
	"Kentucky_Bell" int,
	"Kentucky_Boone" int,
	"Kentucky_Bourbon" int,
	"Kentucky_Boyd" int,
	"Kentucky_Boyle" int,
	"Kentucky_Bracken" int,
	"Kentucky_Breathitt" int,
	"Kentucky_Breckinridge" int,
	"Kentucky_Bullitt" int,
	"Kentucky_Butler" int,
	"Kentucky_Caldwell" int,
	"Kentucky_Calloway" int,
	"Kentucky_Campbell" int,
	"Kentucky_Carlisle" int,
	"Kentucky_Carroll" int,
	"Kentucky_Carter" int,
	"Kentucky_Casey" int,
	"Kentucky_Christian" int,
	"Kentucky_Clark" int,
	"Kentucky_Clay" int,
	"Kentucky_Clinton" int,
	"Kentucky_Crittenden" int,
	"Kentucky_Cumberland" int,
	"Kentucky_Daviess" int,
	"Kentucky_Edmonson" int,
	"Kentucky_Elliott" int,
	"Kentucky_Estill" int,
	"Kentucky_Fayette" int,
	"Kentucky_Fleming" int,
	"Kentucky_Floyd" int,
	"Kentucky_Franklin" int,
	"Kentucky_Fulton" int,
	"Kentucky_Gallatin" int,
	"Kentucky_Garrard" int,
	"Kentucky_Grant" int,
	"Kentucky_Graves" int,
	"Kentucky_Grayson" int,
	"Kentucky_Green" int,
	"Kentucky_Greenup" int,
	"Kentucky_Hancock" int,
	"Kentucky_Hardin" int,
	"Kentucky_Harlan" int,
	"Kentucky_Harrison" int,
	"Kentucky_Hart" int,
	"Kentucky_Henderson" int,
	"Kentucky_Henry" int,
	"Kentucky_Hickman" int,
	"Kentucky_Hopkins" int,
	"Kentucky_Jackson" int,
	"Kentucky_Jefferson" int,
	"Kentucky_Jessamine" int,
	"Kentucky_Johnson" int,
	"Kentucky_Kenton" int,
	"Kentucky_Knott" int,
	"Kentucky_Knox" int,
	"Kentucky_Larue" int,
	"Kentucky_Laurel" int,
	"Kentucky_Lawrence" int,
	"Kentucky_Lee" int,
	"Kentucky_Leslie" int,
	"Kentucky_Letcher" int,
	"Kentucky_Lewis" int,
	"Kentucky_Lincoln" int,
	"Kentucky_Livingston" int,
	"Kentucky_Logan" int,
	"Kentucky_Lyon" int,
	"Kentucky_Madison" int,
	"Kentucky_Magoffin" int,
	"Kentucky_Marion" int,
	"Kentucky_Marshall" int,
	"Kentucky_Martin" int,
	"Kentucky_Mason" int,
	"Kentucky_McCracken" int,
	"Kentucky_McCreary" int,
	"Kentucky_McLean" int,
	"Kentucky_Meade" int,
	"Kentucky_Menifee" int,
	"Kentucky_Mercer" int,
	"Kentucky_Metcalfe" int,
	"Kentucky_Monroe" int,
	"Kentucky_Montgomery" int,
	"Kentucky_Morgan" int,
	"Kentucky_Muhlenberg" int,
	"Kentucky_Nelson" int,
	"Kentucky_Nicholas" int,
	"Kentucky_Ohio" int,
	"Kentucky_Oldham" int,
	"Kentucky_Out of KY" int,
	"Kentucky_Owen" int,
	"Kentucky_Owsley" int,
	"Kentucky_Pendleton" int,
	"Kentucky_Perry" int,
	"Kentucky_Pike" int,
	"Kentucky_Powell" int,
	"Kentucky_Pulaski" int,
	"Kentucky_Robertson" int,
	"Kentucky_Rockcastle" int,
	"Kentucky_Rowan" int,
	"Kentucky_Russell" int,
	"Kentucky_Scott" int,
	"Kentucky_Shelby" int,
	"Kentucky_Simpson" int,
	"Kentucky_Spencer" int,
	"Kentucky_Taylor" int,
	"Kentucky_Todd" int,
	"Kentucky_Trigg" int,
	"Kentucky_Trimble" int,
	"Kentucky_Unassigned" int,
	"Kentucky_Union" int,
	"Kentucky_Warren" int,
	"Kentucky_Washington" int,
	"Kentucky_Wayne" int,
	"Kentucky_Webster" int,
	"Kentucky_Whitley" int,
	"Kentucky_Wolfe" int,
	"Kentucky_Woodford" int,
	"Louisiana_Acadia" int,
	"Louisiana_Allen" int,
	"Louisiana_Ascension" int,
	"Louisiana_Assumption" int,
	"Louisiana_Avoyelles" int,
	"Louisiana_Beauregard" int,
	"Louisiana_Bienville" int,
	"Louisiana_Bossier" int,
	"Louisiana_Caddo" int,
	"Louisiana_Calcasieu" int,
	"Louisiana_Caldwell" int,
	"Louisiana_Cameron" int,
	"Louisiana_Catahoula" int,
	"Louisiana_Claiborne" int,
	"Louisiana_Concordia" int,
	"Louisiana_De Soto" int,
	"Louisiana_East Baton Rouge" int,
	"Louisiana_East Carroll" int,
	"Louisiana_East Feliciana" int,
	"Louisiana_Evangeline" int,
	"Louisiana_Franklin" int,
	"Louisiana_Grant" int,
	"Louisiana_Iberia" int,
	"Louisiana_Iberville" int,
	"Louisiana_Jackson" int,
	"Louisiana_Jefferson" int,
	"Louisiana_Jefferson Davis" int,
	"Louisiana_LaSalle" int,
	"Louisiana_Lafayette" int,
	"Louisiana_Lafourche" int,
	"Louisiana_Lincoln" int,
	"Louisiana_Livingston" int,
	"Louisiana_Madison" int,
	"Louisiana_Morehouse" int,
	"Louisiana_Natchitoches" int,
	"Louisiana_Orleans" int,
	"Louisiana_Ouachita" int,
	"Louisiana_Out of LA" int,
	"Louisiana_Plaquemines" int,
	"Louisiana_Pointe Coupee" int,
	"Louisiana_Rapides" int,
	"Louisiana_Red River" int,
	"Louisiana_Richland" int,
	"Louisiana_Sabine" int,
	"Louisiana_St. Bernard" int,
	"Louisiana_St. Charles" int,
	"Louisiana_St. Helena" int,
	"Louisiana_St. James" int,
	"Louisiana_St. John the Baptist" int,
	"Louisiana_St. Landry" int,
	"Louisiana_St. Martin" int,
	"Louisiana_St. Mary" int,
	"Louisiana_St. Tammany" int,
	"Louisiana_Tangipahoa" int,
	"Louisiana_Tensas" int,
	"Louisiana_Terrebonne" int,
	"Louisiana_Unassigned" int,
	"Louisiana_Union" int,
	"Louisiana_Vermilion" int,
	"Louisiana_Vernon" int,
	"Louisiana_Washington" int,
	"Louisiana_Webster" int,
	"Louisiana_West Baton Rouge" int,
	"Louisiana_West Carroll" int,
	"Louisiana_West Feliciana" int,
	"Louisiana_Winn" int,
	"Maine_Androscoggin" int,
	"Maine_Aroostook" int,
	"Maine_Cumberland" int,
	"Maine_Franklin" int,
	"Maine_Hancock" int,
	"Maine_Kennebec" int,
	"Maine_Knox" int,
	"Maine_Lincoln" int,
	"Maine_Out of ME" int,
	"Maine_Oxford" int,
	"Maine_Penobscot" int,
	"Maine_Piscataquis" int,
	"Maine_Sagadahoc" int,
	"Maine_Somerset" int,
	"Maine_Unassigned" int,
	"Maine_Waldo" int,
	"Maine_Washington" int,
	"Maine_York" int,
	"Maryland_Allegany" int,
	"Maryland_Anne Arundel" int,
	"Maryland_Baltimore" int,
	"Maryland_Baltimore City" int,
	"Maryland_Calvert" int,
	"Maryland_Caroline" int,
	"Maryland_Carroll" int,
	"Maryland_Cecil" int,
	"Maryland_Charles" int,
	"Maryland_Dorchester" int,
	"Maryland_Frederick" int,
	"Maryland_Garrett" int,
	"Maryland_Harford" int,
	"Maryland_Howard" int,
	"Maryland_Kent" int,
	"Maryland_Montgomery" int,
	"Maryland_Out of MD" int,
	"Maryland_Prince George's" int,
	"Maryland_Queen Anne's" int,
	"Maryland_Somerset" int,
	"Maryland_St. Mary's" int,
	"Maryland_Talbot" int,
	"Maryland_Unassigned" int,
	"Maryland_Washington" int,
	"Maryland_Wicomico" int,
	"Maryland_Worcester" int,
	"Massachusetts_Barnstable" int,
	"Massachusetts_Berkshire" int,
	"Massachusetts_Bristol" int,
	"Massachusetts_Dukes" int,
	"Massachusetts_Dukes and Nantucket" int,
	"Massachusetts_Essex" int,
	"Massachusetts_Franklin" int,
	"Massachusetts_Hampden" int,
	"Massachusetts_Hampshire" int,
	"Massachusetts_Middlesex" int,
	"Massachusetts_Nantucket" int,
	"Massachusetts_Norfolk" int,
	"Massachusetts_Out of MA" int,
	"Massachusetts_Plymouth" int,
	"Massachusetts_Suffolk" int,
	"Massachusetts_Unassigned" int,
	"Massachusetts_Worcester" int,
	"Michigan_Alcona" int,
	"Michigan_Alger" int,
	"Michigan_Allegan" int,
	"Michigan_Alpena" int,
	"Michigan_Antrim" int,
	"Michigan_Arenac" int,
	"Michigan_Baraga" int,
	"Michigan_Barry" int,
	"Michigan_Bay" int,
	"Michigan_Benzie" int,
	"Michigan_Berrien" int,
	"Michigan_Branch" int,
	"Michigan_Calhoun" int,
	"Michigan_Cass" int,
	"Michigan_Charlevoix" int,
	"Michigan_Cheboygan" int,
	"Michigan_Chippewa" int,
	"Michigan_Clare" int,
	"Michigan_Clinton" int,
	"Michigan_Crawford" int,
	"Michigan_Delta" int,
	"Michigan_Dickinson" int,
	"Michigan_Eaton" int,
	"Michigan_Emmet" int,
	"Michigan_Federal Correctional Institution (FCI)" int,
	"Michigan_Genesee" int,
	"Michigan_Gladwin" int,
	"Michigan_Gogebic" int,
	"Michigan_Grand Traverse" int,
	"Michigan_Gratiot" int,
	"Michigan_Hillsdale" int,
	"Michigan_Houghton" int,
	"Michigan_Huron" int,
	"Michigan_Ingham" int,
	"Michigan_Ionia" int,
	"Michigan_Iosco" int,
	"Michigan_Iron" int,
	"Michigan_Isabella" int,
	"Michigan_Jackson" int,
	"Michigan_Kalamazoo" int,
	"Michigan_Kalkaska" int,
	"Michigan_Kent" int,
	"Michigan_Keweenaw" int,
	"Michigan_Lake" int,
	"Michigan_Lapeer" int,
	"Michigan_Leelanau" int,
	"Michigan_Lenawee" int,
	"Michigan_Livingston" int,
	"Michigan_Luce" int,
	"Michigan_Mackinac" int,
	"Michigan_Macomb" int,
	"Michigan_Manistee" int,
	"Michigan_Marquette" int,
	"Michigan_Mason" int,
	"Michigan_Mecosta" int,
	"Michigan_Menominee" int,
	"Michigan_Michigan Department of Corrections (MDOC)" int,
	"Michigan_Midland" int,
	"Michigan_Missaukee" int,
	"Michigan_Monroe" int,
	"Michigan_Montcalm" int,
	"Michigan_Montmorency" int,
	"Michigan_Muskegon" int,
	"Michigan_Newaygo" int,
	"Michigan_Oakland" int,
	"Michigan_Oceana" int,
	"Michigan_Ogemaw" int,
	"Michigan_Ontonagon" int,
	"Michigan_Osceola" int,
	"Michigan_Oscoda" int,
	"Michigan_Otsego" int,
	"Michigan_Ottawa" int,
	"Michigan_Out of MI" int,
	"Michigan_Presque Isle" int,
	"Michigan_Roscommon" int,
	"Michigan_Saginaw" int,
	"Michigan_Sanilac" int,
	"Michigan_Schoolcraft" int,
	"Michigan_Shiawassee" int,
	"Michigan_St. Clair" int,
	"Michigan_St. Joseph" int,
	"Michigan_Tuscola" int,
	"Michigan_Unassigned" int,
	"Michigan_Van Buren" int,
	"Michigan_Washtenaw" int,
	"Michigan_Wayne" int,
	"Michigan_Wexford" int,
	"Minnesota_Aitkin" int,
	"Minnesota_Anoka" int,
	"Minnesota_Becker" int,
	"Minnesota_Beltrami" int,
	"Minnesota_Benton" int,
	"Minnesota_Big Stone" int,
	"Minnesota_Blue Earth" int,
	"Minnesota_Brown" int,
	"Minnesota_Carlton" int,
	"Minnesota_Carver" int,
	"Minnesota_Cass" int,
	"Minnesota_Chippewa" int,
	"Minnesota_Chisago" int,
	"Minnesota_Clay" int,
	"Minnesota_Clearwater" int,
	"Minnesota_Cook" int,
	"Minnesota_Cottonwood" int,
	"Minnesota_Crow Wing" int,
	"Minnesota_Dakota" int,
	"Minnesota_Dodge" int,
	"Minnesota_Douglas" int,
	"Minnesota_Faribault" int,
	"Minnesota_Fillmore" int,
	"Minnesota_Freeborn" int,
	"Minnesota_Goodhue" int,
	"Minnesota_Grant" int,
	"Minnesota_Hennepin" int,
	"Minnesota_Houston" int,
	"Minnesota_Hubbard" int,
	"Minnesota_Isanti" int,
	"Minnesota_Itasca" int,
	"Minnesota_Jackson" int,
	"Minnesota_Kanabec" int,
	"Minnesota_Kandiyohi" int,
	"Minnesota_Kittson" int,
	"Minnesota_Koochiching" int,
	"Minnesota_Lac qui Parle" int,
	"Minnesota_Lake" int,
	"Minnesota_Lake of the Woods" int,
	"Minnesota_Le Sueur" int,
	"Minnesota_Lincoln" int,
	"Minnesota_Lyon" int,
	"Minnesota_Mahnomen" int,
	"Minnesota_Marshall" int,
	"Minnesota_Martin" int,
	"Minnesota_McLeod" int,
	"Minnesota_Meeker" int,
	"Minnesota_Mille Lacs" int,
	"Minnesota_Morrison" int,
	"Minnesota_Mower" int,
	"Minnesota_Murray" int,
	"Minnesota_Nicollet" int,
	"Minnesota_Nobles" int,
	"Minnesota_Norman" int,
	"Minnesota_Olmsted" int,
	"Minnesota_Otter Tail" int,
	"Minnesota_Out of MN" int,
	"Minnesota_Pennington" int,
	"Minnesota_Pine" int,
	"Minnesota_Pipestone" int,
	"Minnesota_Polk" int,
	"Minnesota_Pope" int,
	"Minnesota_Ramsey" int,
	"Minnesota_Red Lake" int,
	"Minnesota_Redwood" int,
	"Minnesota_Renville" int,
	"Minnesota_Rice" int,
	"Minnesota_Rock" int,
	"Minnesota_Roseau" int,
	"Minnesota_Scott" int,
	"Minnesota_Sherburne" int,
	"Minnesota_Sibley" int,
	"Minnesota_St. Louis" int,
	"Minnesota_Stearns" int,
	"Minnesota_Steele" int,
	"Minnesota_Stevens" int,
	"Minnesota_Swift" int,
	"Minnesota_Todd" int,
	"Minnesota_Traverse" int,
	"Minnesota_Unassigned" int,
	"Minnesota_Wabasha" int,
	"Minnesota_Wadena" int,
	"Minnesota_Waseca" int,
	"Minnesota_Washington" int,
	"Minnesota_Watonwan" int,
	"Minnesota_Wilkin" int,
	"Minnesota_Winona" int,
	"Minnesota_Wright" int,
	"Minnesota_Yellow Medicine" int,
	"Mississippi_Adams" int,
	"Mississippi_Alcorn" int,
	"Mississippi_Amite" int,
	"Mississippi_Attala" int,
	"Mississippi_Benton" int,
	"Mississippi_Bolivar" int,
	"Mississippi_Calhoun" int,
	"Mississippi_Carroll" int,
	"Mississippi_Chickasaw" int,
	"Mississippi_Choctaw" int,
	"Mississippi_Claiborne" int,
	"Mississippi_Clarke" int,
	"Mississippi_Clay" int,
	"Mississippi_Coahoma" int,
	"Mississippi_Copiah" int,
	"Mississippi_Covington" int,
	"Mississippi_DeSoto" int,
	"Mississippi_Forrest" int,
	"Mississippi_Franklin" int,
	"Mississippi_George" int,
	"Mississippi_Greene" int,
	"Mississippi_Grenada" int,
	"Mississippi_Hancock" int,
	"Mississippi_Harrison" int,
	"Mississippi_Hinds" int,
	"Mississippi_Holmes" int,
	"Mississippi_Humphreys" int,
	"Mississippi_Issaquena" int,
	"Mississippi_Itawamba" int,
	"Mississippi_Jackson" int,
	"Mississippi_Jasper" int,
	"Mississippi_Jefferson" int,
	"Mississippi_Jefferson Davis" int,
	"Mississippi_Jones" int,
	"Mississippi_Kemper" int,
	"Mississippi_Lafayette" int,
	"Mississippi_Lamar" int,
	"Mississippi_Lauderdale" int,
	"Mississippi_Lawrence" int,
	"Mississippi_Leake" int,
	"Mississippi_Lee" int,
	"Mississippi_Leflore" int,
	"Mississippi_Lincoln" int,
	"Mississippi_Lowndes" int,
	"Mississippi_Madison" int,
	"Mississippi_Marion" int,
	"Mississippi_Marshall" int,
	"Mississippi_Monroe" int,
	"Mississippi_Montgomery" int,
	"Mississippi_Neshoba" int,
	"Mississippi_Newton" int,
	"Mississippi_Noxubee" int,
	"Mississippi_Oktibbeha" int,
	"Mississippi_Out of MS" int,
	"Mississippi_Panola" int,
	"Mississippi_Pearl River" int,
	"Mississippi_Perry" int,
	"Mississippi_Pike" int,
	"Mississippi_Pontotoc" int,
	"Mississippi_Prentiss" int,
	"Mississippi_Quitman" int,
	"Mississippi_Rankin" int,
	"Mississippi_Scott" int,
	"Mississippi_Sharkey" int,
	"Mississippi_Simpson" int,
	"Mississippi_Smith" int,
	"Mississippi_Stone" int,
	"Mississippi_Sunflower" int,
	"Mississippi_Tallahatchie" int,
	"Mississippi_Tate" int,
	"Mississippi_Tippah" int,
	"Mississippi_Tishomingo" int,
	"Mississippi_Tunica" int,
	"Mississippi_Unassigned" int,
	"Mississippi_Union" int,
	"Mississippi_Walthall" int,
	"Mississippi_Warren" int,
	"Mississippi_Washington" int,
	"Mississippi_Wayne" int,
	"Mississippi_Webster" int,
	"Mississippi_Wilkinson" int,
	"Mississippi_Winston" int,
	"Mississippi_Yalobusha" int,
	"Mississippi_Yazoo" int,
	"Missouri_Adair" int,
	"Missouri_Andrew" int,
	"Missouri_Atchison" int,
	"Missouri_Audrain" int,
	"Missouri_Barry" int,
	"Missouri_Barton" int,
	"Missouri_Bates" int,
	"Missouri_Benton" int,
	"Missouri_Bollinger" int,
	"Missouri_Boone" int,
	"Missouri_Buchanan" int,
	"Missouri_Butler" int,
	"Missouri_Caldwell" int,
	"Missouri_Callaway" int,
	"Missouri_Camden" int,
	"Missouri_Cape Girardeau" int,
	"Missouri_Carroll" int,
	"Missouri_Carter" int,
	"Missouri_Cass" int,
	"Missouri_Cedar" int,
	"Missouri_Chariton" int,
	"Missouri_Christian" int,
	"Missouri_Clark" int,
	"Missouri_Clay" int,
	"Missouri_Clinton" int,
	"Missouri_Cole" int,
	"Missouri_Cooper" int,
	"Missouri_Crawford" int,
	"Missouri_Dade" int,
	"Missouri_Dallas" int,
	"Missouri_Daviess" int,
	"Missouri_DeKalb" int,
	"Missouri_Dent" int,
	"Missouri_Douglas" int,
	"Missouri_Dunklin" int,
	"Missouri_Franklin" int,
	"Missouri_Gasconade" int,
	"Missouri_Gentry" int,
	"Missouri_Greene" int,
	"Missouri_Grundy" int,
	"Missouri_Harrison" int,
	"Missouri_Henry" int,
	"Missouri_Hickory" int,
	"Missouri_Holt" int,
	"Missouri_Howard" int,
	"Missouri_Howell" int,
	"Missouri_Iron" int,
	"Missouri_Jackson" int,
	"Missouri_Jasper" int,
	"Missouri_Jefferson" int,
	"Missouri_Johnson" int,
	"Missouri_Kansas City" int,
	"Missouri_Knox" int,
	"Missouri_Laclede" int,
	"Missouri_Lafayette" int,
	"Missouri_Lawrence" int,
	"Missouri_Lewis" int,
	"Missouri_Lincoln" int,
	"Missouri_Linn" int,
	"Missouri_Livingston" int,
	"Missouri_Macon" int,
	"Missouri_Madison" int,
	"Missouri_Maries" int,
	"Missouri_Marion" int,
	"Missouri_McDonald" int,
	"Missouri_Mercer" int,
	"Missouri_Miller" int,
	"Missouri_Mississippi" int,
	"Missouri_Moniteau" int,
	"Missouri_Monroe" int,
	"Missouri_Montgomery" int,
	"Missouri_Morgan" int,
	"Missouri_New Madrid" int,
	"Missouri_Newton" int,
	"Missouri_Nodaway" int,
	"Missouri_Oregon" int,
	"Missouri_Osage" int,
	"Missouri_Out of MO" int,
	"Missouri_Ozark" int,
	"Missouri_Pemiscot" int,
	"Missouri_Perry" int,
	"Missouri_Pettis" int,
	"Missouri_Phelps" int,
	"Missouri_Pike" int,
	"Missouri_Platte" int,
	"Missouri_Polk" int,
	"Missouri_Pulaski" int,
	"Missouri_Putnam" int,
	"Missouri_Ralls" int,
	"Missouri_Randolph" int,
	"Missouri_Ray" int,
	"Missouri_Reynolds" int,
	"Missouri_Ripley" int,
	"Missouri_Saline" int,
	"Missouri_Schuyler" int,
	"Missouri_Scotland" int,
	"Missouri_Scott" int,
	"Missouri_Shannon" int,
	"Missouri_Shelby" int,
	"Missouri_St. Charles" int,
	"Missouri_St. Clair" int,
	"Missouri_St. Francois" int,
	"Missouri_St. Louis" int,
	"Missouri_St. Louis City" int,
	"Missouri_Ste. Genevieve" int,
	"Missouri_Stoddard" int,
	"Missouri_Stone" int,
	"Missouri_Sullivan" int,
	"Missouri_Taney" int,
	"Missouri_Texas" int,
	"Missouri_Unassigned" int,
	"Missouri_Vernon" int,
	"Missouri_Warren" int,
	"Missouri_Washington" int,
	"Missouri_Wayne" int,
	"Missouri_Webster" int,
	"Missouri_Worth" int,
	"Missouri_Wright" int,
	"Montana_Beaverhead" int,
	"Montana_Big Horn" int,
	"Montana_Blaine" int,
	"Montana_Broadwater" int,
	"Montana_Carbon" int,
	"Montana_Carter" int,
	"Montana_Cascade" int,
	"Montana_Chouteau" int,
	"Montana_Custer" int,
	"Montana_Daniels" int,
	"Montana_Dawson" int,
	"Montana_Deer Lodge" int,
	"Montana_Fallon" int,
	"Montana_Fergus" int,
	"Montana_Flathead" int,
	"Montana_Gallatin" int,
	"Montana_Garfield" int,
	"Montana_Glacier" int,
	"Montana_Golden Valley" int,
	"Montana_Granite" int,
	"Montana_Hill" int,
	"Montana_Jefferson" int,
	"Montana_Judith Basin" int,
	"Montana_Lake" int,
	"Montana_Lewis and Clark" int,
	"Montana_Liberty" int,
	"Montana_Lincoln" int,
	"Montana_Madison" int,
	"Montana_McCone" int,
	"Montana_Meagher" int,
	"Montana_Mineral" int,
	"Montana_Missoula" int,
	"Montana_Musselshell" int,
	"Montana_Out of MT" int,
	"Montana_Park" int,
	"Montana_Petroleum" int,
	"Montana_Phillips" int,
	"Montana_Pondera" int,
	"Montana_Powder River" int,
	"Montana_Powell" int,
	"Montana_Prairie" int,
	"Montana_Ravalli" int,
	"Montana_Richland" int,
	"Montana_Roosevelt" int,
	"Montana_Rosebud" int,
	"Montana_Sanders" int,
	"Montana_Sheridan" int,
	"Montana_Silver Bow" int,
	"Montana_Stillwater" int,
	"Montana_Sweet Grass" int,
	"Montana_Teton" int,
	"Montana_Toole" int,
	"Montana_Treasure" int,
	"Montana_Unassigned" int,
	"Montana_Valley" int,
	"Montana_Wheatland" int,
	"Montana_Wibaux" int,
	"Montana_Yellowstone" int,
	"Nebraska_Adams" int,
	"Nebraska_Antelope" int,
	"Nebraska_Arthur" int,
	"Nebraska_Banner" int,
	"Nebraska_Blaine" int,
	"Nebraska_Boone" int,
	"Nebraska_Box Butte" int,
	"Nebraska_Boyd" int,
	"Nebraska_Brown" int,
	"Nebraska_Buffalo" int,
	"Nebraska_Burt" int,
	"Nebraska_Butler" int,
	"Nebraska_Cass" int,
	"Nebraska_Cedar" int,
	"Nebraska_Chase" int,
	"Nebraska_Cherry" int,
	"Nebraska_Cheyenne" int,
	"Nebraska_Clay" int,
	"Nebraska_Colfax" int,
	"Nebraska_Cuming" int,
	"Nebraska_Custer" int,
	"Nebraska_Dakota" int,
	"Nebraska_Dawes" int,
	"Nebraska_Dawson" int,
	"Nebraska_Deuel" int,
	"Nebraska_Dixon" int,
	"Nebraska_Dodge" int,
	"Nebraska_Douglas" int,
	"Nebraska_Dundy" int,
	"Nebraska_Fillmore" int,
	"Nebraska_Franklin" int,
	"Nebraska_Frontier" int,
	"Nebraska_Furnas" int,
	"Nebraska_Gage" int,
	"Nebraska_Garden" int,
	"Nebraska_Garfield" int,
	"Nebraska_Gosper" int,
	"Nebraska_Grant" int,
	"Nebraska_Greeley" int,
	"Nebraska_Hall" int,
	"Nebraska_Hamilton" int,
	"Nebraska_Harlan" int,
	"Nebraska_Hayes" int,
	"Nebraska_Hitchcock" int,
	"Nebraska_Holt" int,
	"Nebraska_Hooker" int,
	"Nebraska_Howard" int,
	"Nebraska_Jefferson" int,
	"Nebraska_Johnson" int,
	"Nebraska_Kearney" int,
	"Nebraska_Keith" int,
	"Nebraska_Keya Paha" int,
	"Nebraska_Kimball" int,
	"Nebraska_Knox" int,
	"Nebraska_Lancaster" int,
	"Nebraska_Lincoln" int,
	"Nebraska_Logan" int,
	"Nebraska_Loup" int,
	"Nebraska_Madison" int,
	"Nebraska_McPherson" int,
	"Nebraska_Merrick" int,
	"Nebraska_Morrill" int,
	"Nebraska_Nance" int,
	"Nebraska_Nemaha" int,
	"Nebraska_Nuckolls" int,
	"Nebraska_Otoe" int,
	"Nebraska_Out of NE" int,
	"Nebraska_Pawnee" int,
	"Nebraska_Perkins" int,
	"Nebraska_Phelps" int,
	"Nebraska_Pierce" int,
	"Nebraska_Platte" int,
	"Nebraska_Polk" int,
	"Nebraska_Red Willow" int,
	"Nebraska_Richardson" int,
	"Nebraska_Rock" int,
	"Nebraska_Saline" int,
	"Nebraska_Sarpy" int,
	"Nebraska_Saunders" int,
	"Nebraska_Scotts Bluff" int,
	"Nebraska_Seward" int,
	"Nebraska_Sheridan" int,
	"Nebraska_Sherman" int,
	"Nebraska_Sioux" int,
	"Nebraska_Stanton" int,
	"Nebraska_Thayer" int,
	"Nebraska_Thomas" int,
	"Nebraska_Thurston" int,
	"Nebraska_Unassigned" int,
	"Nebraska_Valley" int,
	"Nebraska_Washington" int,
	"Nebraska_Wayne" int,
	"Nebraska_Webster" int,
	"Nebraska_Wheeler" int,
	"Nebraska_York" int,
	"Nevada_Carson City" int,
	"Nevada_Churchill" int,
	"Nevada_Clark" int,
	"Nevada_Douglas" int,
	"Nevada_Elko" int,
	"Nevada_Esmeralda" int,
	"Nevada_Eureka" int,
	"Nevada_Humboldt" int,
	"Nevada_Lander" int,
	"Nevada_Lincoln" int,
	"Nevada_Lyon" int,
	"Nevada_Mineral" int,
	"Nevada_Nye" int,
	"Nevada_Out of NV" int,
	"Nevada_Pershing" int,
	"Nevada_Storey" int,
	"Nevada_Unassigned" int,
	"Nevada_Washoe" int,
	"Nevada_White Pine" int,
	"New Hampshire_Belknap" int,
	"New Hampshire_Carroll" int,
	"New Hampshire_Cheshire" int,
	"New Hampshire_Coos" int,
	"New Hampshire_Grafton" int,
	"New Hampshire_Hillsborough" int,
	"New Hampshire_Merrimack" int,
	"New Hampshire_Out of NH" int,
	"New Hampshire_Rockingham" int,
	"New Hampshire_Strafford" int,
	"New Hampshire_Sullivan" int,
	"New Hampshire_Unassigned" int,
	"New Jersey_Atlantic" int,
	"New Jersey_Bergen" int,
	"New Jersey_Burlington" int,
	"New Jersey_Camden" int,
	"New Jersey_Cape May" int,
	"New Jersey_Cumberland" int,
	"New Jersey_Essex" int,
	"New Jersey_Gloucester" int,
	"New Jersey_Hudson" int,
	"New Jersey_Hunterdon" int,
	"New Jersey_Mercer" int,
	"New Jersey_Middlesex" int,
	"New Jersey_Monmouth" int,
	"New Jersey_Morris" int,
	"New Jersey_Ocean" int,
	"New Jersey_Out of NJ" int,
	"New Jersey_Passaic" int,
	"New Jersey_Salem" int,
	"New Jersey_Somerset" int,
	"New Jersey_Sussex" int,
	"New Jersey_Unassigned" int,
	"New Jersey_Union" int,
	"New Jersey_Warren" int,
	"New Mexico_Bernalillo" int,
	"New Mexico_Catron" int,
	"New Mexico_Chaves" int,
	"New Mexico_Cibola" int,
	"New Mexico_Colfax" int,
	"New Mexico_Curry" int,
	"New Mexico_De Baca" int,
	"New Mexico_Dona Ana" int,
	"New Mexico_Eddy" int,
	"New Mexico_Grant" int,
	"New Mexico_Guadalupe" int,
	"New Mexico_Harding" int,
	"New Mexico_Hidalgo" int,
	"New Mexico_Lea" int,
	"New Mexico_Lincoln" int,
	"New Mexico_Los Alamos" int,
	"New Mexico_Luna" int,
	"New Mexico_McKinley" int,
	"New Mexico_Mora" int,
	"New Mexico_Otero" int,
	"New Mexico_Out of NM" int,
	"New Mexico_Quay" int,
	"New Mexico_Rio Arriba" int,
	"New Mexico_Roosevelt" int,
	"New Mexico_San Juan" int,
	"New Mexico_San Miguel" int,
	"New Mexico_Sandoval" int,
	"New Mexico_Santa Fe" int,
	"New Mexico_Sierra" int,
	"New Mexico_Socorro" int,
	"New Mexico_Taos" int,
	"New Mexico_Torrance" int,
	"New Mexico_Unassigned" int,
	"New Mexico_Union" int,
	"New Mexico_Valencia" int,
	"New York_Albany" int,
	"New York_Allegany" int,
	"New York_Bronx" int,
	"New York_Broome" int,
	"New York_Cattaraugus" int,
	"New York_Cayuga" int,
	"New York_Chautauqua" int,
	"New York_Chemung" int,
	"New York_Chenango" int,
	"New York_Clinton" int,
	"New York_Columbia" int,
	"New York_Cortland" int,
	"New York_Delaware" int,
	"New York_Dutchess" int,
	"New York_Erie" int,
	"New York_Essex" int,
	"New York_Franklin" int,
	"New York_Fulton" int,
	"New York_Genesee" int,
	"New York_Greene" int,
	"New York_Hamilton" int,
	"New York_Herkimer" int,
	"New York_Jefferson" int,
	"New York_Kings" int,
	"New York_Lewis" int,
	"New York_Livingston" int,
	"New York_Madison" int,
	"New York_Monroe" int,
	"New York_Montgomery" int,
	"New York_Nassau" int,
	"New York_New York" int,
	"New York_Niagara" int,
	"New York_Oneida" int,
	"New York_Onondaga" int,
	"New York_Ontario" int,
	"New York_Orange" int,
	"New York_Orleans" int,
	"New York_Oswego" int,
	"New York_Otsego" int,
	"New York_Out of NY" int,
	"New York_Putnam" int,
	"New York_Queens" int,
	"New York_Rensselaer" int,
	"New York_Richmond" int,
	"New York_Rockland" int,
	"New York_Saratoga" int,
	"New York_Schenectady" int,
	"New York_Schoharie" int,
	"New York_Schuyler" int,
	"New York_Seneca" int,
	"New York_St. Lawrence" int,
	"New York_Steuben" int,
	"New York_Suffolk" int,
	"New York_Sullivan" int,
	"New York_Tioga" int,
	"New York_Tompkins" int,
	"New York_Ulster" int,
	"New York_Unassigned" int,
	"New York_Warren" int,
	"New York_Washington" int,
	"New York_Wayne" int,
	"New York_Westchester" int,
	"New York_Wyoming" int,
	"New York_Yates" int,
	"North Carolina_Alamance" int,
	"North Carolina_Alexander" int,
	"North Carolina_Alleghany" int,
	"North Carolina_Anson" int,
	"North Carolina_Ashe" int,
	"North Carolina_Avery" int,
	"North Carolina_Beaufort" int,
	"North Carolina_Bertie" int,
	"North Carolina_Bladen" int,
	"North Carolina_Brunswick" int,
	"North Carolina_Buncombe" int,
	"North Carolina_Burke" int,
	"North Carolina_Cabarrus" int,
	"North Carolina_Caldwell" int,
	"North Carolina_Camden" int,
	"North Carolina_Carteret" int,
	"North Carolina_Caswell" int,
	"North Carolina_Catawba" int,
	"North Carolina_Chatham" int,
	"North Carolina_Cherokee" int,
	"North Carolina_Chowan" int,
	"North Carolina_Clay" int,
	"North Carolina_Cleveland" int,
	"North Carolina_Columbus" int,
	"North Carolina_Craven" int,
	"North Carolina_Cumberland" int,
	"North Carolina_Currituck" int,
	"North Carolina_Dare" int,
	"North Carolina_Davidson" int,
	"North Carolina_Davie" int,
	"North Carolina_Duplin" int,
	"North Carolina_Durham" int,
	"North Carolina_Edgecombe" int,
	"North Carolina_Forsyth" int,
	"North Carolina_Franklin" int,
	"North Carolina_Gaston" int,
	"North Carolina_Gates" int,
	"North Carolina_Graham" int,
	"North Carolina_Granville" int,
	"North Carolina_Greene" int,
	"North Carolina_Guilford" int,
	"North Carolina_Halifax" int,
	"North Carolina_Harnett" int,
	"North Carolina_Haywood" int,
	"North Carolina_Henderson" int,
	"North Carolina_Hertford" int,
	"North Carolina_Hoke" int,
	"North Carolina_Hyde" int,
	"North Carolina_Iredell" int,
	"North Carolina_Jackson" int,
	"North Carolina_Johnston" int,
	"North Carolina_Jones" int,
	"North Carolina_Lee" int,
	"North Carolina_Lenoir" int,
	"North Carolina_Lincoln" int,
	"North Carolina_Macon" int,
	"North Carolina_Madison" int,
	"North Carolina_Martin" int,
	"North Carolina_McDowell" int,
	"North Carolina_Mecklenburg" int,
	"North Carolina_Mitchell" int,
	"North Carolina_Montgomery" int,
	"North Carolina_Moore" int,
	"North Carolina_Nash" int,
	"North Carolina_New Hanover" int,
	"North Carolina_Northampton" int,
	"North Carolina_Onslow" int,
	"North Carolina_Orange" int,
	"North Carolina_Out of NC" int,
	"North Carolina_Pamlico" int,
	"North Carolina_Pasquotank" int,
	"North Carolina_Pender" int,
	"North Carolina_Perquimans" int,
	"North Carolina_Person" int,
	"North Carolina_Pitt" int,
	"North Carolina_Polk" int,
	"North Carolina_Randolph" int,
	"North Carolina_Richmond" int,
	"North Carolina_Robeson" int,
	"North Carolina_Rockingham" int,
	"North Carolina_Rowan" int,
	"North Carolina_Rutherford" int,
	"North Carolina_Sampson" int,
	"North Carolina_Scotland" int,
	"North Carolina_Stanly" int,
	"North Carolina_Stokes" int,
	"North Carolina_Surry" int,
	"North Carolina_Swain" int,
	"North Carolina_Transylvania" int,
	"North Carolina_Tyrrell" int,
	"North Carolina_Unassigned" int,
	"North Carolina_Union" int,
	"North Carolina_Vance" int,
	"North Carolina_Wake" int,
	"North Carolina_Warren" int,
	"North Carolina_Washington" int,
	"North Carolina_Watauga" int,
	"North Carolina_Wayne" int,
	"North Carolina_Wilkes" int,
	"North Carolina_Wilson" int,
	"North Carolina_Yadkin" int,
	"North Carolina_Yancey" int,
	"North Dakota_Adams" int,
	"North Dakota_Barnes" int,
	"North Dakota_Benson" int,
	"North Dakota_Billings" int,
	"North Dakota_Bottineau" int,
	"North Dakota_Bowman" int,
	"North Dakota_Burke" int,
	"North Dakota_Burleigh" int,
	"North Dakota_Cass" int,
	"North Dakota_Cavalier" int,
	"North Dakota_Dickey" int,
	"North Dakota_Divide" int,
	"North Dakota_Dunn" int,
	"North Dakota_Eddy" int,
	"North Dakota_Emmons" int,
	"North Dakota_Foster" int,
	"North Dakota_Golden Valley" int,
	"North Dakota_Grand Forks" int,
	"North Dakota_Grant" int,
	"North Dakota_Griggs" int,
	"North Dakota_Hettinger" int,
	"North Dakota_Kidder" int,
	"North Dakota_LaMoure" int,
	"North Dakota_Logan" int,
	"North Dakota_McHenry" int,
	"North Dakota_McIntosh" int,
	"North Dakota_McKenzie" int,
	"North Dakota_McLean" int,
	"North Dakota_Mercer" int,
	"North Dakota_Morton" int,
	"North Dakota_Mountrail" int,
	"North Dakota_Nelson" int,
	"North Dakota_Oliver" int,
	"North Dakota_Out of ND" int,
	"North Dakota_Pembina" int,
	"North Dakota_Pierce" int,
	"North Dakota_Ramsey" int,
	"North Dakota_Ransom" int,
	"North Dakota_Renville" int,
	"North Dakota_Richland" int,
	"North Dakota_Rolette" int,
	"North Dakota_Sargent" int,
	"North Dakota_Sheridan" int,
	"North Dakota_Sioux" int,
	"North Dakota_Slope" int,
	"North Dakota_Stark" int,
	"North Dakota_Steele" int,
	"North Dakota_Stutsman" int,
	"North Dakota_Towner" int,
	"North Dakota_Traill" int,
	"North Dakota_Unassigned" int,
	"North Dakota_Walsh" int,
	"North Dakota_Ward" int,
	"North Dakota_Wells" int,
	"North Dakota_Williams" int,
	"Northern Mariana Islands" int,
	"Ohio_Adams" int,
	"Ohio_Allen" int,
	"Ohio_Ashland" int,
	"Ohio_Ashtabula" int,
	"Ohio_Athens" int,
	"Ohio_Auglaize" int,
	"Ohio_Belmont" int,
	"Ohio_Brown" int,
	"Ohio_Butler" int,
	"Ohio_Carroll" int,
	"Ohio_Champaign" int,
	"Ohio_Clark" int,
	"Ohio_Clermont" int,
	"Ohio_Clinton" int,
	"Ohio_Columbiana" int,
	"Ohio_Coshocton" int,
	"Ohio_Crawford" int,
	"Ohio_Cuyahoga" int,
	"Ohio_Darke" int,
	"Ohio_Defiance" int,
	"Ohio_Delaware" int,
	"Ohio_Erie" int,
	"Ohio_Fairfield" int,
	"Ohio_Fayette" int,
	"Ohio_Franklin" int,
	"Ohio_Fulton" int,
	"Ohio_Gallia" int,
	"Ohio_Geauga" int,
	"Ohio_Greene" int,
	"Ohio_Guernsey" int,
	"Ohio_Hamilton" int,
	"Ohio_Hancock" int,
	"Ohio_Hardin" int,
	"Ohio_Harrison" int,
	"Ohio_Henry" int,
	"Ohio_Highland" int,
	"Ohio_Hocking" int,
	"Ohio_Holmes" int,
	"Ohio_Huron" int,
	"Ohio_Jackson" int,
	"Ohio_Jefferson" int,
	"Ohio_Knox" int,
	"Ohio_Lake" int,
	"Ohio_Lawrence" int,
	"Ohio_Licking" int,
	"Ohio_Logan" int,
	"Ohio_Lorain" int,
	"Ohio_Lucas" int,
	"Ohio_Madison" int,
	"Ohio_Mahoning" int,
	"Ohio_Marion" int,
	"Ohio_Medina" int,
	"Ohio_Meigs" int,
	"Ohio_Mercer" int,
	"Ohio_Miami" int,
	"Ohio_Monroe" int,
	"Ohio_Montgomery" int,
	"Ohio_Morgan" int,
	"Ohio_Morrow" int,
	"Ohio_Muskingum" int,
	"Ohio_Noble" int,
	"Ohio_Ottawa" int,
	"Ohio_Out of OH" int,
	"Ohio_Paulding" int,
	"Ohio_Perry" int,
	"Ohio_Pickaway" int,
	"Ohio_Pike" int,
	"Ohio_Portage" int,
	"Ohio_Preble" int,
	"Ohio_Putnam" int,
	"Ohio_Richland" int,
	"Ohio_Ross" int,
	"Ohio_Sandusky" int,
	"Ohio_Scioto" int,
	"Ohio_Seneca" int,
	"Ohio_Shelby" int,
	"Ohio_Stark" int,
	"Ohio_Summit" int,
	"Ohio_Trumbull" int,
	"Ohio_Tuscarawas" int,
	"Ohio_Unassigned" int,
	"Ohio_Union" int,
	"Ohio_Van Wert" int,
	"Ohio_Vinton" int,
	"Ohio_Warren" int,
	"Ohio_Washington" int,
	"Ohio_Wayne" int,
	"Ohio_Williams" int,
	"Ohio_Wood" int,
	"Ohio_Wyandot" int,
	"Oklahoma_Adair" int,
	"Oklahoma_Alfalfa" int,
	"Oklahoma_Atoka" int,
	"Oklahoma_Beaver" int,
	"Oklahoma_Beckham" int,
	"Oklahoma_Blaine" int,
	"Oklahoma_Bryan" int,
	"Oklahoma_Caddo" int,
	"Oklahoma_Canadian" int,
	"Oklahoma_Carter" int,
	"Oklahoma_Cherokee" int,
	"Oklahoma_Choctaw" int,
	"Oklahoma_Cimarron" int,
	"Oklahoma_Cleveland" int,
	"Oklahoma_Coal" int,
	"Oklahoma_Comanche" int,
	"Oklahoma_Cotton" int,
	"Oklahoma_Craig" int,
	"Oklahoma_Creek" int,
	"Oklahoma_Custer" int,
	"Oklahoma_Delaware" int,
	"Oklahoma_Dewey" int,
	"Oklahoma_Ellis" int,
	"Oklahoma_Garfield" int,
	"Oklahoma_Garvin" int,
	"Oklahoma_Grady" int,
	"Oklahoma_Grant" int,
	"Oklahoma_Greer" int,
	"Oklahoma_Harmon" int,
	"Oklahoma_Harper" int,
	"Oklahoma_Haskell" int,
	"Oklahoma_Hughes" int,
	"Oklahoma_Jackson" int,
	"Oklahoma_Jefferson" int,
	"Oklahoma_Johnston" int,
	"Oklahoma_Kay" int,
	"Oklahoma_Kingfisher" int,
	"Oklahoma_Kiowa" int,
	"Oklahoma_Latimer" int,
	"Oklahoma_Le Flore" int,
	"Oklahoma_Lincoln" int,
	"Oklahoma_Logan" int,
	"Oklahoma_Love" int,
	"Oklahoma_Major" int,
	"Oklahoma_Marshall" int,
	"Oklahoma_Mayes" int,
	"Oklahoma_McClain" int,
	"Oklahoma_McCurtain" int,
	"Oklahoma_McIntosh" int,
	"Oklahoma_Murray" int,
	"Oklahoma_Muskogee" int,
	"Oklahoma_Noble" int,
	"Oklahoma_Nowata" int,
	"Oklahoma_Okfuskee" int,
	"Oklahoma_Oklahoma" int,
	"Oklahoma_Okmulgee" int,
	"Oklahoma_Osage" int,
	"Oklahoma_Ottawa" int,
	"Oklahoma_Out of OK" int,
	"Oklahoma_Pawnee" int,
	"Oklahoma_Payne" int,
	"Oklahoma_Pittsburg" int,
	"Oklahoma_Pontotoc" int,
	"Oklahoma_Pottawatomie" int,
	"Oklahoma_Pushmataha" int,
	"Oklahoma_Roger Mills" int,
	"Oklahoma_Rogers" int,
	"Oklahoma_Seminole" int,
	"Oklahoma_Sequoyah" int,
	"Oklahoma_Stephens" int,
	"Oklahoma_Texas" int,
	"Oklahoma_Tillman" int,
	"Oklahoma_Tulsa" int,
	"Oklahoma_Unassigned" int,
	"Oklahoma_Wagoner" int,
	"Oklahoma_Washington" int,
	"Oklahoma_Washita" int,
	"Oklahoma_Woods" int,
	"Oklahoma_Woodward" int,
	"Oregon_Baker" int,
	"Oregon_Benton" int,
	"Oregon_Clackamas" int,
	"Oregon_Clatsop" int,
	"Oregon_Columbia" int,
	"Oregon_Coos" int,
	"Oregon_Crook" int,
	"Oregon_Curry" int,
	"Oregon_Deschutes" int,
	"Oregon_Douglas" int,
	"Oregon_Gilliam" int,
	"Oregon_Grant" int,
	"Oregon_Harney" int,
	"Oregon_Hood River" int,
	"Oregon_Jackson" int,
	"Oregon_Jefferson" int,
	"Oregon_Josephine" int,
	"Oregon_Klamath" int,
	"Oregon_Lake" int,
	"Oregon_Lane" int,
	"Oregon_Lincoln" int,
	"Oregon_Linn" int,
	"Oregon_Malheur" int,
	"Oregon_Marion" int,
	"Oregon_Morrow" int,
	"Oregon_Multnomah" int,
	"Oregon_Out of OR" int,
	"Oregon_Polk" int,
	"Oregon_Sherman" int,
	"Oregon_Tillamook" int,
	"Oregon_Umatilla" int,
	"Oregon_Unassigned" int,
	"Oregon_Union" int,
	"Oregon_Wallowa" int,
	"Oregon_Wasco" int,
	"Oregon_Washington" int,
	"Oregon_Wheeler" int,
	"Oregon_Yamhill" int,
	"Pennsylvania_Adams" int,
	"Pennsylvania_Allegheny" int,
	"Pennsylvania_Armstrong" int,
	"Pennsylvania_Beaver" int,
	"Pennsylvania_Bedford" int,
	"Pennsylvania_Berks" int,
	"Pennsylvania_Blair" int,
	"Pennsylvania_Bradford" int,
	"Pennsylvania_Bucks" int,
	"Pennsylvania_Butler" int,
	"Pennsylvania_Cambria" int,
	"Pennsylvania_Cameron" int,
	"Pennsylvania_Carbon" int,
	"Pennsylvania_Centre" int,
	"Pennsylvania_Chester" int,
	"Pennsylvania_Clarion" int,
	"Pennsylvania_Clearfield" int,
	"Pennsylvania_Clinton" int,
	"Pennsylvania_Columbia" int,
	"Pennsylvania_Crawford" int,
	"Pennsylvania_Cumberland" int,
	"Pennsylvania_Dauphin" int,
	"Pennsylvania_Delaware" int,
	"Pennsylvania_Elk" int,
	"Pennsylvania_Erie" int,
	"Pennsylvania_Fayette" int,
	"Pennsylvania_Forest" int,
	"Pennsylvania_Franklin" int,
	"Pennsylvania_Fulton" int,
	"Pennsylvania_Greene" int,
	"Pennsylvania_Huntingdon" int,
	"Pennsylvania_Indiana" int,
	"Pennsylvania_Jefferson" int,
	"Pennsylvania_Juniata" int,
	"Pennsylvania_Lackawanna" int,
	"Pennsylvania_Lancaster" int,
	"Pennsylvania_Lawrence" int,
	"Pennsylvania_Lebanon" int,
	"Pennsylvania_Lehigh" int,
	"Pennsylvania_Luzerne" int,
	"Pennsylvania_Lycoming" int,
	"Pennsylvania_McKean" int,
	"Pennsylvania_Mercer" int,
	"Pennsylvania_Mifflin" int,
	"Pennsylvania_Monroe" int,
	"Pennsylvania_Montgomery" int,
	"Pennsylvania_Montour" int,
	"Pennsylvania_Northampton" int,
	"Pennsylvania_Northumberland" int,
	"Pennsylvania_Out of PA" int,
	"Pennsylvania_Perry" int,
	"Pennsylvania_Philadelphia" int,
	"Pennsylvania_Pike" int,
	"Pennsylvania_Potter" int,
	"Pennsylvania_Schuylkill" int,
	"Pennsylvania_Snyder" int,
	"Pennsylvania_Somerset" int,
	"Pennsylvania_Sullivan" int,
	"Pennsylvania_Susquehanna" int,
	"Pennsylvania_Tioga" int,
	"Pennsylvania_Unassigned" int,
	"Pennsylvania_Union" int,
	"Pennsylvania_Venango" int,
	"Pennsylvania_Warren" int,
	"Pennsylvania_Washington" int,
	"Pennsylvania_Wayne" int,
	"Pennsylvania_Westmoreland" int,
	"Pennsylvania_Wyoming" int,
	"Pennsylvania_York" int,
	"Puerto Rico_Adjuntas" int,
	"Puerto Rico_Aguada" int,
	"Puerto Rico_Aguadilla" int,
	"Puerto Rico_Aguas Buenas" int,
	"Puerto Rico_Aibonito" int,
	"Puerto Rico_Anasco" int,
	"Puerto Rico_Arecibo" int,
	"Puerto Rico_Arroyo" int,
	"Puerto Rico_Barceloneta" int,
	"Puerto Rico_Barranquitas" int,
	"Puerto Rico_Bayamon" int,
	"Puerto Rico_Cabo Rojo" int,
	"Puerto Rico_Caguas" int,
	"Puerto Rico_Camuy" int,
	"Puerto Rico_Canovanas" int,
	"Puerto Rico_Carolina" int,
	"Puerto Rico_Catano" int,
	"Puerto Rico_Cayey" int,
	"Puerto Rico_Ceiba" int,
	"Puerto Rico_Ciales" int,
	"Puerto Rico_Cidra" int,
	"Puerto Rico_Coamo" int,
	"Puerto Rico_Comerio" int,
	"Puerto Rico_Corozal" int,
	"Puerto Rico_Culebra" int,
	"Puerto Rico_Dorado" int,
	"Puerto Rico_Fajardo" int,
	"Puerto Rico_Florida" int,
	"Puerto Rico_Guanica" int,
	"Puerto Rico_Guayama" int,
	"Puerto Rico_Guayanilla" int,
	"Puerto Rico_Guaynabo" int,
	"Puerto Rico_Gurabo" int,
	"Puerto Rico_Hatillo" int,
	"Puerto Rico_Hormigueros" int,
	"Puerto Rico_Humacao" int,
	"Puerto Rico_Isabela" int,
	"Puerto Rico_Jayuya" int,
	"Puerto Rico_Juana Diaz" int,
	"Puerto Rico_Juncos" int,
	"Puerto Rico_Lajas" int,
	"Puerto Rico_Lares" int,
	"Puerto Rico_Las Marias" int,
	"Puerto Rico_Las Piedras" int,
	"Puerto Rico_Loiza" int,
	"Puerto Rico_Luquillo" int,
	"Puerto Rico_Manati" int,
	"Puerto Rico_Maricao" int,
	"Puerto Rico_Maunabo" int,
	"Puerto Rico_Mayaguez" int,
	"Puerto Rico_Moca" int,
	"Puerto Rico_Morovis" int,
	"Puerto Rico_Naguabo" int,
	"Puerto Rico_Naranjito" int,
	"Puerto Rico_Orocovis" int,
	"Puerto Rico_Out of PR" int,
	"Puerto Rico_Patillas" int,
	"Puerto Rico_Penuelas" int,
	"Puerto Rico_Ponce" int,
	"Puerto Rico_Quebradillas" int,
	"Puerto Rico_Rincon" int,
	"Puerto Rico_Rio Grande" int,
	"Puerto Rico_Sabana Grande" int,
	"Puerto Rico_Salinas" int,
	"Puerto Rico_San German" int,
	"Puerto Rico_San Juan" int,
	"Puerto Rico_San Lorenzo" int,
	"Puerto Rico_San Sebastian" int,
	"Puerto Rico_Santa Isabel" int,
	"Puerto Rico_Toa Alta" int,
	"Puerto Rico_Toa Baja" int,
	"Puerto Rico_Trujillo Alto" int,
	"Puerto Rico_Unassigned" int,
	"Puerto Rico_Utuado" int,
	"Puerto Rico_Vega Alta" int,
	"Puerto Rico_Vega Baja" int,
	"Puerto Rico_Vieques" int,
	"Puerto Rico_Villalba" int,
	"Puerto Rico_Yabucoa" int,
	"Puerto Rico_Yauco" int,
	"Rhode Island_Bristol" int,
	"Rhode Island_Kent" int,
	"Rhode Island_Newport" int,
	"Rhode Island_Out of RI" int,
	"Rhode Island_Providence" int,
	"Rhode Island_Unassigned" int,
	"Rhode Island_Washington" int,
	"South Carolina_Abbeville" int,
	"South Carolina_Aiken" int,
	"South Carolina_Allendale" int,
	"South Carolina_Anderson" int,
	"South Carolina_Bamberg" int,
	"South Carolina_Barnwell" int,
	"South Carolina_Beaufort" int,
	"South Carolina_Berkeley" int,
	"South Carolina_Calhoun" int,
	"South Carolina_Charleston" int,
	"South Carolina_Cherokee" int,
	"South Carolina_Chester" int,
	"South Carolina_Chesterfield" int,
	"South Carolina_Clarendon" int,
	"South Carolina_Colleton" int,
	"South Carolina_Darlington" int,
	"South Carolina_Dillon" int,
	"South Carolina_Dorchester" int,
	"South Carolina_Edgefield" int,
	"South Carolina_Fairfield" int,
	"South Carolina_Florence" int,
	"South Carolina_Georgetown" int,
	"South Carolina_Greenville" int,
	"South Carolina_Greenwood" int,
	"South Carolina_Hampton" int,
	"South Carolina_Horry" int,
	"South Carolina_Jasper" int,
	"South Carolina_Kershaw" int,
	"South Carolina_Lancaster" int,
	"South Carolina_Laurens" int,
	"South Carolina_Lee" int,
	"South Carolina_Lexington" int,
	"South Carolina_Marion" int,
	"South Carolina_Marlboro" int,
	"South Carolina_McCormick" int,
	"South Carolina_Newberry" int,
	"South Carolina_Oconee" int,
	"South Carolina_Orangeburg" int,
	"South Carolina_Out of SC" int,
	"South Carolina_Pickens" int,
	"South Carolina_Richland" int,
	"South Carolina_Saluda" int,
	"South Carolina_Spartanburg" int,
	"South Carolina_Sumter" int,
	"South Carolina_Unassigned" int,
	"South Carolina_Union" int,
	"South Carolina_Williamsburg" int,
	"South Carolina_York" int,
	"South Dakota_Aurora" int,
	"South Dakota_Beadle" int,
	"South Dakota_Bennett" int,
	"South Dakota_Bon Homme" int,
	"South Dakota_Brookings" int,
	"South Dakota_Brown" int,
	"South Dakota_Brule" int,
	"South Dakota_Buffalo" int,
	"South Dakota_Butte" int,
	"South Dakota_Campbell" int,
	"South Dakota_Charles Mix" int,
	"South Dakota_Clark" int,
	"South Dakota_Clay" int,
	"South Dakota_Codington" int,
	"South Dakota_Corson" int,
	"South Dakota_Custer" int,
	"South Dakota_Davison" int,
	"South Dakota_Day" int,
	"South Dakota_Deuel" int,
	"South Dakota_Dewey" int,
	"South Dakota_Douglas" int,
	"South Dakota_Edmunds" int,
	"South Dakota_Fall River" int,
	"South Dakota_Faulk" int,
	"South Dakota_Grant" int,
	"South Dakota_Gregory" int,
	"South Dakota_Haakon" int,
	"South Dakota_Hamlin" int,
	"South Dakota_Hand" int,
	"South Dakota_Hanson" int,
	"South Dakota_Harding" int,
	"South Dakota_Hughes" int,
	"South Dakota_Hutchinson" int,
	"South Dakota_Hyde" int,
	"South Dakota_Jackson" int,
	"South Dakota_Jerauld" int,
	"South Dakota_Jones" int,
	"South Dakota_Kingsbury" int,
	"South Dakota_Lake" int,
	"South Dakota_Lawrence" int,
	"South Dakota_Lincoln" int,
	"South Dakota_Lyman" int,
	"South Dakota_Marshall" int,
	"South Dakota_McCook" int,
	"South Dakota_McPherson" int,
	"South Dakota_Meade" int,
	"South Dakota_Mellette" int,
	"South Dakota_Miner" int,
	"South Dakota_Minnehaha" int,
	"South Dakota_Moody" int,
	"South Dakota_Oglala Lakota" int,
	"South Dakota_Out of SD" int,
	"South Dakota_Pennington" int,
	"South Dakota_Perkins" int,
	"South Dakota_Potter" int,
	"South Dakota_Roberts" int,
	"South Dakota_Sanborn" int,
	"South Dakota_Spink" int,
	"South Dakota_Stanley" int,
	"South Dakota_Sully" int,
	"South Dakota_Todd" int,
	"South Dakota_Tripp" int,
	"South Dakota_Turner" int,
	"South Dakota_Unassigned" int,
	"South Dakota_Union" int,
	"South Dakota_Walworth" int,
	"South Dakota_Yankton" int,
	"South Dakota_Ziebach" int,
	"Tennessee_Anderson" int,
	"Tennessee_Bedford" int,
	"Tennessee_Benton" int,
	"Tennessee_Bledsoe" int,
	"Tennessee_Blount" int,
	"Tennessee_Bradley" int,
	"Tennessee_Campbell" int,
	"Tennessee_Cannon" int,
	"Tennessee_Carroll" int,
	"Tennessee_Carter" int,
	"Tennessee_Cheatham" int,
	"Tennessee_Chester" int,
	"Tennessee_Claiborne" int,
	"Tennessee_Clay" int,
	"Tennessee_Cocke" int,
	"Tennessee_Coffee" int,
	"Tennessee_Crockett" int,
	"Tennessee_Cumberland" int,
	"Tennessee_Davidson" int,
	"Tennessee_DeKalb" int,
	"Tennessee_Decatur" int,
	"Tennessee_Dickson" int,
	"Tennessee_Dyer" int,
	"Tennessee_Fayette" int,
	"Tennessee_Fentress" int,
	"Tennessee_Franklin" int,
	"Tennessee_Gibson" int,
	"Tennessee_Giles" int,
	"Tennessee_Grainger" int,
	"Tennessee_Greene" int,
	"Tennessee_Grundy" int,
	"Tennessee_Hamblen" int,
	"Tennessee_Hamilton" int,
	"Tennessee_Hancock" int,
	"Tennessee_Hardeman" int,
	"Tennessee_Hardin" int,
	"Tennessee_Hawkins" int,
	"Tennessee_Haywood" int,
	"Tennessee_Henderson" int,
	"Tennessee_Henry" int,
	"Tennessee_Hickman" int,
	"Tennessee_Houston" int,
	"Tennessee_Humphreys" int,
	"Tennessee_Jackson" int,
	"Tennessee_Jefferson" int,
	"Tennessee_Johnson" int,
	"Tennessee_Knox" int,
	"Tennessee_Lake" int,
	"Tennessee_Lauderdale" int,
	"Tennessee_Lawrence" int,
	"Tennessee_Lewis" int,
	"Tennessee_Lincoln" int,
	"Tennessee_Loudon" int,
	"Tennessee_Macon" int,
	"Tennessee_Madison" int,
	"Tennessee_Marion" int,
	"Tennessee_Marshall" int,
	"Tennessee_Maury" int,
	"Tennessee_McMinn" int,
	"Tennessee_McNairy" int,
	"Tennessee_Meigs" int,
	"Tennessee_Monroe" int,
	"Tennessee_Montgomery" int,
	"Tennessee_Moore" int,
	"Tennessee_Morgan" int,
	"Tennessee_Obion" int,
	"Tennessee_Out of TN" int,
	"Tennessee_Overton" int,
	"Tennessee_Perry" int,
	"Tennessee_Pickett" int,
	"Tennessee_Polk" int,
	"Tennessee_Putnam" int,
	"Tennessee_Rhea" int,
	"Tennessee_Roane" int,
	"Tennessee_Robertson" int,
	"Tennessee_Rutherford" int,
	"Tennessee_Scott" int,
	"Tennessee_Sequatchie" int,
	"Tennessee_Sevier" int,
	"Tennessee_Shelby" int,
	"Tennessee_Smith" int,
	"Tennessee_Stewart" int,
	"Tennessee_Sullivan" int,
	"Tennessee_Sumner" int,
	"Tennessee_Tipton" int,
	"Tennessee_Trousdale" int,
	"Tennessee_Unassigned" int,
	"Tennessee_Unicoi" int,
	"Tennessee_Union" int,
	"Tennessee_Van Buren" int,
	"Tennessee_Warren" int,
	"Tennessee_Washington" int,
	"Tennessee_Wayne" int,
	"Tennessee_Weakley" int,
	"Tennessee_White" int,
	"Tennessee_Williamson" int,
	"Tennessee_Wilson" int,
	"Texas_Anderson" int,
	"Texas_Andrews" int,
	"Texas_Angelina" int,
	"Texas_Aransas" int,
	"Texas_Archer" int,
	"Texas_Armstrong" int,
	"Texas_Atascosa" int,
	"Texas_Austin" int,
	"Texas_Bailey" int,
	"Texas_Bandera" int,
	"Texas_Bastrop" int,
	"Texas_Baylor" int,
	"Texas_Bee" int,
	"Texas_Bell" int,
	"Texas_Bexar" int,
	"Texas_Blanco" int,
	"Texas_Borden" int,
	"Texas_Bosque" int,
	"Texas_Bowie" int,
	"Texas_Brazoria" int,
	"Texas_Brazos" int,
	"Texas_Brewster" int,
	"Texas_Briscoe" int,
	"Texas_Brooks" int,
	"Texas_Brown" int,
	"Texas_Burleson" int,
	"Texas_Burnet" int,
	"Texas_Caldwell" int,
	"Texas_Calhoun" int,
	"Texas_Callahan" int,
	"Texas_Cameron" int,
	"Texas_Camp" int,
	"Texas_Carson" int,
	"Texas_Cass" int,
	"Texas_Castro" int,
	"Texas_Chambers" int,
	"Texas_Cherokee" int,
	"Texas_Childress" int,
	"Texas_Clay" int,
	"Texas_Cochran" int,
	"Texas_Coke" int,
	"Texas_Coleman" int,
	"Texas_Collin" int,
	"Texas_Collingsworth" int,
	"Texas_Colorado" int,
	"Texas_Comal" int,
	"Texas_Comanche" int,
	"Texas_Concho" int,
	"Texas_Cooke" int,
	"Texas_Coryell" int,
	"Texas_Cottle" int,
	"Texas_Crane" int,
	"Texas_Crockett" int,
	"Texas_Crosby" int,
	"Texas_Culberson" int,
	"Texas_Dallam" int,
	"Texas_Dallas" int,
	"Texas_Dawson" int,
	"Texas_DeWitt" int,
	"Texas_Deaf Smith" int,
	"Texas_Delta" int,
	"Texas_Denton" int,
	"Texas_Dickens" int,
	"Texas_Dimmit" int,
	"Texas_Donley" int,
	"Texas_Duval" int,
	"Texas_Eastland" int,
	"Texas_Ector" int,
	"Texas_Edwards" int,
	"Texas_El Paso" int,
	"Texas_Ellis" int,
	"Texas_Erath" int,
	"Texas_Falls" int,
	"Texas_Fannin" int,
	"Texas_Fayette" int,
	"Texas_Fisher" int,
	"Texas_Floyd" int,
	"Texas_Foard" int,
	"Texas_Fort Bend" int,
	"Texas_Franklin" int,
	"Texas_Freestone" int,
	"Texas_Frio" int,
	"Texas_Gaines" int,
	"Texas_Galveston" int,
	"Texas_Garza" int,
	"Texas_Gillespie" int,
	"Texas_Glasscock" int,
	"Texas_Goliad" int,
	"Texas_Gonzales" int,
	"Texas_Gray" int,
	"Texas_Grayson" int,
	"Texas_Gregg" int,
	"Texas_Grimes" int,
	"Texas_Guadalupe" int,
	"Texas_Hale" int,
	"Texas_Hall" int,
	"Texas_Hamilton" int,
	"Texas_Hansford" int,
	"Texas_Hardeman" int,
	"Texas_Hardin" int,
	"Texas_Harris" int,
	"Texas_Harrison" int,
	"Texas_Hartley" int,
	"Texas_Haskell" int,
	"Texas_Hays" int,
	"Texas_Hemphill" int,
	"Texas_Henderson" int,
	"Texas_Hidalgo" int,
	"Texas_Hill" int,
	"Texas_Hockley" int,
	"Texas_Hood" int,
	"Texas_Hopkins" int,
	"Texas_Houston" int,
	"Texas_Howard" int,
	"Texas_Hudspeth" int,
	"Texas_Hunt" int,
	"Texas_Hutchinson" int,
	"Texas_Irion" int,
	"Texas_Jack" int,
	"Texas_Jackson" int,
	"Texas_Jasper" int,
	"Texas_Jeff Davis" int,
	"Texas_Jefferson" int,
	"Texas_Jim Hogg" int,
	"Texas_Jim Wells" int,
	"Texas_Johnson" int,
	"Texas_Jones" int,
	"Texas_Karnes" int,
	"Texas_Kaufman" int,
	"Texas_Kendall" int,
	"Texas_Kenedy" int,
	"Texas_Kent" int,
	"Texas_Kerr" int,
	"Texas_Kimble" int,
	"Texas_King" int,
	"Texas_Kinney" int,
	"Texas_Kleberg" int,
	"Texas_Knox" int,
	"Texas_La Salle" int,
	"Texas_Lamar" int,
	"Texas_Lamb" int,
	"Texas_Lampasas" int,
	"Texas_Lavaca" int,
	"Texas_Lee" int,
	"Texas_Leon" int,
	"Texas_Liberty" int,
	"Texas_Limestone" int,
	"Texas_Lipscomb" int,
	"Texas_Live Oak" int,
	"Texas_Llano" int,
	"Texas_Loving" int,
	"Texas_Lubbock" int,
	"Texas_Lynn" int,
	"Texas_Madison" int,
	"Texas_Marion" int,
	"Texas_Martin" int,
	"Texas_Mason" int,
	"Texas_Matagorda" int,
	"Texas_Maverick" int,
	"Texas_McCulloch" int,
	"Texas_McLennan" int,
	"Texas_McMullen" int,
	"Texas_Medina" int,
	"Texas_Menard" int,
	"Texas_Midland" int,
	"Texas_Milam" int,
	"Texas_Mills" int,
	"Texas_Mitchell" int,
	"Texas_Montague" int,
	"Texas_Montgomery" int,
	"Texas_Moore" int,
	"Texas_Morris" int,
	"Texas_Motley" int,
	"Texas_Nacogdoches" int,
	"Texas_Navarro" int,
	"Texas_Newton" int,
	"Texas_Nolan" int,
	"Texas_Nueces" int,
	"Texas_Ochiltree" int,
	"Texas_Oldham" int,
	"Texas_Orange" int,
	"Texas_Out of TX" int,
	"Texas_Palo Pinto" int,
	"Texas_Panola" int,
	"Texas_Parker" int,
	"Texas_Parmer" int,
	"Texas_Pecos" int,
	"Texas_Polk" int,
	"Texas_Potter" int,
	"Texas_Presidio" int,
	"Texas_Rains" int,
	"Texas_Randall" int,
	"Texas_Reagan" int,
	"Texas_Real" int,
	"Texas_Red River" int,
	"Texas_Reeves" int,
	"Texas_Refugio" int,
	"Texas_Roberts" int,
	"Texas_Robertson" int,
	"Texas_Rockwall" int,
	"Texas_Runnels" int,
	"Texas_Rusk" int,
	"Texas_Sabine" int,
	"Texas_San Augustine" int,
	"Texas_San Jacinto" int,
	"Texas_San Patricio" int,
	"Texas_San Saba" int,
	"Texas_Schleicher" int,
	"Texas_Scurry" int,
	"Texas_Shackelford" int,
	"Texas_Shelby" int,
	"Texas_Sherman" int,
	"Texas_Smith" int,
	"Texas_Somervell" int,
	"Texas_Starr" int,
	"Texas_Stephens" int,
	"Texas_Sterling" int,
	"Texas_Stonewall" int,
	"Texas_Sutton" int,
	"Texas_Swisher" int,
	"Texas_Tarrant" int,
	"Texas_Taylor" int,
	"Texas_Terrell" int,
	"Texas_Terry" int,
	"Texas_Throckmorton" int,
	"Texas_Titus" int,
	"Texas_Tom Green" int,
	"Texas_Travis" int,
	"Texas_Trinity" int,
	"Texas_Tyler" int,
	"Texas_Unassigned" int,
	"Texas_Upshur" int,
	"Texas_Upton" int,
	"Texas_Uvalde" int,
	"Texas_Val Verde" int,
	"Texas_Van Zandt" int,
	"Texas_Victoria" int,
	"Texas_Walker" int,
	"Texas_Waller" int,
	"Texas_Ward" int,
	"Texas_Washington" int,
	"Texas_Webb" int,
	"Texas_Wharton" int,
	"Texas_Wheeler" int,
	"Texas_Wichita" int,
	"Texas_Wilbarger" int,
	"Texas_Willacy" int,
	"Texas_Williamson" int,
	"Texas_Wilson" int,
	"Texas_Winkler" int,
	"Texas_Wise" int,
	"Texas_Wood" int,
	"Texas_Yoakum" int,
	"Texas_Young" int,
	"Texas_Zapata" int,
	"Texas_Zavala" int,
	"Utah_Bear River" int,
	"Utah_Beaver" int,
	"Utah_Box Elder" int,
	"Utah_Cache" int,
	"Utah_Carbon" int,
	"Utah_Central Utah" int,
	"Utah_Daggett" int,
	"Utah_Davis" int,
	"Utah_Duchesne" int,
	"Utah_Emery" int,
	"Utah_Garfield" int,
	"Utah_Grand" int,
	"Utah_Iron" int,
	"Utah_Juab" int,
	"Utah_Kane" int,
	"Utah_Millard" int,
	"Utah_Morgan" int,
	"Utah_Out of UT" int,
	"Utah_Piute" int,
	"Utah_Rich" int,
	"Utah_Salt Lake" int,
	"Utah_San Juan" int,
	"Utah_Sanpete" int,
	"Utah_Sevier" int,
	"Utah_Southeast Utah" int,
	"Utah_Southwest Utah" int,
	"Utah_Summit" int,
	"Utah_Tooele" int,
	"Utah_TriCounty" int,
	"Utah_Uintah" int,
	"Utah_Unassigned" int,
	"Utah_Utah" int,
	"Utah_Wasatch" int,
	"Utah_Washington" int,
	"Utah_Wayne" int,
	"Utah_Weber" int,
	"Utah_Weber-Morgan" int,
	"Vermont_Addison" int,
	"Vermont_Bennington" int,
	"Vermont_Caledonia" int,
	"Vermont_Chittenden" int,
	"Vermont_Essex" int,
	"Vermont_Franklin" int,
	"Vermont_Grand Isle" int,
	"Vermont_Lamoille" int,
	"Vermont_Orange" int,
	"Vermont_Orleans" int,
	"Vermont_Out of VT" int,
	"Vermont_Rutland" int,
	"Vermont_Unassigned" int,
	"Vermont_Washington" int,
	"Vermont_Windham" int,
	"Vermont_Windsor" int,
	"Virgin Islands" int,
	"Virginia_Accomack" int,
	"Virginia_Albemarle" int,
	"Virginia_Alexandria" int,
	"Virginia_Alleghany" int,
	"Virginia_Amelia" int,
	"Virginia_Amherst" int,
	"Virginia_Appomattox" int,
	"Virginia_Arlington" int,
	"Virginia_Augusta" int,
	"Virginia_Bath" int,
	"Virginia_Bedford" int,
	"Virginia_Bland" int,
	"Virginia_Botetourt" int,
	"Virginia_Bristol" int,
	"Virginia_Brunswick" int,
	"Virginia_Buchanan" int,
	"Virginia_Buckingham" int,
	"Virginia_Buena Vista" int,
	"Virginia_Campbell" int,
	"Virginia_Caroline" int,
	"Virginia_Carroll" int,
	"Virginia_Charles City" int,
	"Virginia_Charlotte" int,
	"Virginia_Charlottesville" int,
	"Virginia_Chesapeake" int,
	"Virginia_Chesterfield" int,
	"Virginia_Clarke" int,
	"Virginia_Colonial Heights" int,
	"Virginia_Covington" int,
	"Virginia_Craig" int,
	"Virginia_Culpeper" int,
	"Virginia_Cumberland" int,
	"Virginia_Danville" int,
	"Virginia_Dickenson" int,
	"Virginia_Dinwiddie" int,
	"Virginia_Emporia" int,
	"Virginia_Essex" int,
	"Virginia_Fairfax" int,
	"Virginia_Fairfax City" int,
	"Virginia_Falls Church" int,
	"Virginia_Fauquier" int,
	"Virginia_Floyd" int,
	"Virginia_Fluvanna" int,
	"Virginia_Franklin" int,
	"Virginia_Franklin City" int,
	"Virginia_Frederick" int,
	"Virginia_Fredericksburg" int,
	"Virginia_Galax" int,
	"Virginia_Giles" int,
	"Virginia_Gloucester" int,
	"Virginia_Goochland" int,
	"Virginia_Grayson" int,
	"Virginia_Greene" int,
	"Virginia_Greensville" int,
	"Virginia_Halifax" int,
	"Virginia_Hampton" int,
	"Virginia_Hanover" int,
	"Virginia_Harrisonburg" int,
	"Virginia_Henrico" int,
	"Virginia_Henry" int,
	"Virginia_Highland" int,
	"Virginia_Hopewell" int,
	"Virginia_Isle of Wight" int,
	"Virginia_James City" int,
	"Virginia_King George" int,
	"Virginia_King William" int,
	"Virginia_King and Queen" int,
	"Virginia_Lancaster" int,
	"Virginia_Lee" int,
	"Virginia_Lexington" int,
	"Virginia_Loudoun" int,
	"Virginia_Louisa" int,
	"Virginia_Lunenburg" int,
	"Virginia_Lynchburg" int,
	"Virginia_Madison" int,
	"Virginia_Manassas" int,
	"Virginia_Manassas Park" int,
	"Virginia_Martinsville" int,
	"Virginia_Mathews" int,
	"Virginia_Mecklenburg" int,
	"Virginia_Middlesex" int,
	"Virginia_Montgomery" int,
	"Virginia_Nelson" int,
	"Virginia_New Kent" int,
	"Virginia_Newport News" int,
	"Virginia_Norfolk" int,
	"Virginia_Northampton" int,
	"Virginia_Northumberland" int,
	"Virginia_Norton" int,
	"Virginia_Nottoway" int,
	"Virginia_Orange" int,
	"Virginia_Out of VA" int,
	"Virginia_Page" int,
	"Virginia_Patrick" int,
	"Virginia_Petersburg" int,
	"Virginia_Pittsylvania" int,
	"Virginia_Poquoson" int,
	"Virginia_Portsmouth" int,
	"Virginia_Powhatan" int,
	"Virginia_Prince Edward" int,
	"Virginia_Prince George" int,
	"Virginia_Prince William" int,
	"Virginia_Pulaski" int,
	"Virginia_Radford" int,
	"Virginia_Rappahannock" int,
	"Virginia_Richmond" int,
	"Virginia_Richmond City" int,
	"Virginia_Roanoke" int,
	"Virginia_Roanoke City" int,
	"Virginia_Rockbridge" int,
	"Virginia_Rockingham" int,
	"Virginia_Russell" int,
	"Virginia_Salem" int,
	"Virginia_Scott" int,
	"Virginia_Shenandoah" int,
	"Virginia_Smyth" int,
	"Virginia_Southampton" int,
	"Virginia_Spotsylvania" int,
	"Virginia_Stafford" int,
	"Virginia_Staunton" int,
	"Virginia_Suffolk" int,
	"Virginia_Surry" int,
	"Virginia_Sussex" int,
	"Virginia_Tazewell" int,
	"Virginia_Unassigned" int,
	"Virginia_Virginia Beach" int,
	"Virginia_Warren" int,
	"Virginia_Washington" int,
	"Virginia_Waynesboro" int,
	"Virginia_Westmoreland" int,
	"Virginia_Williamsburg" int,
	"Virginia_Winchester" int,
	"Virginia_Wise" int,
	"Virginia_Wythe" int,
	"Virginia_York" int,
	"Washington_Adams" int,
	"Washington_Asotin" int,
	"Washington_Benton" int,
	"Washington_Chelan" int,
	"Washington_Clallam" int,
	"Washington_Clark" int,
	"Washington_Columbia" int,
	"Washington_Cowlitz" int,
	"Washington_Douglas" int,
	"Washington_Ferry" int,
	"Washington_Franklin" int,
	"Washington_Garfield" int,
	"Washington_Grant" int,
	"Washington_Grays Harbor" int,
	"Washington_Island" int,
	"Washington_Jefferson" int,
	"Washington_King" int,
	"Washington_Kitsap" int,
	"Washington_Kittitas" int,
	"Washington_Klickitat" int,
	"Washington_Lewis" int,
	"Washington_Lincoln" int,
	"Washington_Mason" int,
	"Washington_Okanogan" int,
	"Washington_Out of WA" int,
	"Washington_Pacific" int,
	"Washington_Pend Oreille" int,
	"Washington_Pierce" int,
	"Washington_San Juan" int,
	"Washington_Skagit" int,
	"Washington_Skamania" int,
	"Washington_Snohomish" int,
	"Washington_Spokane" int,
	"Washington_Stevens" int,
	"Washington_Thurston" int,
	"Washington_Unassigned" int,
	"Washington_Wahkiakum" int,
	"Washington_Walla Walla" int,
	"Washington_Whatcom" int,
	"Washington_Whitman" int,
	"Washington_Yakima" int,
	"West Virginia_Barbour" int,
	"West Virginia_Berkeley" int,
	"West Virginia_Boone" int,
	"West Virginia_Braxton" int,
	"West Virginia_Brooke" int,
	"West Virginia_Cabell" int,
	"West Virginia_Calhoun" int,
	"West Virginia_Clay" int,
	"West Virginia_Doddridge" int,
	"West Virginia_Fayette" int,
	"West Virginia_Gilmer" int,
	"West Virginia_Grant" int,
	"West Virginia_Greenbrier" int,
	"West Virginia_Hampshire" int,
	"West Virginia_Hancock" int,
	"West Virginia_Hardy" int,
	"West Virginia_Harrison" int,
	"West Virginia_Jackson" int,
	"West Virginia_Jefferson" int,
	"West Virginia_Kanawha" int,
	"West Virginia_Lewis" int,
	"West Virginia_Lincoln" int,
	"West Virginia_Logan" int,
	"West Virginia_Marion" int,
	"West Virginia_Marshall" int,
	"West Virginia_Mason" int,
	"West Virginia_McDowell" int,
	"West Virginia_Mercer" int,
	"West Virginia_Mineral" int,
	"West Virginia_Mingo" int,
	"West Virginia_Monongalia" int,
	"West Virginia_Monroe" int,
	"West Virginia_Morgan" int,
	"West Virginia_Nicholas" int,
	"West Virginia_Ohio" int,
	"West Virginia_Out of WV" int,
	"West Virginia_Pendleton" int,
	"West Virginia_Pleasants" int,
	"West Virginia_Pocahontas" int,
	"West Virginia_Preston" int,
	"West Virginia_Putnam" int,
	"West Virginia_Raleigh" int,
	"West Virginia_Randolph" int,
	"West Virginia_Ritchie" int,
	"West Virginia_Roane" int,
	"West Virginia_Summers" int,
	"West Virginia_Taylor" int,
	"West Virginia_Tucker" int,
	"West Virginia_Tyler" int,
	"West Virginia_Unassigned" int,
	"West Virginia_Upshur" int,
	"West Virginia_Wayne" int,
	"West Virginia_Webster" int,
	"West Virginia_Wetzel" int,
	"West Virginia_Wirt" int,
	"West Virginia_Wood" int,
	"West Virginia_Wyoming" int,
	"Wisconsin_Adams" int,
	"Wisconsin_Ashland" int,
	"Wisconsin_Barron" int,
	"Wisconsin_Bayfield" int,
	"Wisconsin_Brown" int,
	"Wisconsin_Buffalo" int,
	"Wisconsin_Burnett" int,
	"Wisconsin_Calumet" int,
	"Wisconsin_Chippewa" int,
	"Wisconsin_Clark" int,
	"Wisconsin_Columbia" int,
	"Wisconsin_Crawford" int,
	"Wisconsin_Dane" int,
	"Wisconsin_Dodge" int,
	"Wisconsin_Door" int,
	"Wisconsin_Douglas" int,
	"Wisconsin_Dunn" int,
	"Wisconsin_Eau Claire" int,
	"Wisconsin_Florence" int,
	"Wisconsin_Fond du Lac" int,
	"Wisconsin_Forest" int,
	"Wisconsin_Grant" int,
	"Wisconsin_Green" int,
	"Wisconsin_Green Lake" int,
	"Wisconsin_Iowa" int,
	"Wisconsin_Iron" int,
	"Wisconsin_Jackson" int,
	"Wisconsin_Jefferson" int,
	"Wisconsin_Juneau" int,
	"Wisconsin_Kenosha" int,
	"Wisconsin_Kewaunee" int,
	"Wisconsin_La Crosse" int,
	"Wisconsin_Lafayette" int,
	"Wisconsin_Langlade" int,
	"Wisconsin_Lincoln" int,
	"Wisconsin_Manitowoc" int,
	"Wisconsin_Marathon" int,
	"Wisconsin_Marinette" int,
	"Wisconsin_Marquette" int,
	"Wisconsin_Menominee" int,
	"Wisconsin_Milwaukee" int,
	"Wisconsin_Monroe" int,
	"Wisconsin_Oconto" int,
	"Wisconsin_Oneida" int,
	"Wisconsin_Out of WI" int,
	"Wisconsin_Outagamie" int,
	"Wisconsin_Ozaukee" int,
	"Wisconsin_Pepin" int,
	"Wisconsin_Pierce" int,
	"Wisconsin_Polk" int,
	"Wisconsin_Portage" int,
	"Wisconsin_Price" int,
	"Wisconsin_Racine" int,
	"Wisconsin_Richland" int,
	"Wisconsin_Rock" int,
	"Wisconsin_Rusk" int,
	"Wisconsin_Sauk" int,
	"Wisconsin_Sawyer" int,
	"Wisconsin_Shawano" int,
	"Wisconsin_Sheboygan" int,
	"Wisconsin_St. Croix" int,
	"Wisconsin_Taylor" int,
	"Wisconsin_Trempealeau" int,
	"Wisconsin_Unassigned" int,
	"Wisconsin_Vernon" int,
	"Wisconsin_Vilas" int,
	"Wisconsin_Walworth" int,
	"Wisconsin_Washburn" int,
	"Wisconsin_Washington" int,
	"Wisconsin_Waukesha" int,
	"Wisconsin_Waupaca" int,
	"Wisconsin_Waushara" int,
	"Wisconsin_Winnebago" int,
	"Wisconsin_Wood" int,
	"Wyoming_Albany" int,
	"Wyoming_Big Horn" int,
	"Wyoming_Campbell" int,
	"Wyoming_Carbon" int,
	"Wyoming_Converse" int,
	"Wyoming_Crook" int,
	"Wyoming_Fremont" int,
	"Wyoming_Goshen" int,
	"Wyoming_Hot Springs" int,
	"Wyoming_Johnson" int,
	"Wyoming_Laramie" int,
	"Wyoming_Lincoln" int,
	"Wyoming_Natrona" int,
	"Wyoming_Niobrara" int,
	"Wyoming_Out of WY" int,
	"Wyoming_Park" int,
	"Wyoming_Platte" int,
	"Wyoming_Sheridan" int,
	"Wyoming_Sublette" int,
	"Wyoming_Sweetwater" int,
	"Wyoming_Teton" int,
	"Wyoming_Uinta" int,
	"Wyoming_Unassigned" int,
	"Wyoming_Washakie" int,
	"Wyoming_Weston" int
);